export type SlotManufacturer = 
  | 'Aristocrat'
  | 'IGT'
  | 'Konami'
  | 'Everi'
  | 'Light & Wonder'
  | 'AGS'
  | 'Ainsworth'
  | 'Bally'
  | 'Other';

export type SlotVolatility = 'Low' | 'Medium-Low' | 'Medium' | 'Medium-High' | 'High' | 'Very High';

export type CabinetType = 
  | 'Standard Upright'
  | 'Slant Top'
  | 'Curved'
  | 'Pod'
  | 'Multi-Screen'
  | 'Mechanical'
  | 'Video'
  | 'Other';

export type PersistenceType = 'True' | 'Pseudo' | 'None';

export type GlobalSlotMachine = {
  id: string;
  name: string;
  manufacturer: SlotManufacturer;
  gameSeries?: string;
  volatility: SlotVolatility;
  cabinetType: CabinetType;
  releaseYear: number;
  rtpRange?: string;
  basePay?: string;
  bonusMechanic?: string;
  jackpotTypes?: string[];
  denominationFamilies?: string[];
  persistenceType?: PersistenceType;
  hasMHB?: boolean;
  theme?: string;
  description?: string;
};

export const GLOBAL_SLOT_MACHINES_2020_2025: GlobalSlotMachine[] = [
  {
    id: 'dragon-link-golden-century',
    name: 'Dragon Link - Golden Century',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dragon Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRange: '87-92%',
    bonusMechanic: 'Free Games with Persistent State',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'True',
    hasMHB: true,
    theme: 'Asian/Dragon',
  },
  {
    id: 'dragon-link-panda-magic',
    name: 'Dragon Link - Panda Magic',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dragon Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    rtpRange: '87-92%',
    bonusMechanic: 'Free Games with Persistent State',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'True',
    hasMHB: true,
    theme: 'Asian/Panda',
  },
  {
    id: 'dragon-link-genghis-khan',
    name: 'Dragon Link - Genghis Khan',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dragon Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRange: '87-92%',
    bonusMechanic: 'Free Games with Persistent State',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'True',
    hasMHB: true,
    theme: 'Asian/Historical',
  },
  {
    id: 'lightning-link-best-bet',
    name: 'Lightning Link - Best Bet',
    manufacturer: 'Aristocrat',
    gameSeries: 'Lightning Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRange: '88-92%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.10'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Classic',
  },
  {
    id: 'lightning-link-high-stakes',
    name: 'Lightning Link - High Stakes',
    manufacturer: 'Aristocrat',
    gameSeries: 'Lightning Link',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    rtpRange: '88-92%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Casino',
  },
  {
    id: 'ultimate-fire-link-china-street',
    name: 'Ultimate Fire Link - China Street',
    manufacturer: 'Bally',
    gameSeries: 'Ultimate Fire Link',
    volatility: 'Medium-High',
    cabinetType: 'Multi-Screen',
    releaseYear: 2022,
    rtpRange: '85-90%',
    bonusMechanic: 'Hold & Spin with Multipliers',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Asian',
  },
  {
    id: 'ultimate-fire-link-olvera-street',
    name: 'Ultimate Fire Link - Olvera Street',
    manufacturer: 'Bally',
    gameSeries: 'Ultimate Fire Link',
    volatility: 'Medium-High',
    cabinetType: 'Multi-Screen',
    releaseYear: 2022,
    rtpRange: '85-90%',
    bonusMechanic: 'Hold & Spin with Multipliers',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Mexican',
  },
  {
    id: 'money-link-dynasty',
    name: 'Money Link - Dynasty',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Money Link',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2023,
    rtpRange: '88-92%',
    bonusMechanic: 'Link Feature',
    jackpotTypes: ['Mega', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Asian',
  },
  {
    id: 'huff-n-puff',
    name: "Huff N' Puff",
    manufacturer: 'Aristocrat',
    gameSeries: 'Huff N Puff',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    rtpRange: '87-91%',
    bonusMechanic: 'Progressive Collection Feature',
    jackpotTypes: ['Grand', 'Major', 'Minor'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'True',
    hasMHB: true,
    theme: 'Three Little Pigs',
  },
  {
    id: 'money-mansion',
    name: 'Money Mansion',
    manufacturer: 'Aristocrat',
    gameSeries: 'Money Mansion',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2023,
    rtpRange: '87-91%',
    bonusMechanic: 'Collect & Win Feature',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'True',
    hasMHB: true,
    theme: 'Luxury/Mansion',
  },
  {
    id: '88-fortunes',
    name: '88 Fortunes',
    manufacturer: 'Light & Wonder',
    gameSeries: '88 Fortunes',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRange: '86-96%',
    bonusMechanic: 'Fu Bat Jackpot Feature',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.88', '$1.88', '$2.88'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian',
  },
  {
    id: 'bao-zhu-zhao-fu',
    name: 'Bao Zhu Zhao Fu',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Bao Zhu',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    rtpRange: '86-94%',
    bonusMechanic: 'Free Games with Wild Features',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian',
  },
  {
    id: 'dancing-drums',
    name: 'Dancing Drums',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Dancing Drums',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRange: '86-96%',
    bonusMechanic: 'Fu Bat Jackpot & Free Games',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.88', '$2.88', '$8.88'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian/Drums',
  },
  {
    id: 'dancing-drums-explosion',
    name: 'Dancing Drums Explosion',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Dancing Drums',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2022,
    rtpRange: '86-96%',
    bonusMechanic: 'Fu Bat Jackpot & Enhanced Free Games',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.88', '$2.88', '$8.88'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian/Drums',
  },
  {
    id: 'mighty-cash-outback-bucks',
    name: 'Mighty Cash - Outback Bucks',
    manufacturer: 'Aristocrat',
    gameSeries: 'Mighty Cash',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRange: '87-92%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Australian',
  },
  {
    id: 'rakin-bacon',
    name: "Rakin' Bacon",
    manufacturer: 'IGT',
    gameSeries: 'Rakin Bacon',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    rtpRange: '85-94%',
    bonusMechanic: 'Collection Feature with Persistent Meter',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'True',
    hasMHB: true,
    theme: 'Pigs/Bacon',
  },
  {
    id: 'rich-little-piggies',
    name: 'Rich Little Piggies',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Rich Little Piggies',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '86-96%',
    bonusMechanic: 'Pick & Match Bonus',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Pigs',
  },
  {
    id: 'wonder-4-tower',
    name: 'Wonder 4 Tower',
    manufacturer: 'Aristocrat',
    gameSeries: 'Wonder 4',
    volatility: 'Medium',
    cabinetType: 'Multi-Screen',
    releaseYear: 2020,
    rtpRange: '87-92%',
    bonusMechanic: 'Multi-Game Selection with Free Games',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Multi-Theme',
  },
  {
    id: 'dollar-storm',
    name: 'Dollar Storm',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dollar Storm',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    rtpRange: '87-91%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Classic',
  },
  {
    id: 'cash-express-more-cash',
    name: 'Cash Express - More Cash',
    manufacturer: 'Aristocrat',
    gameSeries: 'Cash Express',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2022,
    rtpRange: '87-92%',
    bonusMechanic: 'Collection Feature',
    jackpotTypes: ['Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'True',
    hasMHB: false,
    theme: 'Train',
  },
  {
    id: 'fire-link-pillars',
    name: 'Fire Link - Pillars of Ra',
    manufacturer: 'Bally',
    gameSeries: 'Fire Link',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '85-92%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Egyptian',
  },
  {
    id: 'fu-dai-lian-lian-panda',
    name: 'Fu Dai Lian Lian - Panda',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Fu Dai Lian Lian',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2021,
    rtpRange: '86-94%',
    bonusMechanic: 'Link Feature',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Asian/Panda',
  },
  {
    id: 'cashman-las-vegas',
    name: 'Cashman - Las Vegas',
    manufacturer: 'Aristocrat',
    gameSeries: 'Cashman',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '87-92%',
    bonusMechanic: 'Hold & Spin with Cashman',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Las Vegas',
  },
  {
    id: 'buffalo-gold',
    name: 'Buffalo Gold',
    manufacturer: 'Aristocrat',
    gameSeries: 'Buffalo',
    volatility: 'High',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '87-94%',
    bonusMechanic: 'Free Games with Multipliers',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Buffalo/Native American',
  },
  {
    id: 'buffalo-chief',
    name: 'Buffalo Chief',
    manufacturer: 'Aristocrat',
    gameSeries: 'Buffalo',
    volatility: 'High',
    cabinetType: 'Video',
    releaseYear: 2021,
    rtpRange: '87-94%',
    bonusMechanic: 'Free Games with Multipliers',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Buffalo/Native American',
  },
  {
    id: 'buffalo-link',
    name: 'Buffalo Link',
    manufacturer: 'Aristocrat',
    gameSeries: 'Buffalo',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2022,
    rtpRange: '87-92%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Buffalo/Native American',
  },
  {
    id: 'buffalo-ascension',
    name: 'Buffalo Ascension',
    manufacturer: 'Aristocrat',
    gameSeries: 'Buffalo',
    volatility: 'High',
    cabinetType: 'Multi-Screen',
    releaseYear: 2023,
    rtpRange: '87-92%',
    bonusMechanic: 'Progressive Free Games',
    jackpotTypes: ['Mega', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Buffalo/Native American',
  },
  {
    id: 'jin-ji-bao-xi',
    name: 'Jin Ji Bao Xi',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Jin Ji Bao Xi',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRange: '86-96%',
    bonusMechanic: 'Pick Feature',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.88', '$1.88'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian',
  },
  {
    id: 'lock-it-link-diamonds',
    name: 'Lock It Link - Diamonds',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Lock It Link',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    rtpRange: '88-96%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Diamonds',
  },
  {
    id: 'lock-it-link-cats-hats-bats',
    name: 'Lock It Link - Cats Hats Bats',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Lock It Link',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2022,
    rtpRange: '88-96%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Magic/Cats',
  },
  {
    id: 'wheel-of-fortune-triple-extreme-spin',
    name: 'Wheel of Fortune - Triple Extreme Spin',
    manufacturer: 'IGT',
    gameSeries: 'Wheel of Fortune',
    volatility: 'Medium',
    cabinetType: 'Multi-Screen',
    releaseYear: 2022,
    rtpRange: '85-94%',
    bonusMechanic: 'Wheel Bonus',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Wheel of Fortune',
  },
  {
    id: 'triple-diamond',
    name: 'Triple Diamond',
    manufacturer: 'IGT',
    gameSeries: 'Triple Diamond',
    volatility: 'High',
    cabinetType: 'Mechanical',
    releaseYear: 2020,
    rtpRange: '92-96%',
    bonusMechanic: 'None (Classic 3-Reel)',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$1.00', '$5.00'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Classic',
  },
  {
    id: 'double-diamond',
    name: 'Double Diamond',
    manufacturer: 'IGT',
    gameSeries: 'Double Diamond',
    volatility: 'Medium-High',
    cabinetType: 'Mechanical',
    releaseYear: 2020,
    rtpRange: '92-96%',
    bonusMechanic: 'None (Classic 3-Reel)',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$1.00', '$5.00'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Classic',
  },
  {
    id: 'blazing-7s',
    name: "Blazing 7's",
    manufacturer: 'Bally',
    gameSeries: 'Blazing 7s',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '88-94%',
    bonusMechanic: 'None (Classic Style)',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.25', '$1.00'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Classic',
  },
  {
    id: 'lightning-zap',
    name: 'Lightning Zap',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Lightning Zap',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2023,
    rtpRange: '88-94%',
    bonusMechanic: 'Lightning Feature',
    jackpotTypes: ['Mega', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Lightning',
  },
  {
    id: 'dragon-train',
    name: 'Dragon Train',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dragon Train',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2024,
    rtpRange: '87-92%',
    bonusMechanic: 'Collection Feature',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'True',
    hasMHB: true,
    theme: 'Asian/Dragon',
  },
  {
    id: 'gold-bonanza',
    name: 'Gold Bonanza',
    manufacturer: 'Aristocrat',
    gameSeries: 'Gold Bonanza',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2024,
    rtpRange: '87-91%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Gold/Mining',
  },
  {
    id: 'lantern-festival',
    name: 'Lantern Festival',
    manufacturer: 'Konami',
    gameSeries: 'Lantern Festival',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2023,
    rtpRange: '86-93%',
    bonusMechanic: 'Free Games with Wild Features',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian/Lanterns',
  },
  {
    id: 'lotus-land',
    name: 'Lotus Land',
    manufacturer: 'Konami',
    gameSeries: 'Lotus Land',
    volatility: 'Medium-High',
    cabinetType: 'Pod',
    releaseYear: 2022,
    rtpRange: '86-93%',
    bonusMechanic: 'Action Stacked Symbols',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian/Lotus',
  },
  {
    id: 'fortune-coin',
    name: 'Fortune Coin',
    manufacturer: 'IGT',
    gameSeries: 'Fortune Coin',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2023,
    rtpRange: '85-94%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Mega', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Asian/Coin',
  },
  {
    id: 'moon-rabbit',
    name: 'Moon Rabbit',
    manufacturer: 'Konami',
    gameSeries: 'Moon Rabbit',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2024,
    rtpRange: '86-92%',
    bonusMechanic: 'Free Games',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian/Rabbit',
  },
  {
    id: 'prosperity-lion',
    name: 'Prosperity Lion',
    manufacturer: 'Aristocrat',
    gameSeries: 'Prosperity',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2023,
    rtpRange: '87-92%',
    bonusMechanic: 'Free Games with Multipliers',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian/Lion',
  },
  {
    id: 'fu-fu-fu',
    name: 'Fu Fu Fu',
    manufacturer: 'IGT',
    gameSeries: 'Fu Fu Fu',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2022,
    rtpRange: '85-94%',
    bonusMechanic: 'Pick Bonus',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian',
  },
  {
    id: 'golden-rooster',
    name: 'Golden Rooster',
    manufacturer: 'Konami',
    gameSeries: 'Golden Rooster',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    rtpRange: '86-92%',
    bonusMechanic: 'Free Games with Enhanced Features',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian/Rooster',
  },
  {
    id: 'scarab',
    name: 'Scarab',
    manufacturer: 'IGT',
    gameSeries: 'Scarab',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    rtpRange: '85-96%',
    bonusMechanic: 'Free Games with Expanding Symbols',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Egyptian',
  },
  {
    id: 'cleopatra',
    name: 'Cleopatra',
    manufacturer: 'IGT',
    gameSeries: 'Cleopatra',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '92-96%',
    bonusMechanic: 'Free Games with Multipliers',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Egyptian',
  },
  {
    id: 'kitty-glitter',
    name: 'Kitty Glitter',
    manufacturer: 'IGT',
    gameSeries: 'Kitty Glitter',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '92-94%',
    bonusMechanic: 'Free Games',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Cats',
  },
  {
    id: 'cats-hats-more-bats',
    name: 'Cats Hats & More Bats',
    manufacturer: 'Aristocrat',
    gameSeries: 'Cats Hats',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2023,
    rtpRange: '87-92%',
    bonusMechanic: 'Hold & Spin',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'Pseudo',
    hasMHB: false,
    theme: 'Magic/Cats',
  },
  {
    id: 'timber-wolf',
    name: 'Timber Wolf',
    manufacturer: 'Aristocrat',
    gameSeries: 'Timber Wolf',
    volatility: 'High',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '87-94%',
    bonusMechanic: 'Free Games',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Wolf/Nature',
  },
  {
    id: 'stinkin-rich',
    name: "Stinkin' Rich",
    manufacturer: 'IGT',
    gameSeries: 'Stinkin Rich',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '88-94%',
    bonusMechanic: 'Pick Bonus',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Skunk/Money',
  },
  {
    id: 'top-dollar',
    name: 'Top Dollar',
    manufacturer: 'IGT',
    gameSeries: 'Top Dollar',
    volatility: 'Medium-High',
    cabinetType: 'Mechanical',
    releaseYear: 2020,
    rtpRange: '92-95%',
    bonusMechanic: 'None (Classic 3-Reel)',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$1.00', '$5.00'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Classic/Money',
  },
  {
    id: 'monopoly-hot-shot',
    name: 'Monopoly Hot Shot',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Monopoly',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2022,
    rtpRange: '88-94%',
    bonusMechanic: 'Monopoly Bonus',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Monopoly',
  },
  {
    id: 'deal-or-no-deal',
    name: 'Deal or No Deal',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Deal or No Deal',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    rtpRange: '88-94%',
    bonusMechanic: 'Pick Bonus',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Game Show',
  },
  {
    id: 'wheel-of-fortune-gold-spin',
    name: 'Wheel of Fortune Gold Spin',
    manufacturer: 'IGT',
    gameSeries: 'Wheel of Fortune',
    volatility: 'Medium',
    cabinetType: 'Multi-Screen',
    releaseYear: 2024,
    rtpRange: '85-94%',
    bonusMechanic: 'Wheel Bonus with Enhanced Features',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Wheel of Fortune',
  },
  {
    id: 'tarzan',
    name: 'Tarzan',
    manufacturer: 'Aristocrat',
    gameSeries: 'Tarzan',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    rtpRange: '87-92%',
    bonusMechanic: 'Free Games with Progressive Features',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Tarzan/Jungle',
  },
  {
    id: 'king-kong-cash',
    name: 'King Kong Cash',
    manufacturer: 'Light & Wonder',
    gameSeries: 'King Kong',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2022,
    rtpRange: '88-96%',
    bonusMechanic: 'Multiple Features',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'King Kong',
  },
  {
    id: 'quick-hit-platinum',
    name: 'Quick Hit Platinum',
    manufacturer: 'Bally',
    gameSeries: 'Quick Hit',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '88-94%',
    bonusMechanic: 'Free Games',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Classic',
  },
  {
    id: 'quick-hit-ultra-pays',
    name: 'Quick Hit Ultra Pays',
    manufacturer: 'Bally',
    gameSeries: 'Quick Hit',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2023,
    rtpRange: '88-94%',
    bonusMechanic: 'Free Games with Enhanced Pays',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Classic',
  },
  {
    id: 'china-shores',
    name: 'China Shores',
    manufacturer: 'Konami',
    gameSeries: 'China Shores',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '86-92%',
    bonusMechanic: 'Action Stacked Symbols',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Asian',
  },
  {
    id: 'mystical-unicorn',
    name: 'Mystical Unicorn',
    manufacturer: 'Bally',
    gameSeries: 'Mystical Unicorn',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '88-94%',
    bonusMechanic: 'Free Games',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Fantasy/Unicorn',
  },
  {
    id: 'michael-jackson',
    name: 'Michael Jackson',
    manufacturer: 'Bally',
    gameSeries: 'Michael Jackson',
    volatility: 'Medium-High',
    cabinetType: 'Multi-Screen',
    releaseYear: 2021,
    rtpRange: '88-94%',
    bonusMechanic: 'Multiple Music-Themed Features',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Music/Michael Jackson',
  },
  {
    id: 'elvis-the-king',
    name: 'Elvis - The King',
    manufacturer: 'IGT',
    gameSeries: 'Elvis',
    volatility: 'Medium',
    cabinetType: 'Multi-Screen',
    releaseYear: 2022,
    rtpRange: '85-94%',
    bonusMechanic: 'Multiple Music-Themed Features',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Music/Elvis',
  },
  {
    id: 'game-of-thrones',
    name: 'Game of Thrones',
    manufacturer: 'Aristocrat',
    gameSeries: 'Game of Thrones',
    volatility: 'Medium-High',
    cabinetType: 'Multi-Screen',
    releaseYear: 2020,
    rtpRange: '87-92%',
    bonusMechanic: 'Free Games with Multiple Game Modes',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Game of Thrones',
  },
  {
    id: 'walking-dead',
    name: 'The Walking Dead',
    manufacturer: 'Aristocrat',
    gameSeries: 'Walking Dead',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    rtpRange: '87-92%',
    bonusMechanic: 'Free Games with Walker Features',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Walking Dead',
  },
  {
    id: 'wicked-winnings',
    name: 'Wicked Winnings',
    manufacturer: 'Aristocrat',
    gameSeries: 'Wicked Winnings',
    volatility: 'High',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '87-94%',
    bonusMechanic: 'Free Games',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Wizard/Magic',
  },
  {
    id: 'zeus',
    name: 'Zeus',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Zeus',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '88-96%',
    bonusMechanic: 'Free Games',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Greek Mythology',
  },
  {
    id: 'zeus-unleashed',
    name: 'Zeus Unleashed',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Zeus',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2023,
    rtpRange: '88-96%',
    bonusMechanic: 'Free Games with Enhanced Features',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Greek Mythology',
  },
  {
    id: 'kronos',
    name: 'Kronos',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Kronos',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2020,
    rtpRange: '88-96%',
    bonusMechanic: 'Free Games with Stacked Wilds',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Greek Mythology',
  },
  {
    id: 'spartacus',
    name: 'Spartacus',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Spartacus',
    volatility: 'Medium-High',
    cabinetType: 'Multi-Screen',
    releaseYear: 2020,
    rtpRange: '88-96%',
    bonusMechanic: 'Colossal Reels Free Games',
    jackpotTypes: ['Fixed'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Ancient Rome',
  },
  {
    id: 'wizard-of-oz',
    name: 'Wizard of Oz',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Wizard of Oz',
    volatility: 'Medium',
    cabinetType: 'Multi-Screen',
    releaseYear: 2020,
    rtpRange: '88-96%',
    bonusMechanic: 'Multiple Oz-Themed Features',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Wizard of Oz',
  },
  {
    id: 'sex-and-the-city',
    name: 'Sex and the City',
    manufacturer: 'IGT',
    gameSeries: 'Sex and the City',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    rtpRange: '85-94%',
    bonusMechanic: 'Pick Bonus',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Sex and the City',
  },
  {
    id: 'family-guy',
    name: 'Family Guy',
    manufacturer: 'IGT',
    gameSeries: 'Family Guy',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2022,
    rtpRange: '85-94%',
    bonusMechanic: 'Multiple Character Features',
    jackpotTypes: ['Progressive'],
    denominationFamilies: ['$0.01', '$0.02'],
    persistenceType: 'None',
    hasMHB: false,
    theme: 'Family Guy',
  },
  {
    id: 'flaming-hot-pots-mr-lee',
    name: 'Flaming Hot Pots — Mr. Lee',
    manufacturer: 'Aristocrat',
    gameSeries: 'Flaming Hot Pots',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2023,
    rtpRange: '87-91%',
    bonusMechanic: 'Multi-Pot Progressive with Hold & Spin (Yummy/Spicy/Upsized)',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.10', '$1.00'],
    persistenceType: 'True',
    hasMHB: true,
    theme: 'Asian/Food',
    description: 'The Mr. Lee version of Flaming Hot Pots centers around the three jackpot pots—Yummy, Spicy, and Upsized. The Spicy pot uses strawberry symbols labeled Mini, Minor, or Major, each of which adds the full jackpot value to every credit prize on the board when it lands. Upsized expands the bonus grid, giving even more chances for these huge credit-adders. Jackpots reset around $10–15 (Mini), $40–75 (Minor), $500–1,000 (Major), and $8,000–12,000 (Grand), with the Major being the main AP signal. The game becomes worth playing when the Upsized or Spicy pots are visibly full, the Major is inflated, or Mini/Minor values are unusually high. The 1¢ denom is the optimal AP entry because jackpots are shared across denoms. Avoid when pots are empty or after any pot has just triggered.',
  },
  {
    id: 'flaming-hot-pots-ms-wong',
    name: 'Flaming Hot Pots — Ms. Wong',
    manufacturer: 'Aristocrat',
    gameSeries: 'Flaming Hot Pots',
    volatility: 'Very High',
    cabinetType: 'Curved',
    releaseYear: 2023,
    rtpRange: '87-91%',
    bonusMechanic: 'Multi-Pot Progressive with Hold & Spin (Yummy/Spicy/Upsized)',
    jackpotTypes: ['Grand', 'Major', 'Minor', 'Mini'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.10', '$1.00'],
    persistenceType: 'True',
    hasMHB: true,
    theme: 'Asian/Food',
    description: 'Ms. Wong\'s Flaming Hot Pots uses the same Yummy, Spicy, and Upsized pots as Mr. Lee, but the values and volatility are higher. Her Spicy strawberries have greater chances of landing Major and Minor adders, and the Upsized pot expands the bonus grid even more, allowing Major-value adders to flood the board. Jackpots reset around $10–18 (Mini), $50–80 (Minor), $600–1,200 (Major), and $8,000–12,500 (Grand). This machine becomes profitable for AP players when the Upsized pot is nearly full or when both the Spicy and Upsized pots are elevated together. The 1¢ denom is best for progressive chasing, while 2¢ gives better overall bonus performance. Avoid when only the Yummy pot is high or immediately after a pot-trigger event.',
  },
];
