import { GlobalSlotMachine } from './globalSlotMachinesDatabase';

export const QUANTUM_OF_THE_SEAS_MACHINES: GlobalSlotMachine[] = [
  {
    id: '88-fortunes',
    name: '88 Fortunes',
    manufacturer: 'Light & Wonder',
    gameSeries: '88 Fortunes',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2020,
    theme: 'Asian',
  },
  {
    id: 'bao-zhu-zhao-fu',
    name: 'Bao Zhu Zhao Fu',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Bao Zhu',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    theme: 'Asian',
  },
  {
    id: 'flaming-hot-pots-mr-lee',
    name: 'Big Hot Flaming Pots (Mr. Lee & Ms. Wong)',
    manufacturer: 'Aristocrat',
    gameSeries: 'Flaming Hot Pots',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2023,
    theme: 'Asian/Food',
  },
  {
    id: 'buffalo-gold',
    name: 'Buffalo Gold',
    manufacturer: 'Aristocrat',
    gameSeries: 'Buffalo',
    volatility: 'High',
    cabinetType: 'Video',
    releaseYear: 2020,
    theme: 'Buffalo/Native American',
  },
  {
    id: 'cosmic-cat',
    name: 'Cosmic Cat',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    theme: 'Space/Cat',
  },
  {
    id: 'dancing-drums',
    name: 'Dancing Drums',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Dancing Drums',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    theme: 'Asian/Drums',
  },
  {
    id: 'dragon-link-golden-century',
    name: 'Dragon Link – Golden Century',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dragon Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    theme: 'Asian/Dragon',
  },
  {
    id: 'dragon-link-autumn-moon',
    name: 'Dragon Link – Autumn Moon',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dragon Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    theme: 'Asian/Dragon',
  },
  {
    id: 'dragon-link-panda-magic',
    name: 'Dragon Link – Panda Magic',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dragon Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    theme: 'Asian/Panda',
  },
  {
    id: 'dragon-link-happy-prosperous',
    name: 'Dragon Link – Happy & Prosperous',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dragon Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2022,
    theme: 'Asian/Dragon',
  },
  {
    id: 'fire-link-pillars-cash',
    name: 'Fire Link – Pillars of Cash',
    manufacturer: 'Bally',
    gameSeries: 'Fire Link',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2020,
    theme: 'Egyptian',
  },
  {
    id: 'fire-link-island-rising',
    name: 'Fire Link – Island Rising',
    manufacturer: 'Bally',
    gameSeries: 'Fire Link',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Island',
  },
  {
    id: 'huff-n-puff',
    name: "Huff N' Puff",
    manufacturer: 'Aristocrat',
    gameSeries: 'Huff N Puff',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    theme: 'Three Little Pigs',
  },
  {
    id: 'huff-n-more-puff',
    name: "Huff N' More Puff",
    manufacturer: 'Aristocrat',
    gameSeries: 'Huff N Puff',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2022,
    theme: 'Three Little Pigs',
  },
  {
    id: 'huff-n-puff-money-mansion',
    name: "Huff N' Puff — Money Mansion",
    manufacturer: 'Aristocrat',
    gameSeries: 'Huff N Puff',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2023,
    theme: 'Three Little Pigs',
  },
  {
    id: 'jade-tree',
    name: 'Jade Tree',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Asian',
  },
  {
    id: 'lightning-link-best-bet',
    name: 'Lightning Link',
    manufacturer: 'Aristocrat',
    gameSeries: 'Lightning Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    theme: 'Classic',
  },
  {
    id: 'lock-it-link-leprechaun',
    name: 'Lock It Link – Leprechaun',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Lock It Link',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Irish/Leprechaun',
  },
  {
    id: 'lock-it-link-piggy-bank',
    name: 'Lock It Link – Piggy Bank',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Lock It Link',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2022,
    theme: 'Pigs',
  },
  {
    id: 'lucky-leprechauns',
    name: 'Lucky Leprechauns',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    theme: 'Irish/Leprechaun',
  },
  {
    id: 'mo-mo-mummy',
    name: 'Mo Mo Mummy',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Egyptian/Mummy',
  },
  {
    id: 'spooky-mummy',
    name: 'Spooky Mummy',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Egyptian/Mummy',
  },
  {
    id: 'yeti',
    name: 'Yeti',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    theme: 'Arctic/Yeti',
  },
  {
    id: 'red-hot-chile',
    name: 'Red Hot Chile',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Chile Peppers',
  },
  {
    id: 'timber-wolf',
    name: 'Timber Wolf',
    manufacturer: 'Aristocrat',
    gameSeries: 'Timber Wolf',
    volatility: 'High',
    cabinetType: 'Video',
    releaseYear: 2020,
    theme: 'Wolf/Nature',
  },
  {
    id: 'ultimate-fire-link-china-street',
    name: 'Ultimate Fire Link – China Street',
    manufacturer: 'Bally',
    gameSeries: 'Ultimate Fire Link',
    volatility: 'Medium-High',
    cabinetType: 'Multi-Screen',
    releaseYear: 2022,
    theme: 'Asian',
  },
  {
    id: 'ultimate-fire-link-olvera-street',
    name: 'Ultimate Fire Link – Olvera Street',
    manufacturer: 'Bally',
    gameSeries: 'Ultimate Fire Link',
    volatility: 'Medium-High',
    cabinetType: 'Multi-Screen',
    releaseYear: 2022,
    theme: 'Mexican',
  },
  {
    id: 'ultimate-fire-link-tahiti-inferno',
    name: 'Ultimate Fire Link – Tahiti Inferno',
    manufacturer: 'Bally',
    gameSeries: 'Ultimate Fire Link',
    volatility: 'Medium-High',
    cabinetType: 'Multi-Screen',
    releaseYear: 2022,
    theme: 'Island',
  },
  {
    id: 'ultimate-fire-link-tiger-empress',
    name: 'Ultimate Fire Link – Tiger Empress',
    manufacturer: 'Bally',
    gameSeries: 'Ultimate Fire Link',
    volatility: 'Medium-High',
    cabinetType: 'Multi-Screen',
    releaseYear: 2023,
    theme: 'Asian/Tiger',
  },
  {
    id: 'wheel-of-fortune-quantum',
    name: 'Wheel of Fortune',
    manufacturer: 'IGT',
    gameSeries: 'Wheel of Fortune',
    volatility: 'Medium',
    cabinetType: 'Multi-Screen',
    releaseYear: 2022,
    theme: 'Wheel of Fortune',
  },
  {
    id: 'wonder-4-tower',
    name: 'Wonder 4 Tower',
    manufacturer: 'Aristocrat',
    gameSeries: 'Wonder 4',
    volatility: 'Medium',
    cabinetType: 'Multi-Screen',
    releaseYear: 2020,
    theme: 'Multi-Theme',
  },
  {
    id: 'mighty-monkey',
    name: 'Mighty Monkey',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Monkey',
  },
  {
    id: 'perfect-peacock',
    name: 'Perfect Peacock',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Peacock',
  },
  {
    id: 'gold-rush',
    name: 'Gold Rush',
    manufacturer: 'Other',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Gold/Mining',
  },
  {
    id: 'dancing-drums-prosperity',
    name: 'Dancing Drums Prosperity',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Dancing Drums',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    theme: 'Asian/Drums',
  },
  {
    id: 'dancing-drums-explosion',
    name: 'Dancing Drums Explosion',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Dancing Drums',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2022,
    theme: 'Asian/Drums',
  },
  {
    id: 'ocean-magic-ultra',
    name: 'Ocean Magic Ultra',
    manufacturer: 'IGT',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2022,
    theme: 'Ocean',
  },
  {
    id: 'treasure-box',
    name: 'Treasure Box',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Treasure',
  },
  {
    id: 'jackpot-carnival',
    name: 'Jackpot Carnival',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Carnival',
  },
  {
    id: 'mighty-miner',
    name: 'Mighty Miner',
    manufacturer: 'Other',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Mining',
  },
  {
    id: 'mighty-tiger',
    name: 'Mighty Tiger',
    manufacturer: 'Other',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Tiger',
  },
  {
    id: 'wheel-of-fortune-gold',
    name: 'Wheel of Fortune Gold',
    manufacturer: 'IGT',
    gameSeries: 'Wheel of Fortune',
    volatility: 'Medium',
    cabinetType: 'Multi-Screen',
    releaseYear: 2024,
    theme: 'Wheel of Fortune',
  },
  {
    id: 'san-fa-panda',
    name: 'San Fa Panda',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Asian/Panda',
  },
  {
    id: 'san-fa-tiger',
    name: 'San Fa Tiger',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Asian/Tiger',
  },
  {
    id: 'san-fa-dragon',
    name: 'San Fa Dragon',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Asian/Dragon',
  },
  {
    id: 'rakin-bacon',
    name: "Rakin' Bacon",
    manufacturer: 'IGT',
    gameSeries: 'Rakin Bacon',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Pigs/Bacon',
  },
  {
    id: 'rakin-bacon-deluxe',
    name: "Rakin' Bacon Deluxe",
    manufacturer: 'IGT',
    gameSeries: 'Rakin Bacon',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2022,
    theme: 'Pigs/Bacon',
  },
  {
    id: 'rakin-bacon-explosion',
    name: "Rakin' Bacon Explosion",
    manufacturer: 'IGT',
    gameSeries: 'Rakin Bacon',
    volatility: 'High',
    cabinetType: 'Video',
    releaseYear: 2023,
    theme: 'Pigs/Bacon',
  },
  {
    id: 'golden-wins-deluxe',
    name: 'Golden Wins Deluxe',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Classic',
  },
  {
    id: 'jade-dragon-rising',
    name: 'Jade Dragon Rising',
    manufacturer: 'Other',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2022,
    theme: 'Asian/Dragon',
  },
  {
    id: 'wild-wild-samurai-ags',
    name: 'Wild Wild Samurai',
    manufacturer: 'AGS',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2022,
    theme: 'Samurai',
  },
  {
    id: 'cleopatra-ii',
    name: 'Cleopatra II',
    manufacturer: 'IGT',
    gameSeries: 'Cleopatra',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Egyptian',
  },
  {
    id: 'golden-egypt-grand',
    name: 'Golden Egypt Grand',
    manufacturer: 'IGT',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2022,
    theme: 'Egyptian',
  },
  {
    id: 'scarab',
    name: 'Scarab',
    manufacturer: 'IGT',
    gameSeries: 'Scarab',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Egyptian',
  },
  {
    id: 'fortune-coin-boost',
    name: 'Fortune Coin Boost',
    manufacturer: 'IGT',
    gameSeries: 'Fortune Coin',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2023,
    theme: 'Asian/Coin',
  },
  {
    id: 'pharaohs-fortune-2024',
    name: "Pharaoh's Fortune 2024 Edition",
    manufacturer: 'IGT',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2024,
    theme: 'Egyptian',
  },
  {
    id: 'wolf-ridge',
    name: 'Wolf Ridge',
    manufacturer: 'Other',
    volatility: 'Medium-High',
    cabinetType: 'Video',
    releaseYear: 2021,
    theme: 'Wolf/Nature',
  },
  {
    id: 'treasures-of-troy',
    name: 'Treasures of Troy',
    manufacturer: 'IGT',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2020,
    theme: 'Ancient Greece',
  },
  {
    id: '88-fortunes-diamond',
    name: '88 Fortunes Diamond',
    manufacturer: 'Light & Wonder',
    gameSeries: '88 Fortunes',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2023,
    theme: 'Asian',
  },
  {
    id: '5-treasures-explosion',
    name: '5 Treasures Explosion',
    manufacturer: 'Light & Wonder',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2023,
    theme: 'Asian',
  },
  {
    id: 'money-link-dynasty',
    name: 'Money Link',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Money Link',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2023,
    theme: 'Asian',
  },
  {
    id: 'coin-combo',
    name: 'Coin Combo',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2022,
    theme: 'Coin',
  },
  {
    id: 'cash-falls',
    name: 'Cash Falls',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2022,
    theme: 'Waterfall/Money',
  },
  {
    id: 'fu-dai-lian-lian-panda',
    name: 'Fu Dai Lian Lian',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Fu Dai Lian Lian',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2021,
    theme: 'Asian/Panda',
  },
  {
    id: 'prosperity-link',
    name: 'Prosperity Link',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2022,
    theme: 'Asian',
  },
  {
    id: 'jinse-dao',
    name: 'Jinse Dao',
    manufacturer: 'Other',
    volatility: 'Medium',
    cabinetType: 'Video',
    releaseYear: 2022,
    theme: 'Asian',
  },
];

export const QUANTUM_SHIP_NAME = 'Quantum of the Seas';
