import React, { useMemo, useState } from 'react';
import { FlatList, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Stack, useRouter } from 'expo-router';
import { ArrowLeft, Check, GitCompareArrows, Search, X } from 'lucide-react-native';
import { useCoreData } from '@/state/CoreDataProvider';
import { useCertificates } from '@/state/CertificatesProvider';
import { compareCandidates, type CompareCandidate } from '@/lib/operating/operatingSystem';
import { EASY_SEAS_TOKENS as T } from '@/constants/easySeasDesignSystem';
import { useExperience } from '@/state/ExperienceProvider';

type SelectableCandidate = CompareCandidate & { kind: 'Cruise' | 'Offer' | 'Certificate'; source: string };
const numberOrUndefined = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : undefined;

export default function CompareWorkspace() {
  const router = useRouter(); const core = useCoreData(); const certs = useCertificates(); const { colors, minimumControlSize, textScale } = useExperience(); const [query, setQuery] = useState(''); const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const candidates = useMemo<SelectableCandidate[]>(() => {
    const cruises = [...(core.cruises ?? []), ...(core.bookedCruises ?? [])].map((row: any) => ({ id: `cruise:${row.id}`, kind: 'Cruise' as const, label: `${row.shipName ?? 'Cruise'} · ${row.sailDate ?? 'date missing'}`, dates: row.sailDate && row.returnDate ? `${row.sailDate}/${row.returnDate}` : row.sailDate, cabin: row.cabinType ?? row.stateroomCategory, guests: numberOrUndefined(row.guestCount ?? row.guests), taxes: numberOrUndefined(row.taxesAndFees ?? row.taxes), travelCost: numberOrUndefined(row.travelCost), freePlay: numberOrUndefined(row.freePlay), obc: numberOrUndefined(row.obc), retailValue: numberOrUndefined(row.retailValue ?? row.totalRetailValue), itinerary: row.itinerary, source: row.source ?? 'cruise record' }));
    const offers = (core.casinoOffers ?? []).map((row: any) => ({ id: `offer:${row.id ?? row.offerCode}`, kind: 'Offer' as const, label: `${row.offerCode ?? row.name ?? 'Offer'} · ${row.cabinType ?? 'cabin varies'}`, dates: row.expirationDate, cabin: row.cabinType, guests: numberOrUndefined(row.guests ?? row.guestCount), taxes: numberOrUndefined(row.taxes), travelCost: numberOrUndefined(row.travelCost), freePlay: numberOrUndefined(row.freePlay), obc: numberOrUndefined(row.obc), retailValue: numberOrUndefined(row.estimatedValue ?? row.retailValue), itinerary: row.description, source: row.source ?? 'offer record' }));
    const certificates = certs.searchableCertificates.map((row: any) => ({ id: `certificate:${row.id ?? row.certificateCode}`, kind: 'Certificate' as const, label: `${row.certificateCode ?? row.offerCode ?? 'Certificate'} · ${row.awardType ?? 'award'}`, dates: row.expirationDate, cabin: row.cabinType ?? row.awardType, guests: numberOrUndefined(row.guests ?? row.guestCount), freePlay: numberOrUndefined(row.freePlay), obc: numberOrUndefined(row.obc), retailValue: numberOrUndefined(row.tradeInValue ?? row.estimatedValue), itinerary: row.shipName, source: row.parserSource ?? row.source ?? 'certificate record' }));
    return [...cruises, ...offers, ...certificates];
  }, [certs.searchableCertificates, core.bookedCruises, core.casinoOffers, core.cruises]);
  const selected = useMemo(() => selectedIds.map((id) => candidates.find((row) => row.id === id)).filter((row): row is SelectableCandidate => Boolean(row)), [candidates, selectedIds]);
  const comparison = useMemo(() => selected.length >= 2 ? compareCandidates(selected) : null, [selected]);
  const visible = useMemo(() => { const needle = query.trim().toLowerCase(); return needle ? candidates.filter((row) => `${row.kind} ${row.label} ${row.cabin ?? ''} ${row.itinerary ?? ''}`.toLowerCase().includes(needle)) : candidates; }, [candidates, query]);
  const toggle = (id: string) => setSelectedIds((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length < 5 ? [...current, id] : current);
  const header = <><View style={[s.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><Search size={18} color={colors.muted}/><TextInput style={[s.input, { color: colors.text }]} value={query} onChangeText={setQuery} placeholder="Search cruises, offers, or certificates" placeholderTextColor={colors.muted}/></View><Text style={[s.help, { color: colors.muted }]}>Choose 2–5 records. Missing values stay visibly missing; they are never replaced with zero.</Text><View style={s.selected}>{selected.map((row) => <TouchableOpacity key={row.id} style={s.chip} onPress={() => toggle(row.id)}><Text style={s.chipText} numberOfLines={1}>{row.label}</Text><X size={14} color="#273D9A"/></TouchableOpacity>)}</View>{comparison ? <View style={[s.result, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[s.resultTitle, { color: colors.text }]}>Normalized comparison</Text>{comparison.fields.map((field) => <View key={field.field} style={s.field}><Text style={[s.fieldName, { color: colors.muted }]}>{field.field.replaceAll(/([A-Z])/g, ' $1')}</Text>{comparison.rows.map((row, index) => <Text key={row.id} style={[s.fieldValue, { color: colors.text }]}>{row.label}: {field.values[index] == null ? 'Not recorded' : Number(field.values[index]).toLocaleString()}</Text>)}</View>)}{comparison.scheduleConflicts.length ? <Text style={s.warning}>{comparison.scheduleConflicts.length} overlapping-date comparison pair{comparison.scheduleConflicts.length === 1 ? '' : 's'}.</Text> : null}</View> : null}<Text style={[s.section, { color: colors.accent }]}>Available records ({visible.length.toLocaleString()})</Text></>;
  return <SafeAreaView style={[s.safe, { backgroundColor: colors.background }]}><Stack.Screen options={{ headerShown: false }}/><View style={s.header}><TouchableOpacity onPress={() => router.back()} style={{ minWidth: minimumControlSize, minHeight: minimumControlSize, justifyContent: 'center' }} accessibilityLabel="Back"><ArrowLeft color={T.color.deepNavy}/></TouchableOpacity><View style={{ flex: 1 }}><Text style={s.eye}>2–5 RECORD EVIDENCE BASKET</Text><Text style={[s.title, { fontSize: 22 * textScale }]}>Compare Anything</Text></View><GitCompareArrows color="#4EC0A5"/></View><FlatList data={visible} keyExtractor={(row) => row.id} ListHeaderComponent={header} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" initialNumToRender={18} maxToRenderPerBatch={24} windowSize={8} renderItem={({ item }) => { const active = selectedIds.includes(item.id); return <TouchableOpacity style={[s.row, { backgroundColor: colors.surface, borderColor: active ? colors.accent : colors.border, minHeight: minimumControlSize }]} onPress={() => toggle(item.id)} accessibilityRole="checkbox" accessibilityState={{ checked: active }}><View style={[s.check, active && s.checkOn]}>{active ? <Check size={15} color="#fff"/> : null}</View><View style={{ flex: 1 }}><Text style={[s.rowTitle, { color: colors.text }]}>{item.label}</Text><Text style={[s.rowMeta, { color: colors.muted }]}>{item.kind} · {item.cabin ?? 'cabin not recorded'} · {item.guests == null ? 'guest count missing' : `${item.guests} guest${item.guests === 1 ? '' : 's'}`} · {item.source}</Text></View></TouchableOpacity>; }}/></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1 }, header: { backgroundColor: T.color.surface, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: T.color.border }, eye: { color: '#0E7FA7', fontSize: 9, fontWeight: '900', letterSpacing: 1.1 }, title: { color: T.color.deepNavy, fontWeight: '900' }, content: { padding: 16, paddingBottom: 60 }, search: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderRadius: T.radius.md, paddingHorizontal: 12 }, input: { flex: 1, minHeight: 48 }, help: { fontSize: 12, lineHeight: 17, marginVertical: 10 }, selected: { gap: 6 }, chip: { minHeight: 40, borderRadius: 20, paddingHorizontal: 11, backgroundColor: '#EAF2FF', flexDirection: 'row', alignItems: 'center', gap: 6 }, chipText: { flex: 1, color: '#273D9A', fontWeight: '800', fontSize: 11 }, result: { borderWidth: 1, borderRadius: T.radius.lg, padding: 14, marginTop: 12 }, resultTitle: { fontSize: 17, fontWeight: '900' }, field: { marginTop: 10 }, fieldName: { textTransform: 'capitalize', fontSize: 10, fontWeight: '900' }, fieldValue: { fontSize: 11, marginTop: 3 }, warning: { color: T.color.warning, fontWeight: '800', marginTop: 10 }, section: { fontWeight: '900', marginVertical: 12 }, row: { borderWidth: 1, borderRadius: T.radius.md, padding: 12, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 10 }, check: { width: 24, height: 24, borderRadius: 7, borderWidth: 1, borderColor: '#D5D5D0', alignItems: 'center', justifyContent: 'center' }, checkOn: { backgroundColor: '#273D9A', borderColor: '#273D9A' }, rowTitle: { fontWeight: '900', fontSize: 13 }, rowMeta: { fontSize: 10, lineHeight: 15, marginTop: 3 } });
