import React, { useMemo } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Stack, useRouter } from 'expo-router';
import { ArrowLeft, Circle, Link2 } from 'lucide-react-native';
import { useCoreData } from '@/state/CoreDataProvider';
import { buildOfferLineage } from '@/lib/intelligence/offerLineage';
import type { OfferLineageEvent } from '@/types/intelligence';
const C={navy:'#061725',card:'#143955',white:'#fff',muted:'#B7CADB',gold:'#E5B63E',teal:'#3DD1B6',line:'#315875'};
export default function OfferLineageScreen(){const router=useRouter(),{casinoOffers,bookedCruises}=useCoreData();const lineages=useMemo(()=>casinoOffers.filter(o=>o.status!=='skipped').slice(0,100).map(offer=>{const events:OfferLineageEvent[]=[{id:`offer-${offer.id}`,type:'promotion_received',occurredAt:offer.received||offer.createdAt||'',entityId:offer.id,entityType:'offer',ownerProfileId:offer.ownerProfileId,label:offer.offerName||offer.title||offer.offerCode||'Offer',offerCode:offer.offerCode,playerOfferId:offer.playerOfferId,evidenceStatus:offer.dataConfidence==='verified'?'verified':offer.sourceProvider?'imported':'missing'}];bookedCruises.filter(cruise=>(Boolean(offer.playerOfferId)&&cruise.playerOfferId===offer.playerOfferId)||(Boolean(offer.offerInstanceId)&&cruise.offerInstanceId===offer.offerInstanceId)||(Boolean(offer.cruiseId)&&cruise.id===offer.cruiseId)).forEach(cruise=>events.push({id:`booking-${cruise.id}`,type:'booking_created',occurredAt:cruise.createdAt||cruise.sailDate,entityId:cruise.id,entityType:'booking',parentEntityId:offer.id,ownerProfileId:cruise.ownerProfileId,label:`${cruise.shipName} · ${cruise.sailDate}`,offerCode:cruise.offerCode,playerOfferId:cruise.playerOfferId,evidenceStatus:cruise.dataConfidence==='verified'?'verified':'imported'}));return buildOfferLineage(events,offer.id)}),[bookedCruises,casinoOffers]);return <View style={s.root}><Stack.Screen options={{headerShown:false}}/><SafeAreaView style={{flex:1}} edges={['top']}><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><ArrowLeft color={C.gold}/></TouchableOpacity><View><Text style={s.title}>Offer Lineage</Text><Text style={s.sub}>Exact IDs only—never offer code alone</Text></View></View><ScrollView contentContainerStyle={s.content}>{lineages.map(lineage=><View key={lineage.rootEntityId} style={s.card}><Text style={s.cardTitle}>{lineage.events[0]?.label}</Text><Text style={s.meta}>{lineage.confidence.toUpperCase()} · {lineage.events.length} event(s)</Text>{lineage.events.map((event,index)=><View key={event.id} style={s.event}><View style={s.rail}><Circle size={12} color={C.teal} fill={C.teal}/>{index<lineage.events.length-1&&<View style={s.line}/>}</View><View style={{flex:1}}><Text style={s.eventTitle}>{event.type.replaceAll('_',' ')}</Text><Text style={s.copy}>{event.label} · {event.occurredAt||'date missing'}</Text><Text style={s.meta}>{event.playerOfferId?`playerOfferId ${event.playerOfferId}`:'No unique player-offer ID'}</Text></View></View>)}{lineage.unresolvedLinks.map(value=><Text key={value} style={s.warning}>{value}</Text>)}</View>)}</ScrollView></SafeAreaView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:C.navy},header:{flexDirection:'row',alignItems:'center',gap:12,padding:16,borderBottomWidth:1,borderBottomColor:C.line},title:{color:C.white,fontSize:22,fontWeight:'900'},sub:{color:C.muted,fontSize:11},content:{padding:16,paddingBottom:70},card:{backgroundColor:C.card,borderRadius:14,borderWidth:1,borderColor:C.line,padding:14,marginBottom:10},cardTitle:{color:C.white,fontSize:16,fontWeight:'900'},meta:{color:C.muted,fontSize:9,marginTop:3},event:{flexDirection:'row',gap:9,marginTop:12},rail:{alignItems:'center',width:16},line:{width:2,flex:1,minHeight:30,backgroundColor:C.line},eventTitle:{color:C.gold,fontWeight:'900',fontSize:11,textTransform:'uppercase'},copy:{color:C.white,fontSize:11,marginTop:2},warning:{color:'#FFD19C',fontSize:10,marginTop:8}});
