import React,{useMemo}from'react';import{ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';import{SafeAreaView}from'react-native-safe-area-context';import{Stack,useLocalSearchParams,useRouter}from'expo-router';import{ArrowLeft,Bot,ChevronRight,FileClock,Map,Plane,Ship,Users}from'lucide-react-native';
const sections={
31:{title:'Fare & Upgrade History',body:'Immutable booking, fare, promotion, certificate, upgrade, payment, refund, and invoice-evidence events reconstruct final cruise cost.',route:'/price-upgrade-monitor'},
32:{title:'Cabin Intelligence',body:'Evidence-aware cabin scoring covers obstruction, noise, connecting doors, elevator distance, view, favorites, and avoid lists.',route:'/voyage-command-center'},
33:{title:'Back-to-Back Operations',body:'Transfer time, terminals, hotel nights, luggage, laundry, cabin continuity, travel cost, and impossible combinations.',route:'/back-to-back-trip-builder'},
34:{title:'Travel-Cost Ranking',body:'Net personal value includes airfare, hotel, parking, transfers, meals, taxes, and ancillary cost—with estimates only when enabled.',route:'/certificate-portfolio'},
35:{title:'Port-Day Planner',body:'Ship/local time, transportation, weather risk, tendering, mobility, cancellation rules, and a safe return-to-ship target.',route:'/voyage-command-center'},
36:{title:'Dynamic Voyage Map',body:'Itinerary points, legally sourced position, estimated-route uncertainty, marine zones, buoys, weather, and alerts.',route:'/day-agenda'},
37:{title:'Disruption Workspace',body:'Compare original and updated itineraries, then recheck only affected weather, excursions, transfers, casino hours, and reservations.',route:'/voyage-command-center'},
38:{title:'Travel Document Rules',body:'Traveler-specific passport, visa, consent, medication, age, and residency checks retain official links and verification dates.',route:'/travel-readiness-vault'},
39:{title:'Cruise Memory & Review',body:'Owner-scoped notes, media, meals, entertainment, cabin, casino, and crew recognition improve future rankings.',route:'/casino/post-cruise-closeout'},
40:{title:'Group-Travel Coordination',body:'Travel parties link reservations without merging user accounts; shared and private schedules remain separate.',route:'/passenger-calendar'},
}as const;
export default function TravelIntelligence(){const router=useRouter(),params=useLocalSearchParams<{item?:string}>(),selected=Number(params.item??31)as keyof typeof sections,item=sections[selected]??sections[31],Icon=selected===36?Map:selected===40?Users:selected===34?Plane:selected===31?FileClock:Ship;const ids=useMemo(()=>Object.keys(sections).map(Number),[]);return <SafeAreaView style={s.safe}><Stack.Screen options={{headerShown:false}}/><View style={s.head}><TouchableOpacity onPress={()=>router.back()}><ArrowLeft color="#1C2F7A"/></TouchableOpacity><View style={s.headCopy}><Text style={s.eyebrow}>TRAVEL INTELLIGENCE</Text><Text style={s.title}>{item.title}</Text></View><TouchableOpacity onPress={()=>router.push({pathname:'/ask-my-data',params:{prompt:`Explain ${item.title} using my saved Easy Seas data and cite the contributing records.`}}as never)}><Bot color="#0E7FA7"/></TouchableOpacity></View><ScrollView contentContainerStyle={s.content}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{ids.map(id=><TouchableOpacity key={id} onPress={()=>router.setParams({item:String(id)})} style={[s.chip,id===selected&&s.chipOn]}><Text style={[s.chipText,id===selected&&s.chipTextOn]}>{id}</Text></TouchableOpacity>)}</ScrollView><View style={s.hero}><Icon size={34} color="#e6b63d"/><Text style={s.heroTitle}>{item.title}</Text><Text style={s.body}>{item.body}</Text><View style={s.evidence}><Text style={s.evidenceTitle}>TRUST RULE</Text><Text style={s.evidenceText}>Recorded facts, imported values, user entries, estimates, and missing inputs remain visibly distinct. Personal records stay owner-scoped.</Text></View><TouchableOpacity style={s.open} onPress={()=>router.push(item.route as never)} testID={`travel-intelligence-open-${selected}`}><Text style={s.openText}>Open working tool</Text><ChevronRight color="#071b2d"/></TouchableOpacity></View><Text style={s.helper}>This center is an index; the working tool remains in its existing tab-owned workflow, so no tab was moved or removed.</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#eef4f7'},head:{backgroundColor:'#FFFFFF',padding:16,flexDirection:'row',alignItems:'center'},headCopy:{flex:1,marginLeft:14},eyebrow:{color:'#0E7FA7',fontSize:9,fontWeight:'900',letterSpacing:1.2},title:{color:'#1C2F7A',fontSize:20,fontWeight:'900'},content:{padding:16},chips:{gap:7,paddingBottom:12},chip:{backgroundColor:'#fff',borderColor:'#d3e0e7',borderWidth:1,borderRadius:18,paddingHorizontal:13,paddingVertical:8},chipOn:{backgroundColor:'#273d9a'},chipText:{color:'#35526a',fontWeight:'900'},chipTextOn:{color:'#fff'},hero:{backgroundColor:'#fff',borderColor:'#d4e1e8',borderWidth:1,borderRadius:18,padding:19},heroTitle:{color:'#173b5d',fontSize:24,fontWeight:'900',marginTop:12},body:{color:'#546e81',fontSize:15,lineHeight:22,marginTop:8},evidence:{backgroundColor:'#eef5fb',borderRadius:13,padding:13,marginTop:16},evidenceTitle:{color:'#273d9a',fontWeight:'900',fontSize:10},evidenceText:{color:'#4d677a',lineHeight:18,marginTop:4},open:{backgroundColor:'#e6b63d',borderRadius:13,padding:14,marginTop:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},openText:{color:'#071b2d',fontWeight:'900'},helper:{color:'#60798b',fontSize:12,lineHeight:18,marginTop:12}});
