import React, { useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Stack, useRouter } from 'expo-router';
import { AlertTriangle, ArrowLeft, Check, Circle, Clock, FileCheck2, MapPin, Ship } from 'lucide-react-native';
import { useAuth } from '@/state/AuthProvider';
import { useCoreData } from '@/state/CoreDataProvider';
import { evaluateCabinQuality } from '@/lib/voyage/cabinQuality';
import { buildPortDayCommand } from '@/lib/voyage/portDayCommand';
import { buildTravelChecklist } from '@/lib/voyage/travelChecklist';
import { findVoyageScheduleConflicts, type VoyageAgendaItem } from '@/lib/voyage/scheduleConflicts';
import { ALL_STORAGE_KEYS, getUserScopedKey } from '@/lib/storage/storageKeys';
import { quotaSafeGetJsonItem, quotaSafeSetJsonItem } from '@/lib/storage/quotaSafeStorage';

const C = { navy: '#061725', panel: '#0D2A42', card: '#163C5A', white: '#FFFFFF', muted: '#B6C9DB', gold: '#E5B63E', teal: '#3DD1B6', red: '#FF766E', line: '#315875' };
export default function VoyageCommandCenterScreen() {
  const router = useRouter(), { authenticatedEmail } = useAuth(), { bookedCruises, calendarEvents } = useCoreData();
  const today = new Date().toISOString().slice(0, 10), cruise = bookedCruises.filter((row) => row.returnDate >= today && row.status !== 'cancelled').sort((a, b) => a.sailDate.localeCompare(b.sailDate))[0];
  const [selectedDay, setSelectedDay] = useState(0), [completed, setCompleted] = useState<string[]>([]);
  const storageKey = getUserScopedKey(ALL_STORAGE_KEYS.TRAVEL_CHECKLISTS, authenticatedEmail);
  useEffect(() => { void quotaSafeGetJsonItem<Record<string, string[]>>(storageKey, {}, (value): value is Record<string, string[]> => Boolean(value && typeof value === 'object' && !Array.isArray(value))).then((saved) => setCompleted(saved[cruise?.id ?? 'unassigned'] ?? [])); }, [cruise?.id, storageKey]);
  const itinerary = cruise?.itinerary ?? [], day = itinerary[selectedDay];
  const portCommand = day ? buildPortDayCommand({ port: day.port, arrival: day.arrival, departure: day.departure, allAboard: day.notes?.match(/all aboard\s*[:\-]?\s*(\d{1,2}:\d{2})/i)?.[1], tender: /tender/i.test(day.notes ?? ''), safetyBufferMinutes: 60 }) : null;
  const cabin = evaluateCabinQuality({ cabinNumber: cruise?.cabinNumber || cruise?.stateroomNumber, deck: cruise?.deckNumber ? Number(cruise.deckNumber) : null, distanceToElevator: 'unknown', casinoDeckDistance: null, noiseRisk: 'unknown', obstruction: /obstruct/i.test(cruise?.cabinCategory ?? '') ? 'partial' : 'unknown', motionPosition: 'unknown', smokingExposure: 'unknown' });
  const checklist = buildTravelChecklist({ international: itinerary.some((row) => row.port && !/cococay|miami|fort lauderdale|port canaveral|los angeles|seattle|galveston/i.test(row.port)), destinations: Array.from(new Set(itinerary.filter((row) => !row.isSeaDay).map((row) => row.port))), departureDate: cruise?.sailDate ?? today, hasFlights: Boolean(cruise?.airfare), hasHotel: calendarEvents.some((event) => event.type === 'hotel' && event.startDate <= (cruise?.sailDate ?? '')), hasTransfers: calendarEvents.some((event) => event.type === 'travel' && event.startDate <= (cruise?.sailDate ?? '')), requiresTender: itinerary.some((row) => /tender/i.test(row.notes ?? '')) });
  const agendaItems = useMemo(() => calendarEvents.filter((event) => !cruise || (event.startDate >= cruise.sailDate && event.startDate <= cruise.returnDate)).map((event): VoyageAgendaItem => ({ id: event.id, title: event.title, start: event.start || `${event.startDate}T09:00:00`, end: event.end || `${event.endDate || event.startDate}T10:00:00`, location: event.location, kind: /dining/i.test(event.title) ? 'dining' : /show/i.test(event.title) ? 'show' : /excursion/i.test(event.title) ? 'excursion' : /casino/i.test(event.title) ? 'casino' : 'other', walkingMinutesAfter: 15 })), [calendarEvents, cruise]);
  const conflicts = useMemo(() => findVoyageScheduleConflicts(agendaItems), [agendaItems]);
  const toggle = async (id: string) => { const next = completed.includes(id) ? completed.filter((value) => value !== id) : [...completed, id]; setCompleted(next); const saved = await quotaSafeGetJsonItem<Record<string, string[]>>(storageKey, {}, (value): value is Record<string, string[]> => Boolean(value && typeof value === 'object' && !Array.isArray(value))); await quotaSafeSetJsonItem(storageKey, { ...saved, [cruise?.id ?? 'unassigned']: next }); };
  if (!cruise) return <View style={s.root}><Stack.Screen options={{ headerShown: false }} /><SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity onPress={() => router.back()}><ArrowLeft size={24} color={C.gold} /></TouchableOpacity><Text style={s.title}>Voyage Command Center</Text></View><View style={s.empty}><Ship size={34} color={C.muted} /><Text style={s.copy}>No upcoming booked cruise is saved.</Text></View></SafeAreaView></View>;
  return <View style={s.root}><Stack.Screen options={{ headerShown: false }} /><SafeAreaView style={s.safe} edges={['top']}><View style={s.header}><TouchableOpacity style={s.back} onPress={() => router.back()}><ArrowLeft size={22} color={C.gold} /></TouchableOpacity><View><Text style={s.title}>Voyage Command Center</Text><Text style={s.sub}>{cruise.shipName} · {cruise.sailDate}</Text></View></View><ScrollView contentContainerStyle={s.content}>
    <Text style={s.section}>PORT DAYS</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{itinerary.map((row, index) => <TouchableOpacity key={`${row.day}-${row.port}`} style={[s.chip, selectedDay === index && s.chipActive]} onPress={() => setSelectedDay(index)}><Text style={[s.chipText, selectedDay === index && s.chipTextActive]}>{row.date?.slice(5) || `Day ${row.day}`} · {row.isSeaDay ? 'Sea day' : row.port}</Text></TouchableOpacity>)}</ScrollView>
    {portCommand && <View style={s.panel}><View style={s.row}><MapPin size={21} color={C.teal} /><Text style={s.panelTitle}>{portCommand.port}</Text></View>{portCommand.facts.map((fact) => <Text key={fact} style={s.copy}>{fact}</Text>)}<View style={s.returnBox}><Clock size={20} color={C.gold} /><View><Text style={s.small}>PERSONAL RETURN-TO-SHIP TARGET</Text><Text style={s.returnText}>{portCommand.returnBy || 'Needs all-aboard time'} · {portCommand.safetyBufferMinutes} min buffer</Text></View></View>{portCommand.tenderWarning && <Text style={s.warning}>{portCommand.tenderWarning}</Text>}{portCommand.timeZoneWarning && <Text style={s.warning}>{portCommand.timeZoneWarning}</Text>}</View>}
    <Text style={s.section}>SCHEDULE CONFLICTS</Text><View style={s.panel}>{conflicts.length ? conflicts.map((conflict) => <View key={`${conflict.leftId}-${conflict.rightId}`} style={s.row}><AlertTriangle size={18} color={C.red} /><Text style={s.warning}>{conflict.explanation}</Text></View>) : <View style={s.row}><Check size={18} color={C.teal} /><Text style={s.copy}>No overlaps found among {agendaItems.length} saved voyage calendar item(s).</Text></View>}</View>
    <Text style={s.section}>CABIN QUALITY</Text><View style={s.panel}><View style={s.row}><Ship size={20} color={C.gold} /><Text style={s.panelTitle}>{cruise.cabinNumber || cruise.stateroomNumber || cruise.cabinCategory || 'Cabin not assigned'} · {cabin.score}/100</Text></View><Text style={s.copy}>{cabin.confidence.toUpperCase()} confidence · This score never invents missing deck-plan facts.</Text>{cabin.strengths.map((value) => <Text key={value} style={s.positive}>✓ {value}</Text>)}{cabin.cautions.map((value) => <Text key={value} style={s.warning}>! {value}</Text>)}<Text style={s.missing}>Needed for a better score: {cabin.missingData.join(', ') || 'none'}</Text></View>
    <Text style={s.section}>TRAVEL DOCUMENTS & EMBARKATION</Text>{checklist.map((item) => <TouchableOpacity key={item.id} style={s.checkItem} onPress={() => void toggle(item.id)}><View style={s.checkIcon}>{completed.includes(item.id) ? <Check size={16} color={C.navy} /> : <Circle size={16} color={C.muted} />}</View><View style={s.flex}><Text style={[s.checkTitle, completed.includes(item.id) && s.done]}>{item.label}</Text><Text style={s.small}>{item.dueDate ? `Due ${item.dueDate} · ` : ''}{item.reason}</Text></View></TouchableOpacity>)}
    <TouchableOpacity style={s.ask} onPress={() => router.push({ pathname: '/ask-my-data', params: { prompt: `Review my voyage readiness and conflicts for ${cruise.shipName} sailing ${cruise.sailDate}.` } } as never)}><FileCheck2 size={18} color={C.navy} /><Text style={s.askText}>ASK AGENTX TO EXPLAIN THIS VOYAGE</Text></TouchableOpacity><Text style={s.notice}>Port timing, visa, prohibited-item, and entry requirements must be verified against official current sources before travel.</Text>
  </ScrollView></SafeAreaView></View>;
}
const s = StyleSheet.create({ root: { flex: 1, backgroundColor: C.navy }, safe: { flex: 1 }, flex: { flex: 1 }, header: { flexDirection: 'row', gap: 12, alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: C.line }, back: { width: 43, height: 43, borderRadius: 22, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' }, title: { color: C.white, fontSize: 22, fontWeight: '900' }, sub: { color: C.muted, fontSize: 11, marginTop: 2 }, content: { padding: 16, paddingBottom: 70 }, section: { color: C.gold, fontSize: 12, fontWeight: '900', letterSpacing: 1, marginTop: 20, marginBottom: 9 }, chips: { gap: 7 }, chip: { backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: 18, paddingHorizontal: 12, paddingVertical: 9 }, chipActive: { backgroundColor: C.gold, borderColor: C.gold }, chipText: { color: C.muted, fontWeight: '800', fontSize: 11 }, chipTextActive: { color: C.navy }, panel: { backgroundColor: C.panel, borderRadius: 15, borderWidth: 1, borderColor: C.line, padding: 14, gap: 7 }, panelTitle: { color: C.white, fontSize: 16, fontWeight: '900', flex: 1 }, row: { flexDirection: 'row', alignItems: 'center', gap: 9 }, copy: { color: C.muted, fontSize: 12, lineHeight: 18, flex: 1 }, returnBox: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.card, borderRadius: 11, padding: 12, marginTop: 5 }, small: { color: C.muted, fontSize: 9, lineHeight: 14 }, returnText: { color: C.white, fontWeight: '900', fontSize: 14, marginTop: 3 }, warning: { color: '#FFD19C', fontSize: 11, lineHeight: 17, flex: 1 }, positive: { color: C.teal, fontSize: 11, marginTop: 4 }, missing: { color: C.muted, fontSize: 10, marginTop: 6 }, checkItem: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.card, borderRadius: 12, padding: 12, borderWidth: 1, borderColor: C.line, marginBottom: 7 }, checkIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: C.gold, alignItems: 'center', justifyContent: 'center' }, checkTitle: { color: C.white, fontSize: 12, fontWeight: '800' }, done: { textDecorationLine: 'line-through', color: C.muted }, ask: { flexDirection: 'row', gap: 8, justifyContent: 'center', alignItems: 'center', backgroundColor: C.gold, padding: 14, borderRadius: 12, marginTop: 17 }, askText: { color: C.navy, fontSize: 11, fontWeight: '900' }, notice: { color: C.muted, fontSize: 10, lineHeight: 16, marginTop: 15 }, empty: { padding: 40, alignItems: 'center', gap: 12 } });
