import { buildBackToBackOperationalPlan, type OperationalB2BLeg } from '@/lib/backToBackOperationalPlan';
import { evaluateCabinQuality, type CabinQualityInput } from '@/lib/voyage/cabinQuality';
import { buildPortDayCommand, type PortDayInput } from '@/lib/voyage/portDayCommand';

export type EvidenceState='verified'|'imported'|'user'|'estimated'|'missing';
export interface ImmutableFareEvent{id:string;bookingId:string;kind:'booking'|'fare_change'|'promotion'|'certificate'|'upgrade'|'payment'|'refund';occurredAt:string;amount:number;currency:string;description:string;evidenceUri?:string;source:EvidenceState}
export function appendFareEvent(events:ImmutableFareEvent[],event:ImmutableFareEvent){if(events.some(row=>row.id===event.id))throw new Error('IMMUTABLE_EVENT_ALREADY_EXISTS');return[...events,event].sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt))}
export function summarizeFareHistory(events:ImmutableFareEvent[]){const signed=(event:ImmutableFareEvent)=>event.kind==='payment'||event.kind==='refund'?0:event.kind==='promotion'||event.kind==='certificate'?-Math.abs(event.amount):Math.abs(event.amount);const total=events.reduce((sum,event)=>sum+signed(event),0),paid=events.filter(e=>e.kind==='payment').reduce((s,e)=>s+Math.abs(e.amount),0),refunds=events.filter(e=>e.kind==='refund').reduce((s,e)=>s+Math.abs(e.amount),0);return{totalCost:total,totalPaid:paid,totalRefunded:refunds,remainingBalance:Math.max(0,total-paid+refunds),events:[...events].sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt))}}

export interface CanonicalCabinRecord{ship:string;cabin:string;deck?:number;connecting?:boolean;view?:string;userNotes?:string;evidenceUri?:string;favorite?:boolean;avoid?:boolean;quality:CabinQualityInput}
export function scoreCanonicalCabin(record:CanonicalCabinRecord){const result=evaluateCabinQuality(record.quality);return{...result,score:record.avoid?0:Math.min(100,result.score+(record.favorite?8:0)),evidenceState:record.evidenceUri?'verified':record.userNotes?'user':'missing' as EvidenceState}}

export interface ExpandedB2BInput{legs:OperationalB2BLeg[];transferCost?:number;hotelNightCost?:number;laundryCost?:number;cabinNumbers?:string[]}
export function buildExpandedB2BPlan(input:ExpandedB2BInput){const base=buildBackToBackOperationalPlan(input.legs),hotelCost=base.hotelNights*Math.max(0,input.hotelNightCost??0),operationalCost=hotelCost+Math.max(0,input.transferCost??0)+Math.max(0,input.laundryCost??0),cabins=input.cabinNumbers??[],cabinContinuity=cabins.length>0&&new Set(cabins.map(v=>v.trim().toLowerCase())).size===1;return{...base,operationalCost,cabinContinuity,impossible:base.transitions.some(t=>t.gapDays===0&&!t.samePort),timelineLegs:base.legs.map((leg,index)=>({...leg,sequence:index+1}))}}

export interface TravelCostCandidate{id:string;label:string;cruiseValue:number;taxes?:number;airfare?:number;hotel?:number;parking?:number;transfers?:number;meals?:number;ancillary?:number;estimateEnabled?:boolean}
export function rankByNetPersonalValue(candidates:TravelCostCandidate[]){return candidates.map(candidate=>{const known=['taxes','airfare','hotel','parking','transfers','meals','ancillary'].reduce((sum,key)=>sum+Math.max(0,Number((candidate as any)[key]??0)),0);const missing=['taxes','airfare','hotel','parking','transfers','meals','ancillary'].filter(key=>(candidate as any)[key]==null);return{...candidate,totalTripCost:known,netPersonalValue:candidate.cruiseValue-known,missing,confidence:missing.length===0?'high':candidate.estimateEnabled?'estimated':'incomplete'}}).sort((a,b)=>b.netPersonalValue-a.netPersonalValue)}

export interface PortActivity{id:string;name:string;start?:string;end?:string;cost?:number;mobility?:string;cancellation?:string;weatherRisk?:string}
export function buildSafePortPlan(input:PortDayInput,activities:PortActivity[]){const command=buildPortDayCommand(input);return{command,activities,alerts:activities.flatMap(a=>a.weatherRisk?[`${a.name}: ${a.weatherRisk}`]:[]),offlinePayload:{input,activities,savedAt:new Date().toISOString()}}}

export interface VoyagePoint{day:number;date:string;label:string;latitude?:number;longitude?:number;source:'itinerary'|'provider'|'estimated';uncertaintyNm:number;marineZone?:string;buoyId?:string;alertCount?:number}
export function buildVoyageMap(points:VoyagePoint[]){return{points:points.map(point=>({...point,uncertaintyNm:point.source==='estimated'?Math.max(25,point.uncertaintyNm):Math.max(0,point.uncertaintyNm)})),offline:points.map(({day,date,label,latitude,longitude,source,uncertaintyNm})=>({day,date,label,latitude,longitude,source,uncertaintyNm}))}}

export interface DisruptionInput{original:VoyagePoint[];updated:VoyagePoint[]}
export function analyzeDisruption(input:DisruptionInput){const old=new Map(input.original.map(p=>[p.date,p])),next=new Map(input.updated.map(p=>[p.date,p]));const changed=[...new Set([...old.keys(),...next.keys()])].filter(date=>old.get(date)?.label!==next.get(date)?.label).map(date=>({date,before:old.get(date)?.label??'not scheduled',after:next.get(date)?.label??'removed'}));const checklist=changed.flatMap(row=>[`Recheck weather and marine alerts for ${row.date}`,`Review excursions, transfers, reservations, and casino hours for ${row.date}`]);return{changed,checklist,summary:changed.length?`${changed.length} voyage day${changed.length===1?'':'s'} changed.`:'No itinerary changes detected.'}}

export interface TravelDocumentRule{id:string;destination:string;travelerScope:string;requirement:string;deadline?:string;officialUrl:string;verifiedAt:string;complete:boolean}
export function assessTravelDocuments(rules:TravelDocumentRule[],now=Date.now()){return rules.map(rule=>{const ageDays=Math.floor((now-new Date(rule.verifiedAt).getTime())/86400000),stale=!Number.isFinite(ageDays)||ageDays>30;return{...rule,ageDays,stale,status:!rule.complete?'missing':stale?'verify_again':'ready',message:stale?'Rule is not current; confirm with the linked official source.':rule.requirement}})}

export interface CruiseJournal{id:string;ownerId:string;cruiseId:string;notes?:string;favorites?:string[];disappointments?:string[];meals?:string[];entertainment?:string[];cabinNotes?:string;casinoNotes?:string;crewRecognitionIds?:string[];mediaUris?:string[];private:boolean}
export function buildPostCruiseReview(journal:CruiseJournal){return{cruiseId:journal.cruiseId,ownerId:journal.ownerId,highlights:[...(journal.favorites??[]),...(journal.meals??[]),...(journal.entertainment??[])],improvements:journal.disappointments??[],futurePreferenceSignals:{cabin:journal.cabinNotes,casino:journal.casinoNotes},mediaCount:journal.mediaUris?.length??0,ownerScoped:true}}

export interface TravelPartyMember{id:string;displayName:string;ownerUserId?:string;reservationIds:string[];cabin?:string;dining?:string;activities?:string[];privateFields?:string[]}
export function coordinateTravelParty(members:TravelPartyMember[]){const dining=new Set(members.map(m=>m.dining).filter(Boolean)),activitySets=members.map(m=>new Set(m.activities??[]));const sharedActivities=activitySets.length? [...activitySets[0]].filter(value=>activitySets.every(set=>set.has(value))):[];return{memberCount:members.length,sharedSchedule:{activities:sharedActivities},issues:[...(dining.size>1?['Dining assignments do not match.']:[])],publicMembers:members.map(({privateFields,ownerUserId,...safe})=>safe)}}
