const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),file=path.join(root,'lib/travel/travelIntelligence.ts');
let source=read('lib/travel/travelIntelligence.ts').replace("import { buildBackToBackOperationalPlan, type OperationalB2BLeg } from '@/lib/backToBackOperationalPlan';",`const {buildBackToBackOperationalPlan}=require(${JSON.stringify(path.join(root,'lib/backToBackOperationalPlan.ts'))});`).replace("import { evaluateCabinQuality, type CabinQualityInput } from '@/lib/voyage/cabinQuality';",`const {evaluateCabinQuality}=require(${JSON.stringify(path.join(root,'lib/voyage/cabinQuality.ts'))});`).replace("import { buildPortDayCommand, type PortDayInput } from '@/lib/voyage/portDayCommand';",`const {buildPortDayCommand}=require(${JSON.stringify(path.join(root,'lib/voyage/portDayCommand.ts'))});`);
// Compile dependencies into the test loader.
const oldExt=Module._extensions['.ts'];Module._extensions['.ts']=(mod,filename)=>{const js=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;mod._compile(js,filename)};
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,mod=new Module(file,module);mod.filename=file;mod.paths=Module._nodeModulePaths(path.dirname(file));mod._compile(js,file);const x=mod.exports;
const events=x.appendFareEvent([],{id:'1',bookingId:'b',kind:'booking',occurredAt:'2026-01-01',amount:1000,currency:'USD',description:'fare',source:'imported'});assert.throws(()=>x.appendFareEvent(events,events[0]),/IMMUTABLE/);assert.equal(x.summarizeFareHistory([...events,{id:'2',bookingId:'b',kind:'payment',occurredAt:'2026-01-02',amount:200,currency:'USD',description:'paid',source:'user'}]).remainingBalance,800);
assert.equal(x.scoreCanonicalCabin({ship:'Icon',cabin:'1',favorite:true,quality:{noiseRisk:'low',obstruction:'none'}}).score>70,true);
const b2b=x.buildExpandedB2BPlan({legs:[{shipName:'Icon',sailDate:'2026-01-01',returnDate:'2026-01-08',departurePort:'Miami',nights:7},{shipName:'Icon',sailDate:'2026-01-08',returnDate:'2026-01-15',departurePort:'Miami',nights:7}],cabinNumbers:['1','1']});assert.equal(b2b.cabinContinuity,true);assert.equal(b2b.impossible,false);
assert.equal(x.rankByNetPersonalValue([{id:'a',label:'local',cruiseValue:2000,taxes:100,parking:50},{id:'b',label:'fly',cruiseValue:2500,taxes:100,airfare:900}])[0].id,'a');
assert.equal(x.buildSafePortPlan({port:'Nassau',departure:'17:00'},[]).command.returnBy,'16:00');
assert.equal(x.buildVoyageMap([{day:2,date:'2026-01-02',label:'sea',source:'estimated',uncertaintyNm:2}]).points[0].uncertaintyNm,25);
assert.equal(x.analyzeDisruption({original:[{day:1,date:'2026-01-01',label:'Nassau',source:'itinerary',uncertaintyNm:0}],updated:[{day:1,date:'2026-01-01',label:'CocoCay',source:'itinerary',uncertaintyNm:0}]}).changed.length,1);
assert.equal(x.assessTravelDocuments([{id:'r',destination:'X',travelerScope:'adult',requirement:'passport',officialUrl:'https://example.gov',verifiedAt:'2020-01-01',complete:true}],Date.parse('2026-01-01'))[0].status,'verify_again');
assert.equal(x.buildPostCruiseReview({id:'j',ownerId:'u',cruiseId:'c',favorites:['crew'],private:true}).ownerScoped,true);
assert.deepEqual(x.coordinateTravelParty([{id:'1',displayName:'A',reservationIds:['r'],dining:'6pm',privateFields:['secret']},{id:'2',displayName:'B',reservationIds:['s'],dining:'8pm'}]).issues,['Dining assignments do not match.']);
const center=read('app/operating-center.tsx');for(let i=31;i<=40;i++)assert.match(center,new RegExp(`id: ${i}`));
for(const f of ['lib/travel/travelIntelligence.ts','app/travel-intelligence.tsx']){const out=ts.transpileModule(read(f),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2020},reportDiagnostics:true});assert.equal((out.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error).length,0)}
Module._extensions['.ts']=oldExt;console.log('Build 438 items 31-40 travel intelligence regression passed');
