const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8');
const screen = read('app/(tabs)/machines.tsx');
const card = read('components/AtlasCard.tsx');
const conditions = read('components/MachineConditionLogsPanel.tsx');
const provider = read('state/SlotMachineLibraryProvider.tsx');

assert.match(screen, /numColumns=\{1\}/, 'machine atlas must use a single-column virtualized list');
assert.doesNotMatch(screen, /numColumns=\{2\}/, 'two-column machine grid must not return');
assert.match(screen, /initialNumToRender=\{12\}/);
assert.match(screen, /maxToRenderPerBatch=\{16\}/);
assert.match(screen, /removeClippedSubviews=\{Platform\.OS !== 'web'\}/);
assert.match(screen, /machines\.filter\.open/);
assert.match(screen, /machines\.filter\.sheet/);
assert.match(screen, /Manufacturer/);
assert.match(screen, /Ship/);
assert.match(screen, /selectedManufacturer/);
assert.match(screen, /selectedShip/);
assert.match(screen, /machines\.filter\.apply/);
assert.match(screen, /machines\.filter\.reset/);
assert.match(screen, /machines\.search\.input/);
assert.match(screen, /machines\.filter\.favorites/);
assert.match(screen, /machines\.exportFavorites/);
assert.match(screen, /machines\.exportAll/);
assert.match(screen, /machines-open-verified-atlas/);
assert.match(screen, /MachineSessionStats/);
assert.match(screen, /MachineSessionsList/);
assert.match(screen, /CasinoSessionTracker/);
assert.match(screen, /PlayingHoursCard/);
assert.match(screen, /MachineStrategyCard/);
assert.match(screen, /ShipMachinesExplorer/);
assert.match(screen, /MachineConditionLogsPanel/);
assert.match(card, /onToggleFavorite/);
assert.match(conditions, /notes/);
assert.match(conditions, /timeObserved/);
assert.match(provider, /Loading machines from index \(lightweight mode\)/);

console.log('PASS build440_slots_machine_workflows_regression');
