const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const tokens=read('constants/easySeasDesignSystem.ts');for(const color of ['#55742C','#3D87BF','#D96B38','#2B2930','#E6B63D','#273D9A','#8A1FD1','#2C1D9A','#0E7FA7','#123D73','#0F2247'])assert.match(tokens,new RegExp(color));assert.match(tokens,/high-contrast/);assert.match(tokens,/CHART_PALETTE/);
const prefs=read('lib/experience/experiencePreferences.ts');assert.match(prefs,/isReduceMotionEnabled/);assert.match(prefs,/disclosureKey/);assert.match(prefs,/owner\.trim\(\)\.toLowerCase/);
const flow=read('components/ui/RelationshipFlow.tsx');assert.match(flow,/maxNodes=12/);assert.match(flow,/List view/);assert.match(flow,/unresolved/);
const art=read('components/ui/PremiumVoyageArtwork.tsx');assert.match(art,/onError/);assert.match(art,/LinearGradient/);assert.doesNotMatch(art,/EasySeasHero|logo|signature/);
const motion=read('lib/experience/motion.ts');assert.match(motion,/heavyWork\|\|reducedMotion/);assert.match(motion,/return 0/);
const screen=read('app/experience-settings.tsx');assert.match(screen,/Larger controls/);assert.match(screen,/Simplified (information )?density/);assert.match(screen,/Original Easy Seas logos, signature graphics, tab count, tab order/);
const center=read('app/operating-center.tsx');for(let i=41;i<=46;i++)assert.match(center,new RegExp(`id: ${i}`));
for(const f of ['constants/easySeasDesignSystem.ts','lib/experience/experiencePreferences.ts','lib/experience/motion.ts','components/ui/RelationshipFlow.tsx','components/ui/PremiumVoyageArtwork.tsx','app/experience-settings.tsx']){const out=ts.transpileModule(read(f),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2020},reportDiagnostics:true});assert.equal((out.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error).length,0)}console.log('Build 438 items 41-46 experience regression passed');
