const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');const root=path.resolve(__dirname,'..');
function load(file,deps={}){const filename=path.join(root,file),out=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,old=Module._load;Module._load=(req,p,m)=>req in deps?deps[req]:req.startsWith('@/')?{}:old(req,p,m);try{const mod=new Module(filename,module);mod.filename=filename;mod.paths=Module._nodeModulePaths(path.dirname(filename));mod._compile(out,filename);return mod.exports}finally{Module._load=old}}
const heal=load('lib/dataRepair/selfHealingDataFabric.ts'),scan=heal.scanForSafeRepairs([{id:'c1',shipName:'Harmony  of the Seas',cabinType:'OV',sailDate:'2026-09-10',returnDate:'2026-09-09'}],'booked-cruise','2026-08-23T00:00:00Z');assert.equal(scan.proposals.length,3);assert.equal(scan.automaticCount,1);const audit=heal.applyApprovedRepairs([{id:'c1',shipName:'Harmony  of the Seas'}],scan,[scan.proposals[0].id]);assert.equal(audit.beforeSnapshot[0].shipName,'Harmony  of the Seas');assert.equal(audit.afterSnapshot[0].shipName,'Harmony of the Seas');assert.equal(heal.rollbackRepair(audit)[0].shipName,'Harmony  of the Seas');
const anomalies=load('lib/optimization/alerts/detectCasinoDataAnomalies.ts'),found=anomalies.detectCasinoDataAnomalies([{contextType:'ship',contextKey:'Ship A',sessions:2,points:1000,coinIn:0,cashResult:-500,pointsPerHour:100,lossPerThousandCoinIn:null,confidence:'low',sourceObservationIds:['s1']}]);assert.ok(found.some(x=>x.type==='missing-evidence'));assert.ok(found.some(x=>x.type==='contradictory-value'));
const pricing=fs.readFileSync(path.join(root,'lib/cruisePricingSync.ts'),'utf8');for(const term of ['pricingFromCatalog','PRICING_SYNC_CANCELLED','concurrency','pricingVerified'])assert.ok(pricing.includes(term));
const settings=fs.readFileSync(path.join(root,'app/(tabs)/settings.tsx'),'utf8');for(const term of ['Get all current pricing','settings-get-all-current-pricing','Booked + Completed XLSX','exportBase64File','Export Metadata'])assert.ok(settings.includes(term));
const detail=fs.readFileSync(path.join(root,'app/(tabs)/(overview)/cruise-details.tsx'),'utf8');assert.ok(detail.includes('edit-cruise-pricing'));assert.ok(detail.includes('Edit receipt financials'));assert.doesNotMatch(detail,/style=\{styles\.editAllButton\}[\s\S]{0,100}onPress=\{openFullEditModal\}/);
const ask=fs.readFileSync(path.join(root,'lib/optimization/integration/answerOptimizationQuestion.ts'),'utf8');for(const term of ["'expected-value'","'bankroll'","'what-if'",'sessionScenarios'])assert.ok(ask.includes(term));
console.log('PASS Build 420 remaining workstreams: context anomalies, guarded repairs, provider pricing, XLSX export, scoped edits, and Ask My Data intelligence');
