const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const royal = fs.readFileSync(path.join(root, 'state/RoyalCaribbeanSyncProvider.tsx'), 'utf8');
const core = fs.readFileSync(path.join(root, 'state/CoreDataProvider.tsx'), 'utf8');
const transaction = fs.readFileSync(path.join(root, 'lib/storage/syncTransaction.ts'), 'utf8');

assert.match(royal, /beginSyncTransaction\(syncSource\)/, 'sync must prepare a local transaction');
assert.match(royal, /COMMIT_OFFERS/, 'offers must be a named commit stage');
assert.match(royal, /COMMIT_AVAILABLE_CRUISES/, 'available cruises must be a named commit stage');
assert.match(royal, /COMMIT_BOOKINGS_HISTORY/, 'bookings/history must be a named commit stage');
assert.match(royal, /commitSyncTransaction\(transactionManifest!\)/, 'sync must commit its manifest before success');
assert.match(royal, /abortSyncTransaction\(transactionToAbort, error\)/, 'failed sync must abort its active manifest');
assert.match(royal, /Promise\.race\(\[operationPromise, timeoutPromise\]\)/, 'every checkpoint must terminate visibly instead of freezing the app forever');
assert.match(royal, /activeSyncTransactionRef/, 'Back/unmount cancellation must retain the active transaction handle');
assert.match(royal, /quotaSafeSetJsonItem\(scopedUsersKey, updatedUsers\)/, 'Carnival fallback profile write must use coordinated storage');
assert.match(core, /Calendar generation is derived and must never block authoritative booking persistence/, 'calendar rebuild must be deferred');
assert.ok(core.indexOf('await persistData(skRef.current.BOOKED_CRUISES, normalizedCruises);') < core.indexOf('setBookedCruisesState(normalizedCruises);'), 'bookings state must publish only after durable commit');
assert.match(transaction, /status: 'prepared'/);
assert.match(transaction, /status: 'committed'/);
assert.match(transaction, /status: 'aborted'/);
console.log('PASS build337_stage2_sync_transaction_regression');
