const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const tokens=read('constants/easySeasDesignSystem.ts');
for(const color of ['#55742C','#3D87BF','#D96B38','#58585B','#822A25','#2B2930','#E6B63D','#BFC4CC','#4EC0A5','#3E84D9','#5A43D6','#273D9A','#D87924','#8A1FD1','#2C1D9A','#22201E','#0E7FA7','#123D73','#0F2247'])assert.match(tokens,new RegExp(color));
for(const token of ['space:','radius:','type:','control:','motion:','COLOR_BLIND_SAFE_CHART_PALETTE','highContrast','extra-large'])assert.match(tokens,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
const disclosure=read('components/ui/ProgressiveDisclosure.tsx');assert.match(disclosure,/conclusions\.slice\(0, 3\)/);assert.match(disclosure,/accessibilityState/);assert.match(disclosure,/useExperience/);assert.match(disclosure,/minimumControlSize/);assert.match(read('lib/experience/experiencePreferences.ts'),/disclosureKey/);
const artwork=read('components/ui/PremiumVoyageArtwork.tsx');assert.match(artwork,/cachePolicy="memory-disk"/);for(const kind of ['ship','destination','casino','weather','loyalty'])assert.match(artwork,new RegExp(kind));assert.doesNotMatch(artwork,/EasySeasHero|signature/);
const motion=read('components/ui/PurposefulMotion.tsx');assert.match(motion,/reducedMotion/);assert.match(motion,/accessibility/);
const relationship=read('components/ui/InteractiveRelationshipMap.tsx');assert.match(relationship,/List view/);assert.match(relationship,/exact|inferred/);assert.match(relationship,/useExperience/);assert.match(relationship,/chartPalette/);assert.match(read('app/relationship-explorer.tsx'),/useExperience/);
const settings=read('app/experience-settings.tsx');assert.match(settings,/Extra-large text/);assert.match(settings,/Color-blind-safe charts/);
for(const file of ['constants/easySeasDesignSystem.ts','components/ui/ProgressiveDisclosure.tsx','components/ui/PremiumVoyageArtwork.tsx','components/ui/PurposefulMotion.tsx','components/ui/InteractiveRelationshipMap.tsx','app/experience-settings.tsx']){const out=ts.transpileModule(read(file),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true});assert.equal((out.diagnostics||[]).filter(x=>x.category===ts.DiagnosticCategory.Error).length,0,file)}
console.log('Build 439 unified visual, disclosure, artwork, motion, and accessibility regression passed');
