import type { LocalCertificateLevel, LocalCertificateSailingMatch } from './certificateSailingIndex';

export type SubstitutionBucket = 'shared' | 'lowerOnly' | 'higherOnly' | 'cabinImproved' | 'guestImproved';
export interface SubstitutionRow { key:string; shipName:string; sailDate:string; lower:LocalCertificateLevel|null; higher:LocalCertificateLevel|null; }
export interface CertificateSubstitutionComparison { lowerCode:string; higherCode:string; lowerPoints:number; higherPoints:number; incrementalPoints:number; shared:number; lowerOnly:number; higherOnly:number; cabinImprovements:number; guestImprovements:number; incrementalUsefulInventory:number; nearlyEquivalent:boolean; rows:Record<SubstitutionBucket,SubstitutionRow[]>; }
const key=(ship:string,date:string)=>`${ship.trim().toLowerCase()}__${date.slice(0,10)}`;
const cabinRank=(value:string|null)=>{const v=String(value??'').toLowerCase();return v.includes('suite')?4:v.includes('balcony')?3:v.includes('ocean')?2:v.includes('interior')||v.includes('inside')?1:0};
export function buildCertificateSubstitutionAnalysis(matches:LocalCertificateSailingMatch[]):CertificateSubstitutionComparison[]{
  const byCode=new Map<string,{points:number;rows:Map<string,SubstitutionRow>}>();
  matches.forEach(match=>match.levels.forEach(level=>{if(level.points==null)return;const code=level.certificateCode.trim().toUpperCase(),entry=byCode.get(code)??{points:level.points,rows:new Map()};entry.rows.set(key(match.shipName,match.sailDate),{key:key(match.shipName,match.sailDate),shipName:match.shipName,sailDate:match.sailDate,lower:level,higher:null});byCode.set(code,entry)}));
  const levels=[...byCode.entries()].sort((a,b)=>a[1].points-b[1].points||a[0].localeCompare(b[0]));
  return levels.slice(0,-1).map(([lowerCode,lowerEntry],index)=>{const [higherCode,higherEntry]=levels[index+1],all=new Set([...lowerEntry.rows.keys(),...higherEntry.rows.keys()]);const rows:Record<SubstitutionBucket,SubstitutionRow[]>={shared:[],lowerOnly:[],higherOnly:[],cabinImproved:[],guestImproved:[]};all.forEach(sailingKey=>{const low=lowerEntry.rows.get(sailingKey)?.lower??null,high=higherEntry.rows.get(sailingKey)?.lower??null,base={key:sailingKey,shipName:low?lowerEntry.rows.get(sailingKey)!.shipName:higherEntry.rows.get(sailingKey)!.shipName,sailDate:low?lowerEntry.rows.get(sailingKey)!.sailDate:higherEntry.rows.get(sailingKey)!.sailDate,lower:low,higher:high};if(low&&high){rows.shared.push(base);if(cabinRank(high.cabinLabel)>cabinRank(low.cabinLabel))rows.cabinImproved.push(base);if((high.guestCount??0)>(low.guestCount??0))rows.guestImproved.push(base)}else if(low)rows.lowerOnly.push(base);else rows.higherOnly.push(base)});const incrementalUsefulInventory=rows.higherOnly.length+rows.cabinImproved.length+rows.guestImproved.filter(r=>!rows.cabinImproved.some(c=>c.key===r.key)).length;return{lowerCode,higherCode,lowerPoints:lowerEntry.points,higherPoints:higherEntry.points,incrementalPoints:higherEntry.points-lowerEntry.points,shared:rows.shared.length,lowerOnly:rows.lowerOnly.length,higherOnly:rows.higherOnly.length,cabinImprovements:rows.cabinImproved.length,guestImprovements:rows.guestImproved.length,incrementalUsefulInventory,nearlyEquivalent:incrementalUsefulInventory<=Math.max(3,Math.ceil(lowerEntry.rows.size*.03)),rows}});
}
