const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const batch = read('lib/certificates/certificateBatchDownload.ts');
const lookup = read('app/certificate-lookup.tsx');
const codes = read('app/certificate-codes.tsx');
const offer = read('app/offer-details.tsx');
const app = JSON.parse(read('app.json'));
const pkg = JSON.parse(read('package.json'));
function ok(v,m){ if(!v) throw new Error(m); }
ok(batch.includes('v14.0.0-material-row-parity-and-evidence'), 'missing current certificate batch runtime marker');
ok(batch.includes('v12.4.0-certificate-download-live-log-export'), 'historical live-log compatibility marker missing');
ok(batch.includes('chunk(entries, 3)'), 'certificate scans must be chunked');
ok(batch.includes('callBackend([code]'), 'missing per-code backend retry');
ok(batch.includes('reconcileCertificateParserOutputs'), 'missing backend/device reconciliation');
ok(batch.includes('fetchCertificatesDirectFromRoyalCaribbean'), 'missing direct-device fallback');
ok(batch.includes('parseFailedCodes'), 'parse failures must be separately reported');
ok(lookup.includes('downloadCertificateCatalogBatched'), 'lookup must use batched downloader');
ok(codes.includes('downloadCertificateCatalogBatched'), 'codes page must use batched downloader');
ok(offer.includes('showOfferSummary'), 'offer summary must be collapsible');
ok(offer.includes('Show offer summary'), 'compact header toggle missing');
ok(app.expo.version === '12.4.4', 'app version must be 12.4.4');
ok(app.expo.ios.buildNumber === '319', 'iOS build number must be 319');
ok(app.expo.android.versionCode === 120410, 'Android versionCode must be 120410');
ok(pkg.version === '12.4.4', 'package version must be 12.4.4');
console.log('PASS testV1239CertificateBatchCompactOffer');
