const fs = require('fs');
const path = require('path');
const root = process.cwd();
const route = fs.readFileSync(path.join(root, 'app/(tabs)/analytics.tsx'), 'utf8');
const diag = fs.readFileSync(path.join(root, 'lib/diagnosticLogger.ts'), 'utf8');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const app = JSON.parse(fs.readFileSync(path.join(root, 'app.json'), 'utf8'));
function assert(cond, msg){ if(!cond){ console.error('❌ '+msg); process.exit(1);} }
assert(pkg.version === '9.11.64', 'package version should be 9.11.64');
assert(app.expo.version === '9.11.64', 'app version should be 9.11.64');
assert(app.expo.ios.buildNumber === '9.11.64', 'ios build number should be 9.11.64');
assert(app.expo.android.versionCode === 91164, 'android versionCode should be 91164');
assert(route.includes('useWindowDimensions'), 'Casino route should include native-safe phone layout detection');
assert(route.includes('const isPhone = width < 720'), 'Casino route should define the phone breakpoint');
assert(route.includes('sideNavPhone'), 'Casino route should include phone-first top navigation styles');
assert(route.includes('tableWide'), 'Casino completed cruise table should use a protected horizontal width for phones');
assert(route.includes('showsHorizontalScrollIndicator={false}'), 'Casino dense table should be horizontally scrollable on phones');
assert(route.includes("const ROYAL_NAVY = '#123D73'"), 'Casino route should use Royal-inspired navy');
assert(route.includes("const ROYAL_AQUA = '#00A6D6'"), 'Casino route should use Royal-inspired aqua');
assert(route.includes("const ROYAL_GOLD = '#D4A00A'"), 'Casino route should use Royal-inspired gold');
assert(route.includes('<Text style={[styles.logoMark, isPhone && styles.logoMarkPhone]}>Casino</Text>'), 'Casino route should not display crown/anchor branding in nav');
assert(!route.includes('⚓'), 'Casino route should not display the anchor mark');
assert(!route.includes('diagnosticLogger'), 'Casino route must not import diagnosticLogger');
assert(!route.includes('recordDiagnosticEvent'), 'Casino route must not call recordDiagnosticEvent');
assert(!route.includes('recordDiagnosticError'), 'Casino route must not call recordDiagnosticError');
assert(!route.includes('expo-linear-gradient'), 'Casino route must not import native gradient');
assert(!route.includes('CasinoAnalyticsScreenFull'), 'Casino route must not import legacy full analytics screen');
assert(!route.includes('.split('), 'Casino route must avoid direct .split calls while investigating Hermes split crash');
assert(route.includes('v1074: Casino dashboard finished phone-first light theme'), 'Casino footer should identify v1074 finish');
assert(route.includes('Offer Attribution Ledger'), 'Offer attribution section should remain');
assert(route.includes('True Make-Out Ledger'), 'True make-out section should remain');
assert(route.includes('Modal'), 'Drill-down Modal should remain');
assert(diag.includes('disable automatic AsyncStorage writes'), 'diagnostic logger should document disabled auto persistence');
assert(!/function schedulePersist\(\) \{[\s\S]*AsyncStorage\.setItem/.test(diag), 'schedulePersist must not call AsyncStorage.setItem automatically');
console.log('✅ v1074 Casino mobile light finish QA checks passed');
