const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),ts=require('typescript');
const R=path.resolve(__dirname,'..'),T=fs.mkdtempSync(path.join(os.tmpdir(),'easyseas-opt10-release-'));
function c(r){const s=path.join(R,'lib','optimization',r),o=path.join(T,r.replace(/\.ts$/,'.js'));fs.mkdirSync(path.dirname(o),{recursive:true});const x=ts.transpileModule(fs.readFileSync(s,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true},fileName:s,reportDiagnostics:true});const errors=(x.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error);assert.strictEqual(errors.length,0,`transpile ${r}`);fs.writeFileSync(o,x.outputText)}
['featureFlags.ts','models/statistics.ts','recommendationAuthority.ts','release/types.ts','release/evaluateOptimizerReleaseGate.ts','release/getReleaseGatedRecommendationAuthority.ts'].forEach(c);
const{evaluateOptimizerReleaseGate}=require(path.join(T,'release/evaluateOptimizerReleaseGate.js'));
const{getReleaseGatedRecommendationAuthority}=require(path.join(T,'release/getReleaseGatedRecommendationAuthority.js'));
const automated={generatedAt:'2026-07-15T20:00:00-07:00',automatedRegressionPassed:true,scenarioMatrixPassed:true,typeSyntaxPassed:true,accessibilityAuditPassed:true,protectedFilesUnchanged:true,profileIsolationPassed:true,deterministicReproducibilityPassed:true,rollbackVerified:true,privacyAuditPassed:true,archiveIntegrityPassed:true,requestedFlags:{personalCertificateOptimizerEnabled:true,personalCertificateOptimizerLiveAdvisorEnabled:true,personalCertificateOptimizerLearningEnabled:true}};
const blocked=evaluateOptimizerReleaseGate({...automated,certificateLibraryAuthoritative:false,royalAuthenticatedDataValidated:false,carnivalAuthenticatedDataValidated:false,nativeIosValidated:false,nativeAndroidValidated:false,productionDataReadbackVerified:false});
assert.strictEqual(blocked.status,'blocked-data-prerequisites');assert.strictEqual(blocked.productionEnableAllowed,false);assert.deepStrictEqual(blocked.effectiveFlags,{personalCertificateOptimizerEnabled:false,personalCertificateOptimizerLiveAdvisorEnabled:false,personalCertificateOptimizerLearningEnabled:false});assert.strictEqual(getReleaseGatedRecommendationAuthority(automated.requestedFlags,blocked),'legacy-static');
const nativeBlocked=evaluateOptimizerReleaseGate({...automated,certificateLibraryAuthoritative:true,royalAuthenticatedDataValidated:true,carnivalAuthenticatedDataValidated:true,nativeIosValidated:false,nativeAndroidValidated:false,productionDataReadbackVerified:false});assert.strictEqual(nativeBlocked.status,'blocked-native-validation');
const ready=evaluateOptimizerReleaseGate({...automated,certificateLibraryAuthoritative:true,royalAuthenticatedDataValidated:true,carnivalAuthenticatedDataValidated:true,nativeIosValidated:true,nativeAndroidValidated:true,productionDataReadbackVerified:true});assert.strictEqual(ready.status,'release-ready');assert(ready.productionEnableAllowed);assert.strictEqual(getReleaseGatedRecommendationAuthority(automated.requestedFlags,ready),'personal-optimizer');
const failed=evaluateOptimizerReleaseGate({...automated,automatedRegressionPassed:false,certificateLibraryAuthoritative:true,royalAuthenticatedDataValidated:true,carnivalAuthenticatedDataValidated:true,nativeIosValidated:true,nativeAndroidValidated:true,productionDataReadbackVerified:true});assert.strictEqual(failed.status,'blocked-automated-validation');
console.log('PASS OPT-10 release gate and authority');
