const assert = require('assert');
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const DIR = path.join(ROOT, 'lib', 'optimization', 'engine');
const required = ['types.ts','determineCurrentLockedCertificate.ts','assessSafetyModes.ts','evaluateCandidateTargets.ts','buildOptimalStoppingRecommendation.ts','legacyAdapter.ts','zodSchemas.ts','index.ts'];
for (const file of required) assert(fs.existsSync(path.join(DIR,file)), `Missing ${file}`);
const types=fs.readFileSync(path.join(DIR,'types.ts'),'utf8');
for(const token of ['CertificateCandidateEvaluation','CertificateRecommendationSnapshot','rawIncrementalExpectedValue','riskAdjustedIncrementalExpectedValue','probabilityOfExceedingRemainingBankroll','RecommendationHistoricalEvidence']) assert(types.includes(token),`Missing ${token}`);
const engine=fs.readFileSync(path.join(DIR,'buildOptimalStoppingRecommendation.ts'),'utf8');
const precedence=['DATA_UNAVAILABLE','HARD_STOP','STOP_NOW','BANK_YOUR_WIN','DO_NOT_CHASE','PLAY_ONE_MORE_SESSION','CONTINUE_UNTIL_TARGET','PROFIT_PROTECTED_PUSH','EXCELLENT_OPPORTUNITY'];
for(const token of precedence) assert(engine.includes(token),`Missing action ${token}`);
assert(engine.indexOf("input.hardStops.length > 0") < engine.indexOf("if (!best)"), 'hard stop must precede continuation selection');
assert(engine.includes('No gambling continuation is described as risk-free'));
assert(!/actionLabel[^]*Risk-Free Push/i.test(engine));
const safety=fs.readFileSync(path.join(DIR,'assessSafetyModes.ts'),'utf8');
assert(safety.includes('hardDailyLossLimit'));
assert(safety.includes('hardTripLossLimit'));
assert(safety.includes('lockedProfitFloor'));
assert(safety.toLowerCase().includes('points-per-hour pace has materially deteriorated'));
const evaluator=fs.readFileSync(path.join(DIR,'evaluateCandidateTargets.ts'),'utf8');
assert(evaluator.includes('success.probability * incrementalCertificateValue - expectedLoss.expectedAdditionalLoss'));
assert(evaluator.toLowerCase().includes('conservative replacement assumption'));
const currentLegacy=fs.readFileSync(path.join(ROOT,'lib','certificates','certificateChaseRecommendation.ts'),'utf8');
assert(currentLegacy.includes('buildCertificateChaseRecommendation'), 'legacy rollback implementation must remain available');
const flags=fs.readFileSync(path.join(ROOT,'lib','optimization','featureFlags.ts'),'utf8');
assert(flags.includes('personalCertificateOptimizerEnabled: false'));
const authority=fs.readFileSync(path.join(ROOT,'lib','optimization','recommendationAuthority.ts'),'utf8');
assert(authority.includes("'legacy-static'"));
const index=fs.readFileSync(path.join(ROOT,'lib','optimization','index.ts'),'utf8');
assert(index.includes("export * from '@/lib/optimization/engine'"));
for(const file of required){const source=fs.readFileSync(path.join(DIR,file),'utf8');assert(!/knownProfileFallback|scott\.merlis|KNOWN_CASINO_PROFILE_EMAILS/i.test(source),`${file} must not use hidden personal data`);}
console.log('PASS OPT-4 engine architecture and precedence');
