const assert=require('assert'),fs=require('fs'),path=require('path');const R=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(R,p),'utf8');
for(const p of ['lib/optimization/release/evaluateOptimizerReleaseGate.ts','lib/optimization/release/getReleaseGatedRecommendationAuthority.ts','backend/repositories/casinoOptimizationRepository.ts','backend/services/casino-optimization/optimizationSnapshotService.ts','backend/trpc/routes/certificate-optimization.ts'])assert(fs.existsSync(path.join(R,p)),`missing ${p}`);
const flags=read('lib/optimization/featureFlags.ts');for(const key of ['personalCertificateOptimizerEnabled: false','personalCertificateOptimizerLiveAdvisorEnabled: false','personalCertificateOptimizerLearningEnabled: false'])assert(flags.includes(key));
const route=read('backend/trpc/routes/certificate-optimization.ts');assert(route.includes('x-easyseas-owner-scope'));assert(route.includes('assertOptimizationOwnerScope'));assert(!route.includes('authorization'));assert(!route.includes('cookie'));
const repo=read('backend/repositories/casinoOptimizationRepository.ts');assert(repo.includes('payloadFingerprint'));assert(repo.includes('ownerProfileId'));
const ui=['app/casino/live-certificate-advisor.tsx','app/casino/personal-gambling-profile.tsx','app/casino/certificate-threshold-detail.tsx','app/casino/personal-optimization-alerts.tsx','app/casino/optimization-accuracy.tsx'].map(read).join('\n');assert(ui.includes('accessibility'));assert(!ui.includes('buildOptimalStoppingRecommendation'));
const allOptimization=fs.readdirSync(path.join(R,'lib/optimization'),{recursive:true}).filter(x=>typeof x==='string'&&x.endsWith('.ts')).map(x=>read(path.join('lib/optimization',x))).join('\n');for(const secret of ['Bearer ey','password =','apiKey ='])assert(!allOptimization.includes(secret));
const router=read('backend/trpc/app-router.ts');assert(router.includes('certificateOptimizationRouter'));
console.log('PASS OPT-10 release architecture, privacy, and accessibility');
