const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const analytics = fs.readFileSync(path.join(root, 'app/(tabs)/analytics.tsx'), 'utf8');
const flow = fs.readFileSync(path.join(root, 'lib/analytics/casinoTabDataFlow.ts'), 'utf8');
function assert(cond, msg) { if (!cond) { console.error(`❌ ${msg}`); process.exit(1); } }
assert(analytics.includes('CURRENT_CLUB_ROYALE_SEASON_START'), 'Analytics imports current Club Royale season start');
assert(analytics.includes('CURRENT_CLUB_ROYALE_SEASON_END'), 'Analytics imports current Club Royale season end');
assert(analytics.includes('function isCurrentClubRoyaleSeasonDate'), 'Analytics can identify current Club Royale season rows');
assert(analytics.includes('officialCurrentSeasonPoints = 0'), 'Derived session builder accepts official current-season points');
assert(analytics.includes('Official Club Royale current-season balance adjustment'), 'Official Club Royale balance adjustment session is created');
assert(analytics.includes('balanceAdjustmentPoints * 5'), 'Official current-season balance uses $5/point coin-in');
assert(analytics.includes('const currentYearPoints = Math.max(loyaltyClubRoyalePoints, clubRoyaleCurrentYearPoints, currentSeasonMetrics.points)'), 'Current year points include synced/manual Club Royale points');
assert(analytics.includes('const currentSeasonRetainGap = Math.max(0, CLUB_ROYALE_TIERS.Signature.threshold - currentYearPoints)'), 'Signature retain gap uses official current-year points');
assert(analytics.includes('const currentSeasonCoinInEstimate = currentYearPoints * 5'), 'Current season coin-in uses points x $5');
assert(analytics.includes('buildAnalyticsSessionsForCasinoTabs(casinoTabDataFlow, sessions, currentYearPoints)'), 'Analytics sessions are built from flow, raw sessions, and official current-year balance');
assert(analytics.includes('}, [casinoTabDataFlow, currentYearPoints, sessions]);'), 'Analytics sessions useMemo depends on casino flow, current points, and raw sessions');
assert(analytics.includes('<Text style={styles.sessionHistoryValue}>{analyticsSessions.length}</Text>'), 'Session summary card counts derived analytics sessions, not only manual sessions');
assert(analytics.includes('{[...analyticsSessions]') && analytics.includes('Recent Sessions ({analyticsSessions.length} total)'), 'Recent Sessions list uses analyticsSessions');
assert(analytics.includes('currentSeasonCoinInEstimate') && analytics.includes('currentSeasonEstimatedPlayHours'), 'Calcs fallback uses official current-season estimates');
assert(flow.includes('derivedSessions') && flow.includes('tabTotals'), 'Casino tab data flow still exposes derived sessions and tab totals');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const app = JSON.parse(fs.readFileSync(path.join(root, 'app.json'), 'utf8'));
assert(pkg.version === '9.11.54', 'package version bumped to 9.11.54');
assert(app.expo.version === '9.11.54', 'app version bumped to 9.11.54');
assert(app.expo.ios.buildNumber === '9.11.54', 'iOS buildNumber bumped to 9.11.54');
assert(app.expo.android.versionCode === 91154, 'Android versionCode bumped to 91154');
console.log('✅ v1060 casino calculation flow checks passed');
