const fs = require('fs');
function read(path) { return fs.readFileSync(path, 'utf8'); }
function assert(cond, msg) { if (!cond) { console.error('❌', msg); process.exit(1); } }
const pkg = JSON.parse(read('package.json'));
const app = JSON.parse(read('app.json'));
assert(pkg.version === '9.11.46', 'package version must be 9.11.46');
assert(app.expo.version === '9.11.46', 'app version must be 9.11.46');
assert(app.expo.ios.buildNumber === '9.11.46', 'iOS build number must be 9.11.46');
assert(app.expo.android.versionCode === 91146, 'Android version code must be 91146');
const converter = read('lib/royalCaribbean/loyaltyConverter.ts');
assert(converter.includes('estimateCrownAnchorPointsFromRemaining'), 'C&A remaining-points estimator missing');
assert(converter.includes('sumCrownAnchorPointsFromSailings'), 'C&A loyalty/history sailing sum fallback missing');
assert(converter.includes("'currentTierCredits'"), 'Club Royale current tier credits parser missing');
const network = read('lib/royalCaribbean/networkMonitorScript.ts');
assert(network.includes('/api/casino/v1/loyalty-data'), 'Casino loyalty-data endpoint not monitored');
assert(network.includes('/guestAccounts/loyalty/history'), 'C&A loyalty/history endpoint not monitored');
const sync = read('state/RoyalCaribbeanSyncProvider.tsx');
assert(sync.includes('mergeLoyaltyStateData'), 'loyalty state merge helper missing');
assert(sync.includes('loyaltyDataForPreview'), 'sync preview must use effective extended loyalty data');
assert(sync.includes('extendedLoyaltyToStateData'), 'extended loyalty -> state data bridge missing');
const step4 = read('lib/royalCaribbean/step4_loyalty.ts');
assert(step4.includes('Merged visible loyalty card values'), 'visible My Account loyalty card merge missing');
assert(step4.includes('646 Cruise Points'), 'visible cruise points regex guard missing');
assert(step4.includes('your\\\\s+current\\\\s+tier\\\\s+credits') || step4.includes('your\\s+current\\s+tier\\s+credits'), 'visible Club Royale tier credits parser missing');
const rules = read('lib/portCasinoRules.ts');
assert(rules.includes('continuousWhileDocked'), 'CocoCay continuous open rule missing');
assert(rules.includes('does not close just because the ship is docked'), 'CocoCay ownership rule note missing');
const availability = read('lib/casinoAvailability.ts');
assert(availability.includes('continuous private-destination availability'), 'casino availability must treat CocoCay as continuous');
const agenda = read('app/day-agenda.tsx');
assert(agenda.includes('casino-continuous'), 'day agenda must render continuous private-destination casino block');
const itineraries = read('lib/knownCruiseItineraries.ts');
assert(itineraries.includes('parsePortsAndTimes'), 'trusted itinerary fallback must parse portsAndTimes/casino intelligence');
assert(itineraries.includes('total eclipse'), 'Celebrity Equinox VACAYA relaxed matcher missing');
const calendar = read('lib/calendar/cruiseEvents.ts');
assert(calendar.includes('getCentralTrustedCruiseItineraryDays'), 'calendar/day agenda must use central trusted itinerary fallback');
const seapass = read('lib/seaPassWebPass.ts');
assert(seapass.includes('x: 792'), 'SeaPass date x alignment not updated');
assert(seapass.includes('fontSize: 58'), 'SeaPass date font size not updated');
const dateBlock = seapass.slice(seapass.indexOf('  date: {'), seapass.indexOf('  deck: {'));
assert(!dateBlock.includes("textAnchor: 'end'"), 'SeaPass date must not be right-anchored');
console.log('✅ v1056 loyalty/CocoCay/itinerary/SeaPass checks passed');
