const fs = require('fs');
const path = require('path');
const root = process.cwd();
const route = fs.readFileSync(path.join(root, 'app/(tabs)/analytics.tsx'), 'utf8');
const diag = fs.readFileSync(path.join(root, 'lib/diagnosticLogger.ts'), 'utf8');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const app = JSON.parse(fs.readFileSync(path.join(root, 'app.json'), 'utf8'));
function assert(cond, msg){ if(!cond){ console.error('❌ '+msg); process.exit(1);} }
assert(pkg.version === '9.11.63', 'package version should be 9.11.63');
assert(app.expo.version === '9.11.63', 'app version should be 9.11.63');
assert(app.expo.android.versionCode === 91163, 'android versionCode should be 91163');
assert(!route.includes('diagnosticLogger'), 'Casino route must not import diagnosticLogger');
assert(!route.includes('recordDiagnosticEvent'), 'Casino route must not call recordDiagnosticEvent');
assert(!route.includes('recordDiagnosticError'), 'Casino route must not call recordDiagnosticError');
assert(!route.includes('expo-linear-gradient'), 'Casino route must not import native gradient');
assert(!route.includes('CasinoAnalyticsScreenFull'), 'Casino route must not import legacy full analytics screen');
assert(!route.includes('.split('), 'Casino route must avoid direct .split calls while investigating Hermes split crash');
assert(route.includes('v1073: Casino dashboard native-safe mode'), 'Casino footer should identify v1073 native-safe mode');
assert(route.includes('Offer Attribution Ledger'), 'Offer attribution section should remain');
assert(route.includes('True Make-Out Ledger'), 'True make-out section should remain');
assert(route.includes('Modal'), 'Drill-down Modal should remain');
assert(diag.includes('disable automatic AsyncStorage writes'), 'diagnostic logger should document disabled auto persistence');
assert(!/function schedulePersist\(\) \{[\s\S]*AsyncStorage\.setItem/.test(diag), 'schedulePersist must not call AsyncStorage.setItem automatically');
console.log('✅ v1073 Casino no-native-diagnostics QA checks passed');
