const fs = require('fs');
function assert(cond, msg){ if(!cond){ console.error('❌ '+msg); process.exit(1);} }
const route = fs.readFileSync('app/(tabs)/analytics.tsx','utf8');
const full = fs.readFileSync('components/analytics/CasinoAnalyticsScreenFull.tsx','utf8');
const pkg = JSON.parse(fs.readFileSync('package.json','utf8'));
const app = JSON.parse(fs.readFileSync('app.json','utf8'));
assert(route.includes('CASINO_ROUTE_SHELL_MOUNTED'), 'Casino route shell mount diagnostic missing');
assert(route.includes('CASINO_FULL_MODULE_REQUIRE_STARTED'), 'full module require start diagnostic missing');
assert(route.includes('CASINO_FULL_MODULE_REQUIRE_OK'), 'full module require ok diagnostic missing');
assert(route.includes('CASINO_FULL_MODULE_REQUIRE_FAILED'), 'full module require failure diagnostic missing');
assert(route.includes('require(\'@/components/analytics/CasinoAnalyticsScreenFull\')') || route.includes('require("@/components/analytics/CasinoAnalyticsScreenFull")'), 'full screen should be loaded from safe route shell');
assert(route.includes('casino-route-safe-fallback'), 'safe fallback testID missing');
assert(!route.includes("from 'expo-file-system'"), 'route should not import expo-file-system at module load');
assert(full.includes("expo-file-system/legacy"), 'full casino screen should use legacy FileSystem export API');
assert(!full.includes('File as ExpoFile'), 'new File API should be removed from full casino screen');
assert(full.includes('writeAsStringAsync'), 'CSV export should write through legacy FileSystem');
assert(pkg.version === '9.11.57', 'package version not bumped to 9.11.57');
assert(app.expo.version === '9.11.57', 'app.json expo.version not bumped');
assert(app.expo.ios.buildNumber === '9.11.57', 'iOS buildNumber not bumped');
assert(app.expo.android.versionCode === 91157, 'Android versionCode not bumped');
console.log('✅ v1067 casino safe loader checks passed');
