import type { BookedCruise } from '@/types/models';

const DEFAULT_GUEST_NAMES = ['Scott Merlis'];

/** User-confirmed authoritative booked cruise manifest. Keep this list exact and deduplicated. */
export const USER_CONFIRMED_BOOKED_CRUISE_MANIFEST: BookedCruise[] = [
  {
    id: 'booked-quantum-2026-04-07',
    reservationNumber: '182213',
    shipName: 'Quantum of the Seas',
    sailDate: '2026-04-07',
    returnDate: '2026-04-10',
    departurePort: 'Los Angeles, California',
    destination: 'Mexican Riviera',
    itineraryName: '3 Night Ensenada Cruise',
    nights: 3,
    cabinType: 'Balcony',
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Los Angeles, California', 'Ensenada, Mexico', 'Los Angeles, California'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    checkInDate: '2026-02-21',
  },
  {
    id: 'booked-quantum-2026-04-10',
    reservationNumber: '9449386',
    shipName: 'Quantum of the Seas',
    sailDate: '2026-04-10',
    returnDate: '2026-04-15',
    departurePort: 'Los Angeles, California',
    destination: 'Mexican Riviera',
    itineraryName: '5 Night Cabo Overnight Cruise',
    nights: 5,
    cabinType: 'OV Balcony (4D)',
    cabinNumber: '11138',
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Los Angeles, California', 'Cabo San Lucas, Mexico', 'Cabo San Lucas, Mexico', 'Los Angeles, California'],
    taxes: 126.03,
    offerCode: '25LVA503',
    freePlay: 0,
    freeOBC: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    checkInDate: '2026-02-24',
  },
  {
    id: 'booked-quantum-2026-04-15',
    reservationNumber: '4913547',
    shipName: 'Quantum of the Seas',
    sailDate: '2026-04-15',
    returnDate: '2026-04-21',
    departurePort: 'Los Angeles, California',
    destination: 'Mexican Riviera',
    itineraryName: '6 Night Cabo Overnight and Ensenada',
    nights: 6,
    cabinType: 'OV Balcony (2D)',
    cabinNumber: '11540',
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Los Angeles, California', 'Cabo San Lucas, Mexico', 'Cabo San Lucas, Mexico', 'Ensenada, Mexico', 'Los Angeles, California'],
    taxes: 151.7,
    offerCode: '25MIX403',
    freePlay: 0,
    freeOBC: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    checkInDate: '2026-03-01',
  },
  {
    id: 'booked-quantum-2026-04-21',
    reservationNumber: '1527694',
    shipName: 'Quantum of the Seas',
    sailDate: '2026-04-21',
    returnDate: '2026-04-24',
    departurePort: 'Los Angeles, California',
    destination: 'Mexican Riviera',
    itineraryName: '3 Night Ensenada Cruise',
    nights: 3,
    cabinType: 'OV Balcony (4D)',
    cabinNumber: '8682',
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Los Angeles, California', 'Ensenada, Mexico', 'Los Angeles, California'],
    taxes: 218.81,
    offerCode: '25MIX304',
    freePlay: 75,
    freeOBC: 50,
    usedNextCruiseCertificate: true,
    nextCruiseCertificateValue: 50,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    checkInDate: '2026-03-07',
  },
  {
    id: 'booked-icon-2026-05-09',
    reservationNumber: '871437',
    shipName: 'Icon of the Seas',
    sailDate: '2026-05-09',
    returnDate: '2026-05-16',
    departurePort: 'Miami, Florida',
    destination: 'Western Caribbean',
    itineraryName: '7 Night Western Caribbean Cruise',
    nights: 7,
    cabinType: 'Interior GTY',
    cabinNumber: '7616',
    retailValue: 4800,
    totalRetailCost: 4800,
    originalPrice: 4800,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Miami, Florida', 'Costa Maya, Mexico', 'Roatan, Honduras', 'Cozumel, Mexico', 'Perfect Day at CocoCay, Bahamas', 'Miami, Florida'],
    taxes: 160.22,
    offerCode: '25WST303',
    freePlay: 0,
    freeOBC: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    checkInDate: '2026-03-26',
  },
  {
    id: 'booked-symphony-2026-05-17',
    reservationNumber: '3820089',
    shipName: 'Symphony of the Seas',
    sailDate: '2026-05-17',
    returnDate: '2026-05-24',
    departurePort: 'Galveston, Texas',
    destination: 'Western Caribbean',
    itineraryName: '7 Night Western Caribbean Cruise',
    nights: 7,
    cabinType: 'Ocean View Balcony GTY',
    retailValue: 3786,
    totalRetailCost: 3786,
    originalPrice: 3786,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Galveston, Texas', 'Cozumel, Mexico', 'Roatan, Honduras', 'Puerto Costa Maya, Mexico', 'Galveston, Texas'],
    taxes: 152.28,
    offerCode: '25DEP104',
    freePlay: 0,
    freeOBC: 200,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    checkInDate: '2026-04-02',
  },
  {
    id: 'booked-navigator-2026-05-29',
    reservationNumber: '5455777',
    shipName: 'Navigator of the Seas',
    sailDate: '2026-05-29',
    returnDate: '2026-06-05',
    departurePort: 'Los Angeles, California',
    destination: 'Mexican Riviera',
    itineraryName: '7 Night Ensenada, Cabo & Mazatlan',
    nights: 7,
    cabinType: 'Ocean View GTY',
    retailValue: 1798,
    totalRetailCost: 1798,
    originalPrice: 1798,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Los Angeles, California', 'Ensenada, Mexico', 'Cabo San Lucas, Mexico', 'Mazatlan, Mexico', 'Los Angeles, California'],
    taxes: 159.78,
    offerCode: '25WCR704',
    freePlay: 0,
    freeOBC: 50,
    usedNextCruiseCertificate: true,
    nextCruiseCertificateValue: 100,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    checkInDate: '2026-04-14',
  },
  {
    id: 'booked-quantum-2026-06-05',
    reservationNumber: '3879193',
    shipName: 'Quantum of the Seas',
    sailDate: '2026-06-05',
    returnDate: '2026-06-12',
    departurePort: 'Los Angeles, California',
    destination: 'Mexican Riviera',
    itineraryName: '7 Night Cabo Overnight Catalina & Ensenada',
    nights: 7,
    cabinType: 'Ocean View Balcony GTY',
    retailValue: 2650,
    totalRetailCost: 2650,
    originalPrice: 2650,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Los Angeles, California', 'Catalina Island, California', 'Cabo San Lucas, Mexico', 'Cabo San Lucas, Mexico', 'Ensenada, Mexico', 'Los Angeles, California'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    checkInDate: '2026-04-21',
  },
  {
    id: 'booked-quantum-2026-06-19',
    reservationNumber: '6173746',
    shipName: 'Quantum of the Seas',
    sailDate: '2026-06-19',
    returnDate: '2026-06-26',
    departurePort: 'Los Angeles, California',
    destination: 'Mexican Riviera',
    itineraryName: '7 Night Cabo Overnight & Ensenada',
    nights: 7,
    cabinType: 'Ocean View GTY',
    retailValue: 2250,
    totalRetailCost: 2250,
    originalPrice: 2250,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Los Angeles, California', 'Cabo San Lucas, Mexico', 'Cabo San Lucas, Mexico', 'Cabo San Lucas, Mexico', 'Ensenada, Mexico', 'Los Angeles, California'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    checkInDate: '2026-05-05',
  },
  {
    id: 'booked-star-2026-07-05',
    reservationNumber: '2656334',
    bookingId: '2656334',
    shipName: 'Star of the Seas',
    sailDate: '2026-07-05',
    returnDate: '2026-07-12',
    departurePort: 'Port Canaveral, Florida',
    destination: 'Eastern Caribbean & Perfect Day',
    itineraryName: '7 Night Eastern Caribbean & Perfect Day',
    nights: 7,
    cabinType: 'Interior',
    cabinCategory: 'V4',
    cabinNumber: '10518',
    stateroomNumber: '10518',
    stateroomCategoryCode: 'V4',
    stateroomType: 'Interior Stateroom Obstructed View',
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Port Canaveral, Florida', 'Eastern Caribbean', 'Perfect Day at CocoCay, Bahamas', 'Port Canaveral, Florida'],
    taxes: 150.92,
    taxesFeesEstimate: 150.92,
    amountPaid: 200,
    depositPaid: 200,
    balanceDue: 0,
    netEffectivePaid: 150.92,
    retailValue: 5500,
    totalRetailCost: 5500,
    originalPrice: 5500,
    pricePaid: 150.92,
    totalCasinoDiscount: 5500,
    compValue: 5349.08,
    cruiseValueCaptured: 5349.08,
    totalEconomicValue: 5349.08,
    offerCode: '26TIER3',
    offerName: 'CR Targeted Offer (26TIER3)',
    offerCategory: 'Casino Comp',
    freeOBC: 50,
    perks: ['Casino Comp', 'YHP5-Casino Slots', '$50 onboard credit'],
    specialRequests: 'CR TARGETED OFFER(26TIER3); dining waitlist 8:30 PM',
    cruiseSource: 'royal',
    brand: 'Royal Caribbean',
    casinoProgram: 'clubRoyale',
    calculationConfidence: 'actual',
    notes: 'Reservation issued 2026-04-28. Cruise-only package. Casino Comp CGRP-FIT PROMO YHP5-Casino Slots. User-updated estimated retail value $5,500; taxes/fees/port expenses $150.92; amount paid $200; balance due $0; onboard credit $50. Casino analytics should use $5,500 retail value and $150.92 net effective paid while preserving the $200 paid amount separately.',
    sourcePayload: {
      reservationId: '2656334',
      issueDate: '2026-04-28',
      packageType: 'Cruise Only',
      ship: 'STAR OF THE SEAS',
      sailingDate: '2026-07-05',
      departureDate: '2026-07-05',
      cruiseDuration: '07 Nights',
      itinerary: '7 NIGHT EASTERN CARIBBEAN & PERFECT DAY',
      stateroom: 'V4 10518',
      stateroomDescription: 'Interior Stateroom Obstructed View',
      crownAndAnchorNumber: '305812247',
      specialServices: 'CR TARGETED OFFER(26TIER3)',
      diningWaitlist: '8:30 PM',
      totalCruiseFare: 5500,
      casinoCompDiscount: 3191,
      casinoSlotsPromoDiscount: 2405,
      taxesFeesPortExpenses: 150.92,
      totalCharge: 150.92,
      amountPaid: 200,
      balanceDue: 0,
      onboardCredit: 50,
    },
  },
  {
    id: 'booked-navigator-2026-07-17',
    reservationNumber: '4097701',
    shipName: 'Navigator of the Seas',
    sailDate: '2026-07-17',
    returnDate: '2026-07-24',
    departurePort: 'Los Angeles, California',
    destination: 'Mexican Riviera',
    itineraryName: '7 Night Cabo Overnight & Ensenada',
    nights: 7,
    cabinType: 'Ocean View Balcony GTY',
    cabinNumber: '10718',
    retailValue: 3874,
    totalRetailCost: 3874,
    originalPrice: 3874,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Los Angeles, California', 'Cabo San Lucas, Mexico', 'Cabo San Lucas, Mexico', 'Ensenada, Mexico', 'Los Angeles, California'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
  },
  {
    id: 'booked-navigator-2026-07-24',
    reservationNumber: 'NAV-20260724',
    shipName: 'Navigator of the Seas',
    sailDate: '2026-07-24',
    returnDate: '2026-07-31',
    departurePort: 'Los Angeles, California',
    destination: 'Mexican Riviera',
    itineraryName: '7 Night Cabo Overnight & Ensenada',
    nights: 7,
    cabinType: 'Ocean View Balcony GTY',
    retailValue: 3750,
    totalRetailCost: 3750,
    originalPrice: 3750,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Los Angeles, California', 'Cabo San Lucas, Mexico', 'Cabo San Lucas, Mexico', 'Ensenada, Mexico', 'Los Angeles, California'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
  },
  {
    id: 'booked-celebrity-equinox-2026-08-05',
    reservationNumber: 'CELEQ-20260805',
    shipName: 'Celebrity Equinox',
    sailDate: '2026-08-05',
    returnDate: '2026-08-14',
    departurePort: 'Barcelona, Spain',
    destination: 'Mediterranean',
    itineraryName: 'Mediterranean / Ibiza / Eclipse Cruise',
    nights: 9,
    cabinType: 'Ocean View O2',
    retailValue: 5156,
    totalRetailCost: 5156,
    originalPrice: 5156,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Barcelona, Spain', 'Ibiza, Spain', 'Mediterranean', 'Barcelona, Spain'],
    taxes: 0,
    cruiseSource: 'celebrity',
    brand: 'celebrity',
    casinoProgram: 'blueChip',
    itineraryNeedsManualEntry: true,
  },
  {
    id: 'booked-navigator-2026-08-21',
    reservationNumber: 'NAV-20260821',
    shipName: 'Navigator of the Seas',
    sailDate: '2026-08-21',
    returnDate: '2026-08-28',
    departurePort: 'Los Angeles, California',
    destination: 'Mexican Riviera',
    itineraryName: '7 Night Cabo Overnight & Ensenada',
    nights: 7,
    cabinType: 'Ocean View Balcony GTY',
    retailValue: 3700,
    totalRetailCost: 3700,
    originalPrice: 3700,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Los Angeles, California', 'Cabo San Lucas, Mexico', 'Cabo San Lucas, Mexico', 'Ensenada, Mexico', 'Los Angeles, California'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
  },
  {
    id: 'booked-harmony-2026-09-05',
    reservationNumber: 'HARMONY-20260905',
    shipName: 'Harmony of the Seas',
    sailDate: '2026-09-05',
    returnDate: '2026-09-10',
    departurePort: 'Port Canaveral, Florida',
    destination: 'Caribbean',
    itineraryName: '5 Night Caribbean from Orlando',
    nights: 5,
    cabinType: 'Ocean View',
    cabinNumber: '7516',
    stateroomNumber: '7516',
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Port Canaveral, Florida', 'Caribbean', 'Port Canaveral, Florida'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    itineraryNeedsManualEntry: true,
    notes: 'User-confirmed replacement for former September 2026 Ovation bookings. Sailing out of Orlando / Port Canaveral.',
  },
  {
    id: 'booked-harmony-2026-09-10',
    reservationNumber: 'HARMONY-20260910',
    shipName: 'Harmony of the Seas',
    sailDate: '2026-09-10',
    returnDate: '2026-09-15',
    departurePort: 'Port Canaveral, Florida',
    destination: 'Caribbean',
    itineraryName: '5 Night Caribbean from Orlando',
    nights: 5,
    cabinType: 'TBD',
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Port Canaveral, Florida', 'Caribbean', 'Port Canaveral, Florida'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    itineraryNeedsManualEntry: true,
    notes: 'User-confirmed replacement for former September 2026 Ovation bookings. Sailing out of Orlando / Port Canaveral.',
  },
  {
    id: 'booked-harmony-2026-09-15',
    reservationNumber: 'HARMONY-20260915',
    shipName: 'Harmony of the Seas',
    sailDate: '2026-09-15',
    returnDate: '2026-09-19',
    departurePort: 'Port Canaveral, Florida',
    destination: 'Caribbean',
    itineraryName: '4 Night Caribbean from Orlando',
    nights: 4,
    cabinType: 'Interior GTY',
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Port Canaveral, Florida', 'Caribbean', 'Port Canaveral, Florida'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    itineraryNeedsManualEntry: true,
    notes: 'User-confirmed replacement for former September 2026 Ovation bookings. Sailing out of Orlando / Port Canaveral.',
  },
  {
    id: 'booked-anthem-2026-09-29',
    reservationNumber: '7563285',
    shipName: 'Anthem of the Seas',
    sailDate: '2026-09-29',
    returnDate: '2026-10-11',
    departurePort: 'Vancouver, British Columbia',
    destination: 'Hawaii',
    itineraryName: '12 Night Hawaii Cruise',
    nights: 12,
    cabinType: 'Ocean View Midship',
    retailValue: 4226,
    totalRetailCost: 4226,
    originalPrice: 4226,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Vancouver, British Columbia', 'Seattle, Washington', 'Kailua Kona, Hawaii', 'Honolulu (Oahu), Hawaii', 'Honolulu (Oahu), Hawaii'],
    taxes: 131.92,
    offerCode: '2511A03A',
    freePlay: 500,
    freeOBC: 50,
    usedNextCruiseCertificate: true,
    nextCruiseCertificateValue: 200,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    checkInDate: '2026-08-15',
  },
  {
    id: 'booked-allure-2026-10-25',
    reservationNumber: 'ALLURE-20261025',
    shipName: 'Allure of the Seas',
    sailDate: '2026-10-25',
    returnDate: '2026-11-01',
    departurePort: 'Fort Lauderdale, Florida',
    destination: 'Eastern Caribbean & Perfect Day',
    itineraryName: '7 Night Eastern Caribbean & Perfect Day',
    nights: 7,
    cabinType: 'Ocean View',
    retailValue: 3900,
    totalRetailCost: 3900,
    originalPrice: 3900,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Fort Lauderdale, Florida', 'Eastern Caribbean', 'Perfect Day at CocoCay, Bahamas', 'Fort Lauderdale, Florida'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    itineraryNeedsManualEntry: true,
  },
  {
    id: 'booked-oasis-2026-11-09',
    reservationNumber: 'OASIS-20261109',
    shipName: 'Oasis of the Seas',
    sailDate: '2026-11-09',
    returnDate: '2026-11-13',
    departurePort: 'Fort Lauderdale, Florida',
    destination: 'Caribbean',
    itineraryName: '3 Night Caribbean (Tentative)',
    nights: 3,
    cabinType: 'Balcony',
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Fort Lauderdale, Florida', 'Caribbean', 'Fort Lauderdale, Florida'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    itineraryNeedsManualEntry: true,
    notes: 'Tentative booking. User supplied Nov 9-13, 2026 date range.',
  },
  {
    id: 'booked-adventure-2026-11-15',
    reservationNumber: 'ADVENTURE-20261115',
    shipName: 'Adventure of the Seas',
    sailDate: '2026-11-15',
    returnDate: '2026-11-21',
    departurePort: 'TBD',
    destination: 'TBD',
    itineraryName: '6 Night Adventure of the Seas',
    nights: 6,
    cabinType: 'TBD',
    retailValue: 2250,
    totalRetailCost: 2250,
    originalPrice: 2250,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Fort Lauderdale, Florida', 'Caribbean', 'Fort Lauderdale, Florida'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    itineraryNeedsManualEntry: true,
  },
  {
    id: 'booked-celebrity-beyond-2026-12-06',
    reservationNumber: 'CELBE-20261206',
    shipName: 'Celebrity Beyond',
    sailDate: '2026-12-06',
    returnDate: '2026-12-13',
    departurePort: 'Fort Lauderdale, Florida',
    destination: 'Eastern Caribbean',
    itineraryName: '7 Night Eastern Caribbean',
    nights: 7,
    cabinType: 'Deluxe Inside',
    retailValue: 2208,
    totalRetailCost: 2208,
    originalPrice: 2208,
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Fort Lauderdale, Florida', 'Eastern Caribbean', 'Fort Lauderdale, Florida'],
    taxes: 0,
    cruiseSource: 'celebrity',
    brand: 'celebrity',
    casinoProgram: 'blueChip',
    itineraryNeedsManualEntry: true,
  },
  {
    id: 'booked-hero-2027-10-16',
    reservationNumber: 'HERO-20271016',
    shipName: 'Hero of the Seas',
    sailDate: '2027-10-16',
    returnDate: '2027-10-23',
    departurePort: 'Port Canaveral, Florida',
    destination: 'Perfect Day CocoCay & Western Caribbean',
    itineraryName: '7 Night Perfect Day CocoCay & Western Caribbean',
    nights: 7,
    cabinType: 'Balcony',
    guestNames: DEFAULT_GUEST_NAMES,
    guests: 1,
    singleOccupancy: true,
    status: 'booked',
    completionState: 'upcoming',
    ports: ['Port Canaveral, Florida', 'Perfect Day at CocoCay, Bahamas', 'Western Caribbean', 'Port Canaveral, Florida'],
    taxes: 0,
    cruiseSource: 'royal',
    brand: 'royal',
    casinoProgram: 'clubRoyale',
    itineraryNeedsManualEntry: true,
  },
];
