import type { SlotMachine } from '@/types/models';

export const GLOBAL_SLOT_MACHINES: SlotMachine[] = [
  {
    id: 'dragon-link-panda-magic',
    machineName: 'Dragon Link - Panda Magic',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dragon Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRanges: { min: 88, max: 92 },
    theme: 'Asian/Panda',
    bonusMechanics: ['Hold & Spin', 'Progressive Jackpots', 'Free Games'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Grand', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25', '$1.00'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      entryConditions: ['Major jackpot > $1,200', 'Multiple dragons on reels'],
      recommendedBankroll: { min: 500, max: 2000 },
      notesAndTips: 'Look for machines with high progressive jackpot values',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'lightning-link-high-stakes',
    machineName: 'Lightning Link - High Stakes',
    manufacturer: 'Aristocrat',
    gameSeries: 'Lightning Link',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2019,
    rtpRanges: { min: 87, max: 92 },
    theme: 'Casino/Coins',
    bonusMechanics: ['Hold & Spin', 'Free Games', 'Progressive Jackpots'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Grand', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25', '$1.00', '$2.00'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      entryConditions: ['6+ lightning balls on screen'],
      recommendedBankroll: { min: 400, max: 1500 },
      notesAndTips: 'Count lightning balls left on screen before playing',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'ultimate-fire-link',
    machineName: 'Ultimate Fire Link',
    manufacturer: 'Bally',
    gameSeries: 'Ultimate Fire Link',
    volatility: 'Medium-High',
    cabinetType: 'Wide Screen',
    releaseYear: 2021,
    rtpRanges: { min: 85, max: 90 },
    theme: 'Fire/Gems',
    bonusMechanics: ['Hold & Spin', 'Mystery Symbols', 'Progressive Jackpots'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Maxi', type: 'progressive' },
      { name: 'Mega', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25', '$1.00'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      recommendedBankroll: { min: 300, max: 1200 },
      notesAndTips: 'Look for machines with fire symbols remaining',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'money-link',
    machineName: 'Money Link',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Money Link',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2022,
    rtpRanges: { min: 88, max: 93 },
    theme: 'Money/Coins',
    bonusMechanics: ['Hold & Spin', 'Progressive Jackpots'],
    jackpotTypes: [
      { name: 'Mini', type: 'mystery', mustHitBy: 50 },
      { name: 'Minor', type: 'mystery', mustHitBy: 500 },
      { name: 'Major', type: 'mystery', mustHitBy: 2500 },
      { name: 'Grand', type: 'mystery', mustHitBy: 10000 },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25', '$1.00'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: true,
      mhbThresholds: { minor: 450, major: 2300, grand: 9500 },
      entryConditions: ['Minor > $450', 'Major > $2,300', 'Grand > $9,500'],
      recommendedBankroll: { min: 400, max: 1500 },
      bonusVolatility: 'Medium',
      notesAndTips: 'Must-Hit-By jackpots make this excellent for AP',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'huff-n-puff',
    machineName: "Huff N' Puff",
    manufacturer: 'Bally',
    gameSeries: 'Huff N Puff',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRanges: { min: 85, max: 90 },
    theme: 'Three Little Pigs',
    bonusMechanics: ['Hold & Spin', 'Multipliers', 'Bonus Wheels'],
    jackpotTypes: [
      { name: 'Mini', type: 'mystery', mustHitBy: 50 },
      { name: 'Minor', type: 'mystery', mustHitBy: 500 },
      { name: 'Major', type: 'mystery', mustHitBy: 2500 },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25'],
    apMetadata: {
      persistenceType: 'Pseudo',
      hasMustHitBy: true,
      mhbThresholds: { minor: 475, major: 2400 },
      entryConditions: ['Minor > $475', 'Major > $2,400'],
      recommendedBankroll: { min: 500, max: 2000 },
      risks: ['High volatility', 'Rapid bankroll swings'],
      notesAndTips: 'Very volatile - recommend higher bankroll',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'money-mansion',
    machineName: 'Money Mansion',
    manufacturer: 'Konami',
    gameSeries: 'Money Mansion',
    volatility: 'Medium-High',
    cabinetType: 'Premium',
    releaseYear: 2023,
    rtpRanges: { min: 86, max: 91 },
    theme: 'Luxury/Money',
    bonusMechanics: ['Money Burst', 'Action Stacked Symbols', 'Free Games'],
    jackpotTypes: [
      { name: 'Mega', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.10', '$0.25'],
    apMetadata: {
      persistenceType: 'None',
      hasMustHitBy: false,
      notesAndTips: 'No AP opportunity - random outcomes',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: '88-fortunes',
    machineName: '88 Fortunes',
    manufacturer: 'Light & Wonder',
    gameSeries: '88 Fortunes',
    volatility: 'Medium',
    cabinetType: 'Slant Top',
    releaseYear: 2019,
    rtpRanges: { min: 92, max: 96 },
    theme: 'Asian/Lucky',
    bonusMechanics: ['Free Games', 'Progressive Jackpots', 'Fu Bat Feature'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Grand', type: 'progressive' },
    ],
    denominationFamilies: ['$0.88', '$1.88', '$2.88', '$5.00'],
    apMetadata: {
      persistenceType: 'None',
      hasMustHitBy: false,
      notesAndTips: 'Popular game but no persistent state',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'bao-zhu-zhao-fu',
    machineName: 'Bao Zhu Zhao Fu',
    manufacturer: 'Aristocrat',
    gameSeries: 'Bao Zhu Zhao Fu',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2021,
    rtpRanges: { min: 87, max: 92 },
    theme: 'Asian/Pearl',
    bonusMechanics: ['Hold & Spin', 'Free Games', 'Progressive Jackpots'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Grand', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      entryConditions: ['Multiple pearls on screen'],
      recommendedBankroll: { min: 300, max: 1000 },
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'dancing-drums',
    machineName: 'Dancing Drums',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Dancing Drums',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRanges: { min: 88, max: 96 },
    theme: 'Asian/Drums',
    bonusMechanics: ['Free Games', 'Multipliers', 'Fu Bat Jackpots'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Grand', type: 'progressive' },
    ],
    denominationFamilies: ['$0.88', '$1.88', '$2.88', '$5.00', '$8.80'],
    apMetadata: {
      persistenceType: 'None',
      hasMustHitBy: false,
      notesAndTips: 'High volatility - not recommended for AP',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'mighty-cash',
    machineName: 'Mighty Cash',
    manufacturer: 'Aristocrat',
    gameSeries: 'Mighty Cash',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2021,
    rtpRanges: { min: 87, max: 92 },
    theme: 'Money/Cash',
    bonusMechanics: ['Hold & Spin', 'Progressive Jackpots', 'Multipliers'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Power', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      entryConditions: ['Multiple cash symbols visible'],
      recommendedBankroll: { min: 350, max: 1200 },
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'rakin-bacon',
    machineName: "Rakin' Bacon",
    manufacturer: 'IGT',
    gameSeries: 'Rakin Bacon',
    volatility: 'Medium-High',
    cabinetType: 'Wide Screen',
    releaseYear: 2022,
    rtpRanges: { min: 85, max: 90 },
    theme: 'Pigs/Farm',
    bonusMechanics: ['Wheel Bonus', 'Multipliers', 'Progressive Jackpots'],
    jackpotTypes: [
      { name: 'Mini', type: 'mystery', mustHitBy: 25 },
      { name: 'Minor', type: 'mystery', mustHitBy: 250 },
      { name: 'Major', type: 'mystery', mustHitBy: 2500 },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    apMetadata: {
      persistenceType: 'None',
      hasMustHitBy: true,
      mhbThresholds: { minor: 225, major: 2400 },
      entryConditions: ['Minor > $225', 'Major > $2,400'],
      recommendedBankroll: { min: 300, max: 1000 },
      notesAndTips: 'Must-Hit-By makes this playable near thresholds',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'rich-little-piggies',
    machineName: 'Rich Little Piggies',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Rich Little Piggies',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRanges: { min: 88, max: 94 },
    theme: 'Pigs/Money',
    bonusMechanics: ['Free Games', 'Multipliers', 'Stacked Wilds'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    apMetadata: {
      persistenceType: 'None',
      hasMustHitBy: false,
      notesAndTips: 'Entertaining but no AP opportunity',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'buffalo-gold',
    machineName: 'Buffalo Gold',
    manufacturer: 'Aristocrat',
    gameSeries: 'Buffalo',
    volatility: 'High',
    cabinetType: 'Slant Top',
    releaseYear: 2019,
    rtpRanges: { min: 92, max: 96 },
    theme: 'Buffalo/Western',
    bonusMechanics: ['Free Games', 'Multipliers', 'Gold Buffalo Feature'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25', '$1.00'],
    apMetadata: {
      persistenceType: 'None',
      hasMustHitBy: false,
      notesAndTips: 'Very popular but no persistent features',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'jin-ji-bao-xi',
    machineName: 'Jin Ji Bao Xi',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Jin Ji Bao Xi',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2021,
    rtpRanges: { min: 88, max: 96 },
    theme: 'Asian/Prosperity',
    bonusMechanics: ['Free Games', 'Progressive Jackpots', 'Mystery Symbols'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Grand', type: 'progressive' },
    ],
    denominationFamilies: ['$0.88', '$1.88', '$2.88', '$5.00'],
    apMetadata: {
      persistenceType: 'None',
      hasMustHitBy: false,
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'lock-it-link',
    machineName: 'Lock It Link',
    manufacturer: 'Light & Wonder',
    gameSeries: 'Lock It Link',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRanges: { min: 87, max: 92 },
    theme: 'Various Themes',
    bonusMechanics: ['Hold & Spin', 'Progressive Jackpots', 'Lock Feature'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Grand', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      entryConditions: ['Multiple locked symbols visible'],
      recommendedBankroll: { min: 400, max: 1500 },
      notesAndTips: 'Check for locked symbols before playing',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'wheel-of-fortune-triple-extreme-spin',
    machineName: 'Wheel of Fortune Triple Extreme Spin',
    manufacturer: 'IGT',
    gameSeries: 'Wheel of Fortune',
    volatility: 'Medium',
    cabinetType: 'Premium',
    releaseYear: 2021,
    rtpRanges: { min: 92, max: 96 },
    theme: 'Game Show',
    bonusMechanics: ['Wheel Spins', 'Free Games', 'Multipliers'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25', '$1.00'],
    apMetadata: {
      persistenceType: 'None',
      hasMustHitBy: false,
      notesAndTips: 'Classic game, no AP opportunities',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'dollar-storm',
    machineName: 'Dollar Storm',
    manufacturer: 'Aristocrat',
    gameSeries: 'Dollar Storm',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2022,
    rtpRanges: { min: 87, max: 92 },
    theme: 'Money/Storm',
    bonusMechanics: ['Hold & Spin', 'Free Games', 'Progressive Jackpots'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Grand', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      entryConditions: ['Multiple dollar symbols on screen'],
      recommendedBankroll: { min: 300, max: 1000 },
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'cash-express',
    machineName: 'Cash Express',
    manufacturer: 'Aristocrat',
    gameSeries: 'Cash Express',
    volatility: 'Medium-High',
    cabinetType: 'Curved',
    releaseYear: 2023,
    rtpRanges: { min: 87, max: 92 },
    theme: 'Train/Money',
    bonusMechanics: ['Hold & Spin', 'Progressive Jackpots', 'Luxury Feature'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Luxury', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      entryConditions: ['Train cars on screen', 'Luxury jackpot > $2,000'],
      recommendedBankroll: { min: 500, max: 2000 },
      notesAndTips: 'Newer game with solid AP potential',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'fu-dai-lian-lian',
    machineName: 'Fu Dai Lian Lian',
    manufacturer: 'IGT',
    gameSeries: 'Fu Dai Lian Lian',
    volatility: 'Medium',
    cabinetType: 'Curved',
    releaseYear: 2020,
    rtpRanges: { min: 88, max: 94 },
    theme: 'Asian/Panda',
    bonusMechanics: ['Free Games', 'Progressive Jackpots', 'Multipliers'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Grand', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25'],
    apMetadata: {
      persistenceType: 'None',
      hasMustHitBy: false,
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'cashman',
    machineName: 'Cashman',
    manufacturer: 'Aristocrat',
    gameSeries: 'Cashman',
    volatility: 'Medium',
    cabinetType: 'Upright',
    releaseYear: 2019,
    rtpRanges: { min: 87, max: 92 },
    theme: 'Money/Cashman Character',
    bonusMechanics: ['Hold & Spin', 'Multipliers', 'Free Games'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      entryConditions: ['Multiple Cashman symbols visible'],
      recommendedBankroll: { min: 250, max: 800 },
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'wonder-4-tower',
    machineName: 'Wonder 4 Tower',
    manufacturer: 'Aristocrat',
    gameSeries: 'Wonder 4',
    volatility: 'Medium',
    cabinetType: 'Tower',
    releaseYear: 2020,
    rtpRanges: { min: 87, max: 92 },
    theme: 'Multi-Game',
    bonusMechanics: ['Free Games', 'Stacked Symbols', 'Multi-Game Selection'],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25'],
    apMetadata: {
      persistenceType: 'None',
      hasMustHitBy: false,
      notesAndTips: 'Popular multi-game cabinet but no AP features',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'fire-link-pillars',
    machineName: 'Fire Link - Pillars of Fire',
    manufacturer: 'Bally',
    gameSeries: 'Fire Link',
    volatility: 'High',
    cabinetType: 'Wide Screen',
    releaseYear: 2021,
    rtpRanges: { min: 85, max: 90 },
    theme: 'Fire/Ancient',
    bonusMechanics: ['Hold & Spin', 'Free Games', 'Progressive Jackpots'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Maxi', type: 'progressive' },
      { name: 'Mega', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.25'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      entryConditions: ['6+ fire symbols visible'],
      recommendedBankroll: { min: 500, max: 2000 },
      risks: ['High volatility', 'Rapid bankroll depletion possible'],
      notesAndTips: 'Count fire symbols carefully',
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
  {
    id: 'flaming-hot-pots-ms-wong',
    machineName: 'Flaming Hot Pots — Ms. Wong',
    manufacturer: 'Aristocrat',
    gameSeries: 'Flaming Hot Pots',
    volatility: 'High',
    cabinetType: 'Curved',
    releaseYear: 2022,
    rtpRanges: { min: 87, max: 92 },
    theme: 'Asian/Cooking',
    bonusMechanics: ['Pot Collection', 'Board Expansion', 'Stacked Wilds', 'Symbol Upgrades'],
    jackpotTypes: [
      { name: 'Mini', type: 'progressive' },
      { name: 'Minor', type: 'progressive' },
      { name: 'Major', type: 'progressive' },
      { name: 'Grand', type: 'progressive' },
    ],
    denominationFamilies: ['$0.01', '$0.02', '$0.05', '$0.10', '$1.00'],
    apMetadata: {
      persistenceType: 'True',
      hasMustHitBy: false,
      resetValues: {
        mini: 10,
        minor: 50,
        major: 600,
        grand: 8000,
      },
      entryConditions: [
        'Upsized pot nearly maxed (main trigger)',
        'Spicy pot moderately high AND Upsized mid-high (best EV)',
        'Major inflated 20-30% above reset',
        'Strawberry boards are paying multiples',
      ],
      exitConditions: [
        'Only Yummy pot inflated',
        'Post-jackpot resets',
        'High denoms with cold boards',
        'No strawberry hits for long streaks',
      ],
      recommendedBankroll: { min: 500, max: 2500 },
      notesAndTips: '1¢ for progressives, 2¢ for bonus-chasing. Higher volatility than Mr. Lee variant.',
    },
    detailedProfile: {
      jackpotResetValues: {
        mini: { min: 10, max: 18 },
        minor: { min: 50, max: 80 },
        major: { min: 600, max: 1200 },
        grand: { min: 8000, max: 12500 },
      },
      progressiveBehavior: {
        sharedAcrossBank: true,
        growthRate: 'Major grows noticeably faster on Ms. Wong than Mr. Lee',
        independentPots: true,
        notes: 'Grand is shared across all machines in the bank. Minis/Minors reset higher at 2¢+ denoms. Pot growth is independent and not correlated across machines.',
      },
      specialMechanics: {
        description: 'Ms. Wong uses Spicy strawberries with HIGHER weighting for Major and Minor adders compared to Mr. Lee variant.',
        triggers: ['Spicy strawberries', 'Upsized pot', 'Gold reel boost'],
        bonusFeatures: [
          'Upsized pot has even greater board expansion than Mr. Lee (one extra row possible)',
          'Base game includes stacked symbol upgrades, especially golden Ms. Wong symbols',
          'Gold reel boost increases bonus frequency and symbol upgrade chances',
          'Free spins can drop multiple stacked wild reels',
        ],
        symbolBehavior: 'Golden Ms. Wong symbols can fill multiple reels. Stacked wilds create board-wide multipliers.',
        bestCombos: [
          'Spicy + Upsized is the strongest combo',
          'Strawberry adders become explosive when paired with stacked wild boards',
        ],
      },
      bonusGameBehavior: {
        description: "Ms. Wong's bonuses favor big-symbol wins rather than multiplier line hits.",
        features: [
          'Upsized can produce full-board hits if enough adders appear',
          'Weighted board expansion makes Major strawberries significantly more valuable',
        ],
        volatilityNotes: 'Very High volatility - depends heavily on expanded symbols',
      },
      denominationBehavior: [
        { denom: '$0.01', notes: 'Best for AP and progressive chasing', recommendation: 'Best for AP' },
        { denom: '$0.02', notes: 'Sweet spot for bonus frequency vs. volatility', recommendation: 'Best overall' },
        { denom: '$0.05', notes: 'Enormous potential but brutal variance', recommendation: 'High risk' },
        { denom: '$0.10', notes: 'Enormous potential but brutal variance', recommendation: 'High risk' },
        { denom: '$1.00', notes: 'High-risk "jackpot-gambler" only', recommendation: 'Extreme risk' },
      ],
      apTriggers: {
        primary: [
          'Upsized pot nearly maxed',
          'Spicy pot moderately high AND Upsized mid-high (best EV)',
        ],
        secondary: [
          'Major inflated 20–30% above reset',
        ],
        visualClues: [
          'Strawberry boards are paying multiples (visual clue of someone feeding the pot)',
        ],
      },
      walkAwayConditions: {
        conditions: [
          'Only Yummy pot inflated',
          'Post-jackpot resets',
          'High denoms with cold boards',
          'No strawberry hits for long streaks',
        ],
      },
      bestDenominationForAP: '1¢ for progressives, 2¢ for bonus-chasing',
      cruiseShipNotes: {
        reelStripDifferences: 'Royal ships run Ms. Wong with slightly tighter reel strips than Mr. Lee',
        triggerFrequency: 'Upsized triggers slightly more often at sea',
        placement: 'These machines are usually placed deeper in the casino rather than at the entrance',
      },
      simpleSummary: "Ms. Wong's Flaming Hot Pots uses the same Yummy, Spicy, and Upsized pots as Mr. Lee, but the values and volatility are higher. Her Spicy strawberries have greater chances of landing Major and Minor adders, and the Upsized pot expands the bonus grid even more, allowing Major-value adders to flood the board. Jackpots reset around $10–18 (Mini), $50–80 (Minor), $600–1,200 (Major), and $8,000–12,500 (Grand). This machine becomes profitable for AP players when the Upsized pot is nearly full or when both the Spicy and Upsized pots are elevated together. The 1¢ denom is best for progressive chasing, while 2¢ gives better overall bonus performance. Avoid when only the Yummy pot is high or immediately after a pot-trigger event.",
    },
    source: 'global',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'system',
  },
];

export function searchSlotMachines(query: string, machines: SlotMachine[] = GLOBAL_SLOT_MACHINES): SlotMachine[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return machines;
  
  return machines.filter(machine => 
    machine.machineName.toLowerCase().includes(lowerQuery) ||
    machine.manufacturer.toLowerCase().includes(lowerQuery) ||
    (machine.gameSeries?.toLowerCase().includes(lowerQuery)) ||
    (machine.theme?.toLowerCase().includes(lowerQuery))
  );
}

export function filterSlotMachines(machines: SlotMachine[], filters: {
  manufacturers?: string[];
  volatility?: string[];
  persistenceType?: string[];
  hasMustHitBy?: boolean;
  hasAPPotential?: boolean;
}): SlotMachine[] {
  let filtered = [...machines];
  
  if (filters.manufacturers && filters.manufacturers.length > 0) {
    filtered = filtered.filter(m => filters.manufacturers!.includes(m.manufacturer));
  }
  
  if (filters.volatility && filters.volatility.length > 0) {
    filtered = filtered.filter(m => filters.volatility!.includes(m.volatility));
  }
  
  if (filters.persistenceType && filters.persistenceType.length > 0) {
    filtered = filtered.filter(m => 
      m.apMetadata && filters.persistenceType!.includes(m.apMetadata.persistenceType)
    );
  }
  
  if (filters.hasMustHitBy !== undefined) {
    filtered = filtered.filter(m => 
      m.apMetadata && m.apMetadata.hasMustHitBy === filters.hasMustHitBy
    );
  }
  
  if (filters.hasAPPotential) {
    filtered = filtered.filter(m => 
      m.apMetadata && (m.apMetadata.persistenceType !== 'None' || m.apMetadata.hasMustHitBy)
    );
  }
  
  return filtered;
}
