import type { AnnualCruiseBenefit, BookedCruise, CrownAnchorCruiseCertificate } from '@/types/models';
import type { Certificate } from '@/components/CertificateManagerModal';

export type BenefitCalendarKind='tier_boundary'|'retained_status'|'annual_reward'|'milestone'|'status_match'|'benefit_expiration'|'projected_tier'|'point_contribution';
export interface BenefitCalendarEvent{id:string;date:string;kind:BenefitCalendarKind;title:string;detail:string;source:'provider'|'user_entered'|'calculated'|'local_record';points?:number;cruiseId?:string;status?:string}
export interface BenefitCalendarAudit{events:BenefitCalendarEvent[];pointContributions:Array<{cruiseId:string;ship:string,date:string;points:number;source:string}>;contributionTotal:number;reportedCurrentYearPoints:number;unallocatedPoints:number;warnings:string[]}
type LoyaltySnapshot={clubRoyaleTier:string;clubRoyaleTierValidThrough:string|null;clubRoyaleTierIsProtected:boolean;clubRoyaleCurrentYearPoints:number;clubRoyaleSeasonStartDate?:Date;clubRoyaleNextResetDate:Date;clubRoyalePointsSource:string;mastersProgress:{projectedDate:Date|null};captainsClub:{tier:string|null;statusMatchTier:string|null;isStatusMatched:boolean}};
type ProfileSnapshot={clubRoyaleTierConfirmedAt?:string;loyaltyManualOverrideAt?:string};
const dateOnly=(value:unknown):string|null=>{if(value instanceof Date&&!Number.isNaN(value.getTime()))return value.toISOString().slice(0,10);if(typeof value!=='string'||!value.trim())return null;const match=value.match(/^\d{4}-\d{2}-\d{2}/);if(match)return match[0];const parsed=new Date(value);return Number.isNaN(parsed.getTime())?null:parsed.toISOString().slice(0,10)};
const pointsFor=(cruise:BookedCruise)=>{for(const value of[cruise.pointsEarned,cruise.earnedPoints,cruise.casinoPoints]){const parsed=Number(value);if(Number.isFinite(parsed)&&parsed>0)return parsed}return 0};
export function buildLoyaltyBenefitsCalendar(input:{loyalty:LoyaltySnapshot;profile?:ProfileSnapshot|null;cruises:BookedCruise[];certificates:Certificate[]}):BenefitCalendarAudit{
 const events:BenefitCalendarEvent[]=[];const add=(event:BenefitCalendarEvent)=>{if(dateOnly(event.date))events.push({...event,date:dateOnly(event.date)!})};const reset=dateOnly(input.loyalty.clubRoyaleNextResetDate);if(reset)add({id:'club-royale-reset',date:reset,kind:'tier_boundary',title:'Club Royale earning year resets',detail:'Current-year casino points reset at the program boundary; retained status is evaluated separately.',source:'calculated'});
 const valid=dateOnly(input.loyalty.clubRoyaleTierValidThrough);if(valid)add({id:'club-royale-valid-through',date:valid,kind:'retained_status',title:`${input.loyalty.clubRoyaleTier} status valid through`,detail:input.loyalty.clubRoyaleTierIsProtected?'Retained/grandfathered status is protected through this recorded date.':'Effective tier validity boundary.',source:'local_record'});
 const confirmed=dateOnly(input.profile?.clubRoyaleTierConfirmedAt??input.profile?.loyaltyManualOverrideAt);if(input.loyalty.captainsClub.isStatusMatched&&confirmed)add({id:'celebrity-status-match',date:confirmed,kind:'status_match',title:`Celebrity ${input.loyalty.captainsClub.tier??input.loyalty.captainsClub.statusMatchTier} status match`,detail:`Matched from Royal status; earned Celebrity tier remains independently auditable.`,source:'local_record'});
 const projected=dateOnly(input.loyalty.mastersProgress.projectedDate);if(projected)add({id:'masters-projection',date:projected,kind:'projected_tier',title:'Projected Club Royale Masters date',detail:'Projection based on saved point pace and booked cruises; not provider-confirmed.',source:'calculated'});
 const seasonStart=dateOnly(input.loyalty.clubRoyaleSeasonStartDate),seasonEnd=reset;const pointContributions=input.cruises.map(cruise=>({cruiseId:cruise.id,ship:cruise.shipName,date:cruise.returnDate||cruise.sailDate,points:pointsFor(cruise),source:String(cruise.sourceAuthority??cruise.calculationConfidence??'local_record')})).filter(row=>row.points>0&&(!seasonStart||row.date>=seasonStart)&&(!seasonEnd||row.date<seasonEnd));
 pointContributions.forEach(row=>add({id:`points-${row.cruiseId}`,date:row.date,kind:'point_contribution',title:`${row.points.toLocaleString()} points · ${row.ship}`,detail:`Exact saved contribution from this cruise. Source: ${row.source}.`,source:row.source==='provider'?'provider':row.source==='user_entered'?'user_entered':'local_record',points:row.points,cruiseId:row.cruiseId}));
 input.cruises.forEach(cruise=>{const dynamic=cruise as BookedCruise&{annualCruiseBenefits?:AnnualCruiseBenefit[];crownAnchorCertificates?:CrownAnchorCruiseCertificate[]};(dynamic.annualCruiseBenefits??[]).forEach(benefit=>{const date=benefit.sailByDate??benefit.bookByDate;if(date)add({id:`annual-${benefit.id}`,date,kind:benefit.status==='available'?'benefit_expiration':'annual_reward',title:`Club Royale ${benefit.tier} annual cruise`,detail:`${benefit.cabinEntitlement}, up to ${benefit.maxNights} nights · ${benefit.status}.`,source:'local_record',cruiseId:benefit.selectedCruiseId,status:benefit.status})});(dynamic.crownAnchorCertificates??[]).forEach(cert=>{if(cert.expirationDate)add({id:`milestone-${cert.id}`,date:cert.expirationDate,kind:'milestone',title:`${cert.triggerPoints.toLocaleString()}-point milestone certificate`,detail:`Status: ${cert.status}.`,source:'local_record',cruiseId:cert.selectedCruiseId,status:cert.status})})});
 input.certificates.filter(cert=>cert.expiryDate).forEach(cert=>add({id:`certificate-${cert.id}`,date:cert.expiryDate!,kind:'benefit_expiration',title:`Certificate expires: ${cert.certificateCode??cert.label}`,detail:`${cert.status} · recorded value $${Number(cert.value||0).toLocaleString()}.`,source:cert.parserSource==='manual'?'user_entered':'local_record',status:cert.status}));
 const contributionTotal=pointContributions.reduce((sum,row)=>sum+row.points,0),unallocatedPoints=input.loyalty.clubRoyaleCurrentYearPoints-contributionTotal,warnings:string[]=[];if(unallocatedPoints!==0)warnings.push(`${Math.abs(unallocatedPoints).toLocaleString()} current-year point${Math.abs(unallocatedPoints)===1?' is':'s are'} ${unallocatedPoints>0?'not allocated to a saved cruise':'above the reported current-year total'}.`);if(input.loyalty.captainsClub.isStatusMatched&&!confirmed)warnings.push('Celebrity status match is active, but no confirmation date is recorded, so it is listed in the audit rather than assigned an invented calendar date.');
 return{events:events.sort((a,b)=>a.date.localeCompare(b.date)),pointContributions,contributionTotal,reportedCurrentYearPoints:input.loyalty.clubRoyaleCurrentYearPoints,unallocatedPoints,warnings};
}
