import React, { useEffect, useRef } from 'react';
import { Animated, StyleSheet, Text, View } from 'react-native';
import { CheckCircle2 } from 'lucide-react-native';
import { EASY_SEAS_TOKENS as T } from '@/constants/easySeasDesignSystem';
import { useExperience } from '@/state/ExperienceProvider';

export function PurposefulSuccess({ label, reducedMotion }:{ label: string; reducedMotion?: boolean }) { const { preferences } = useExperience(); const effectiveReducedMotion = reducedMotion ?? preferences.reducedMotion; const opacity = useRef(new Animated.Value(effectiveReducedMotion ? 1 : 0)).current; const scale = useRef(new Animated.Value(effectiveReducedMotion ? 1 : .94)).current; useEffect(() => { if (effectiveReducedMotion) { opacity.setValue(1); scale.setValue(1); return; } const animation = Animated.parallel([Animated.timing(opacity, { toValue: 1, duration: T.motion.standard, useNativeDriver: true }), Animated.spring(scale, { toValue: 1, damping: 13, stiffness: 160, useNativeDriver: true })]); animation.start(); return () => animation.stop(); }, [label, opacity, effectiveReducedMotion, scale]); return <Animated.View style={[styles.success, { opacity, transform: [{ scale }] }]} accessibilityLiveRegion="polite"><CheckCircle2 color={T.color.success}/><Text style={styles.label}>{label}</Text></Animated.View>; }
export function AccessibleProgress({ progress, label, reducedMotion, color = T.color.teal }:{ progress: number; label: string; reducedMotion?: boolean; color?: string }) { const { preferences } = useExperience(); const effectiveReducedMotion = reducedMotion ?? preferences.reducedMotion; const width = useRef(new Animated.Value(0)).current; const bounded = Math.max(0, Math.min(1, progress)); useEffect(() => { const animation = Animated.timing(width, { toValue: bounded, duration: effectiveReducedMotion ? 0 : T.motion.progress, useNativeDriver: false }); animation.start(); return () => animation.stop(); }, [bounded, effectiveReducedMotion, width]); return <View accessibilityRole="progressbar" accessibilityValue={{ min: 0, max: 100, now: Math.round(bounded * 100), text: label }} accessibilityLiveRegion="polite"><View style={styles.track}><Animated.View style={[styles.fill, { backgroundColor: color, width: width.interpolate({ inputRange: [0, 1], outputRange: ['0%', '100%'] }) }]}/></View><Text style={styles.progressLabel}>{label} · {Math.round(bounded * 100)}%</Text></View>; }
const styles = StyleSheet.create({ success: { flexDirection: 'row', alignItems: 'center', gap: T.space.sm, minHeight: T.control.minimum, padding: T.space.md, borderRadius: T.radius.md, backgroundColor: '#E5F4EF' }, label: { flex: 1, color: '#225B4C', fontWeight: '800' }, track: { height: 9, borderRadius: 5, backgroundColor: T.color.border, overflow: 'hidden' }, fill: { height: 9, borderRadius: 5, backgroundColor: T.color.teal }, progressLabel: { color: T.color.muted, fontSize: T.type.caption, marginTop: 5 } });
