import React, { useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Stack, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ArrowLeft, CheckCircle2 } from 'lucide-react-native';
import { DARK_ROYAL_COLORS as C } from '@/constants/darkRoyalTheme';
import { useCoreData } from '@/state/CoreDataProvider';
import { useTax } from '@/state/TaxProvider';
import { buildPostCruiseCloseoutPatch, closeoutProgress, EMPTY_POST_CRUISE_CLOSEOUT, validatePostCruiseCloseout, type PostCruiseCloseoutInput } from '@/lib/casino/postCruiseCloseout';
import { buildPostCruiseScorecard } from '@/lib/voyage/postCruiseScorecard';
import { inferCasinoProgram } from '@/lib/casino/casinoProgramSeasons';

type TextCloseoutKey = Exclude<keyof PostCruiseCloseoutInput, 'handpaysIncludedInEndingCash' | 'slotPointsConfirmed'>;
const primaryFields: Array<[TextCloseoutKey,string,string]> = [['startingCash','Starting cash in','$200'],['endingCash','Ending cash out','$2,032'],['hoursPlayed','Total hours played','12.5'],['ratedGamingDays','Provider-rated gaming days','3'],['pointsEarned','Actual points earned','6,500'],['explicitCoinIn','Casino-reported coin-in (optional)','$0'],['handpays','Separate handpays (optional)','$0'],['certificateCode','Certificate earned','Code'],['certificateValue','Certificate value','$0']];
const additionalFields: Array<[TextCloseoutKey,string,string]> = [['folioCasinoCharges','Casino charges on folio','$0'],['hostComps','Host comps received','$0'],['offerUsedCode','Offer used','Offer code'],['taxesFeesActual','Actual taxes and fees','$0'],['satisfaction','Trip satisfaction (1–5)','1–5'],['notes','Closeout notes','What worked, what did not, and follow-up items']];
export default function PostCruiseCloseoutScreen(){
  const router=useRouter(); const { bookedCruises, updateBookedCruise }=useCoreData(); const { w2gRecords }=useTax();
  const completed=useMemo(()=>bookedCruises.filter(c=>c.returnDate < new Date().toISOString().slice(0,10)).sort((a,b)=>b.returnDate.localeCompare(a.returnDate)),[bookedCruises]);
  const [selectedId,setSelectedId]=useState(completed[0]?.id ?? ''); const [form,setForm]=useState<PostCruiseCloseoutInput>(EMPTY_POST_CRUISE_CLOSEOUT);
  const selected=completed.find(c=>c.id===selectedId); const linkedW2g=w2gRecords.filter(r=>r.cruiseId===selectedId); const progress=closeoutProgress(form); const errors=validatePostCruiseCloseout(form);
  const number=(value:string)=>{const parsed=Number(value.replace(/[$,]/g,''));return Number.isFinite(parsed)?parsed:0};
  const historicalPph=useMemo(()=>{if(!selected)return{rate:400,source:'conservative fallback'};const program=inferCasinoProgram(selected as unknown as Record<string,unknown>);const rows=completed.filter(c=>c.id!==selected.id&&inferCasinoProgram(c as unknown as Record<string,unknown>)===program&&Number(c.hoursPlayed)>0&&Number(c.pointsEarned??c.earnedPoints??c.casinoPoints)>0);const hours=rows.reduce((sum,c)=>sum+Number(c.hoursPlayed),0);const points=rows.reduce((sum,c)=>sum+Number(c.pointsEarned??c.earnedPoints??c.casinoPoints),0);return hours>0?{rate:points/hours,source:`personal history from ${rows.length} cruise(s)`}:{rate:400,source:'conservative fallback'}},[completed,selected]);
  const expectedPoints=Math.round(number(form.hoursPlayed)*historicalPph.rate); const actualPoints=number(form.pointsEarned); const starting=number(form.startingCash); const ending=number(form.endingCash); const separateHandpay=form.handpaysIncludedInEndingCash?0:number(form.handpays); const gamingResult=ending+separateHandpay-starting;
  const scorecard=selected?buildPostCruiseScorecard({totalCost:number(form.taxesFeesActual)+Number(selected.amountPaid??selected.pricePaid??selected.totalPrice??selected.price??0),compValue:number(form.hostComps)+number(form.certificateValue)+Number(selected.freePlay??0)+Number(selected.freeOBC??0),casinoNetResult:gamingResult,points:actualPoints,newOfferCount:form.certificateCode.trim()?1:0,portsVisited:selected.itinerary?.filter(day=>!day.isSeaDay).length??selected.ports?.length??0,cabinRating:number(form.satisfaction)||null,shipRating:number(form.satisfaction)||null,crewRecognitionCount:0,lessons:form.notes.trim()?[form.notes.trim()]:[]}):null;
  const save=()=>{ if(!selected)return; if(errors.length){Alert.alert('Review closeout',errors.join('\n'));return;} const expected=number(form.hoursPlayed)>0?{points:expectedPoints,pointsPerHour:historicalPph.rate,source:historicalPph.source}:undefined; const patch=buildPostCruiseCloseoutPatch(form,{count:linkedW2g.length,amount:linkedW2g.reduce((s,r)=>s+r.amount,0)},undefined,expected); updateBookedCruise(selected.id,patch); Alert.alert('Closeout saved','Cash result, hours, actual points, expected-points comparison, and certificate evidence now feed the Casino calculations.'); };
  return <View style={s.root}><Stack.Screen options={{headerShown:false}}/><SafeAreaView style={s.safe} edges={['top']}><View style={s.header}><TouchableOpacity onPress={()=>router.back()} style={s.back}><ArrowLeft size={20} color={C.gold}/></TouchableOpacity><View><Text style={s.title}>Post-Cruise Closeout</Text><Text style={s.sub}>Reconcile the facts before evaluating value</Text></View></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.cruises}>{completed.slice(0,12).map(c=><TouchableOpacity key={c.id} onPress={()=>setSelectedId(c.id)} style={[s.cruise,c.id===selectedId&&s.cruiseActive]}><Text style={[s.cruiseText,c.id===selectedId&&s.cruiseTextActive]}>{c.shipName}</Text><Text style={s.cruiseDate}>{c.returnDate}</Text></TouchableOpacity>)}</ScrollView>
    {!selected?<View style={s.card}><Text style={s.muted}>No completed cruise is available.</Text></View>:<><View style={s.progress}><View style={s.progressRow}><Text style={s.section}>Closeout progress</Text><Text style={s.percent}>{progress}%</Text></View><View style={s.track}><View style={[s.fill,{width:`${progress}%`}]} /></View><Text style={s.muted}>Blank fields remain explicitly unknown; zero means confirmed zero.</Text></View>
      <View style={s.card}><Text style={s.section}>One cruise play summary</Text><Text style={s.muted}>Enter one starting amount, one ending amount, total hours, and actual points. You do not need to log every session.</Text></View>
      {primaryFields.map(([key,label,placeholder])=><View key={key} style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput value={form[key]} onChangeText={value=>setForm(current=>({...current,[key]:value}))} placeholder={placeholder} placeholderTextColor={C.mutedText} keyboardType={key==='certificateCode'?'default':'decimal-pad'} style={s.input} testID={`closeout-${key}`}/></View>)}
      <TouchableOpacity style={s.toggle} onPress={()=>setForm(current=>({...current,slotPointsConfirmed:!current.slotPointsConfirmed}))}><View style={[s.check,form.slotPointsConfirmed&&s.checkActive]}><Text style={s.checkText}>{form.slotPointsConfirmed?'✓':''}</Text></View><View style={{flex:1}}><Text style={s.toggleText}>Club Royale points came from eligible slot play</Text><Text style={s.muted}>Required before Easy Seas may estimate coin-in as points × $5. Leave off for table play, mixed play, or unknown earning rules.</Text></View></TouchableOpacity>
      <TouchableOpacity style={s.toggle} onPress={()=>setForm(current=>({...current,handpaysIncludedInEndingCash:!current.handpaysIncludedInEndingCash}))}><View style={[s.check,form.handpaysIncludedInEndingCash&&s.checkActive]}><Text style={s.checkText}>{form.handpaysIncludedInEndingCash?'✓':''}</Text></View><Text style={s.toggleText}>Handpays are already included in ending cash</Text></TouchableOpacity>
      <View style={s.card}><Text style={s.section}>Live reconciliation</Text><Text style={s.value}>{gamingResult>=0?'+':''}${gamingResult.toLocaleString()} gaming result</Text><Text style={s.muted}>Ending cash + separate handpays − starting cash. Cruise fare is excluded.</Text><Text style={s.value}>{expectedPoints.toLocaleString()} expected points</Text><Text style={s.muted}>{historicalPph.rate.toFixed(1)} points/hour from {historicalPph.source}. Actual {actualPoints.toLocaleString()} · difference {(actualPoints-expectedPoints).toLocaleString()}. This is an estimate, not a provider rating statement.</Text></View>
      {additionalFields.map(([key,label,placeholder])=><View key={key} style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput value={form[key]} onChangeText={value=>setForm(current=>({...current,[key]:value}))} placeholder={placeholder} placeholderTextColor={C.mutedText} keyboardType={key==='offerUsedCode'||key==='notes'?'default':'decimal-pad'} multiline={key==='notes'} style={[s.input,key==='notes'&&s.notes]} testID={`closeout-${key}`}/></View>)}
      <View style={s.card}><Text style={s.section}>Linked W-2Gs</Text><Text style={s.value}>{linkedW2g.length} record{linkedW2g.length===1?'':'s'} · ${linkedW2g.reduce((sum,row)=>sum+row.amount,0).toLocaleString()}</Text><Text style={s.muted}>W-2Gs remain in the tax ledger and are linked here by cruise ID.</Text></View>
      {scorecard?<View style={s.card}><Text style={s.section}>Sailing scorecard preview</Text><Text style={s.value}>{scorecard.experienceScore??'—'}/100 experience · {scorecard.netEconomicValue.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})} net value</Text><Text style={s.muted}>{scorecard.summary}</Text><Text style={s.muted}>{scorecard.points??0} points · {scorecard.portsVisited??0} ports · {scorecard.newOfferCount??0} new offers/certificates · comp recovery {scorecard.valueRecoveryPercent==null?'—':`${scorecard.valueRecoveryPercent.toFixed(0)}%`}</Text></View>:null}
      <TouchableOpacity onPress={save} style={s.save} testID="post-cruise-closeout-save"><CheckCircle2 size={18} color={C.deepNavy}/><Text style={s.saveText}>Complete and Save Closeout</Text></TouchableOpacity></>}
  </ScrollView></SafeAreaView></View>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:C.background},safe:{flex:1},header:{flexDirection:'row',alignItems:'center',gap:10,padding:16},back:{width:38,height:38,borderRadius:19,backgroundColor:'rgba(255,255,255,.08)',alignItems:'center',justifyContent:'center'},title:{color:C.textPrimary,fontSize:18,fontWeight:'900'},sub:{color:C.mutedText,fontSize:11},content:{padding:16,paddingBottom:70},cruises:{gap:8,paddingBottom:12},cruise:{padding:10,borderRadius:12,backgroundColor:C.card,borderWidth:1,borderColor:C.border,minWidth:150},cruiseActive:{backgroundColor:C.gold,borderColor:C.gold},cruiseText:{color:C.textPrimary,fontSize:12,fontWeight:'800'},cruiseTextActive:{color:C.deepNavy},cruiseDate:{color:C.mutedText,fontSize:10,marginTop:3},progress:{backgroundColor:C.cardAlt,borderRadius:14,padding:14,marginBottom:12},progressRow:{flexDirection:'row',justifyContent:'space-between'},section:{color:C.gold,fontSize:11,fontWeight:'900',textTransform:'uppercase'},percent:{color:C.textPrimary,fontWeight:'900'},track:{height:7,borderRadius:4,backgroundColor:'rgba(255,255,255,.12)',marginVertical:8},fill:{height:7,borderRadius:4,backgroundColor:C.gold},muted:{color:C.mutedText,fontSize:11,lineHeight:16},field:{marginBottom:11},fieldLabel:{color:C.textSecondary,fontSize:11,fontWeight:'800',marginBottom:5},input:{backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:12,color:C.textPrimary,padding:12,minHeight:46},notes:{minHeight:90,textAlignVertical:'top'},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:14,padding:14,marginBottom:12},value:{color:C.textPrimary,fontSize:18,fontWeight:'900',marginVertical:5},toggle:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:12},check:{width:24,height:24,borderRadius:6,borderWidth:1,borderColor:C.border,alignItems:'center',justifyContent:'center'},checkActive:{backgroundColor:C.gold,borderColor:C.gold},checkText:{color:C.deepNavy,fontWeight:'900'},toggleText:{color:C.textSecondary,fontSize:12,fontWeight:'700'},save:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,backgroundColor:C.gold,borderRadius:14,padding:15},saveText:{color:C.deepNavy,fontWeight:'900'}});
