services:
  - type: web
    name: easy-seas-backend-v2
    env: node
    buildCommand: bun install
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EASY_SEAS_DATA_DIR
        value: /data
