import{stableModelFingerprint}from'../models/statistics';import type{GenerateOptimizationAlertsInput,PersonalOptimizationAlert,PersonalOptimizationAlertSeverity,PersonalOptimizationAlertType}from'./types';
function make(input:GenerateOptimizationAlertsInput,type:PersonalOptimizationAlertType,severity:PersonalOptimizationAlertSeverity,title:string,message:string,reasons:string[],pressureSensitive=false):PersonalOptimizationAlert{const b=input.currentBundle,r=b.currentRecommendation,cruise=b.liveState?.cruiseId??null,state=b.liveAdvisor?.stateFingerprint??null,dedupeKey=[b.ownerProfileId,cruise,type,r?.id??state??b.generatedAt].join(':');const fingerprint=stableModelFingerprint([dedupeKey,title,message]);return{id:`personal-optimization-alert:${fingerprint}`,fingerprint,ownerProfileId:b.ownerProfileId,cruiseId:cruise,createdAt:b.generatedAt,type,severity,title,message,recommendationId:r?.id??null,stateFingerprint:state,drillDownRoute:'/casino/live-certificate-advisor',dedupeKey,pressureSensitive,acknowledged:false,dismissedAt:null,reasons,warnings:[]}}
export function generatePersonalOptimizationAlerts(input:GenerateOptimizationAlertsInput):PersonalOptimizationAlert[]{const b=input.currentBundle,r=b.currentRecommendation,d=b.dashboard,live=b.liveState,prev=input.previousBundle?.currentRecommendation??null;const alerts:PersonalOptimizationAlert[]=[];if(!r)return alerts;
if(live&&d?.averageCertificatePoints!==null&&d?.averageCertificatePoints!==undefined&&live.currentPoints>d.averageCertificatePoints)alerts.push(make(input,'points-above-average','info','Points exceed your personal average',`${live.currentPoints.toLocaleString()} points is above your historical average certificate level of ${d.averageCertificatePoints.toLocaleString()}.`,['Uses the current live points and saved personal dashboard.']));
const historyChart=d?.charts.find(c=>c.id==='certificate-history');const priorBest=historyChart?.points.length?Math.max(...historyChart.points.map(p=>p.y)):null;const projected=b.liveAdvisor?.endOfCruiseProjection.expectedPoints??null;if(priorBest!==null&&projected!==null&&projected>priorBest)alerts.push(make(input,'personal-best-likely','info','A personal point best is possible',`Your current projection is ${projected.toLocaleString()} points versus a prior best of ${priorBest.toLocaleString()}.`,['Projection is not a guarantee.']));
const priorEv=prev?.riskAdjustedIncrementalExpectedValue??null;const ev=r.riskAdjustedIncrementalExpectedValue;if(priorEv!==null&&priorEv<=0&&ev>0&&r.recommendedTargetPoints!==null)alerts.push(make(input,'incremental-ev-positive','opportunity','The next certificate became positive EV',`The saved risk-adjusted incremental EV is now $${ev.toFixed(0)} within current safety limits. Continuing is optional, not required.`,['Generated only on a nonpositive-to-positive EV transition.'],true));
if(priorEv!==null&&priorEv>=0&&ev<0)alerts.push(make(input,'incremental-ev-negative','warning','The next certificate is no longer worth chasing',`Risk-adjusted incremental EV fell to $${ev.toFixed(0)}. EasySeas recommends protecting vacation value.`,['Generated only when EV crosses from nonnegative to negative.']));
if(['STOP_NOW','BANK_YOUR_WIN','DO_NOT_CHASE','HARD_STOP'].includes(r.action))alerts.push(make(input,'optimal-stopping-point',r.action==='HARD_STOP'?'critical':'warning','Current certificate is the optimal stopping point',r.actionLabel,r.topReasons));
if(live?.remainingBankroll!==null&&r.expectedAdditionalLoss>live.remainingBankroll)alerts.push(make(input,'bankroll-risk','critical','Expected loss exceeds remaining bankroll',`Expected additional loss of $${r.expectedAdditionalLoss.toFixed(0)} exceeds the $${live.remainingBankroll.toFixed(0)} remaining bankroll.`,['Bankroll safety gate takes precedence.']));
if(r.downsideRange&&live?.remainingBankroll!==null&&r.downsideRange.high>live.remainingBankroll)alerts.push(make(input,'downside-risk','warning','Downside risk is excessive',`High downside estimate of $${r.downsideRange.high.toFixed(0)} exceeds remaining bankroll.`,['Uses the saved downside range.']));
if(r.drillDown.fatiguePerformanceAssessment.penalty>0)alerts.push(make(input,'fatigue-risk','warning','Fatigue or performance risk increased',r.drillDown.fatiguePerformanceAssessment.triggeredSignals.join(' '),['Fatigue warning can be corrected or dismissed, but hard loss gates remain.']));
if(r.drillDown.fatiguePerformanceAssessment.triggeredSignals.some(x=>x.toLowerCase().includes('points-per-hour pace')))alerts.push(make(input,'pace-deterioration','warning','Point pace has deteriorated',`Current point pace is materially below your personal baseline.`,['Pace deterioration reduces risk-adjusted EV.']));
if(b.liveAdvisor?.stale)alerts.push(make(input,'data-stale','warning','Live casino data is stale','Refresh points, result, remaining time, and bankroll before relying on the recommendation.',['Stale data cannot increase confidence.']));
const existing=new Set((input.existingAlerts??[]).map(a=>a.fingerprint));const seen=new Set();return alerts.filter(a=>{if(existing.has(a.fingerprint)||seen.has(a.fingerprint))return false;seen.add(a.fingerprint);return true});}
