import type { AskAllOffersOwnerScope, ConversationScopeSnapshot, ConversationSourceReference } from '@/lib/askAllOffers/types';
import { buildAskAllOffersOwnerKey } from '@/lib/askAllOffers/storage';
export const ASK_ALL_OFFERS_CONTEXT_VERSION='v1.0.0-all-active-offer-sources';
const text=(v:unknown)=>v==null?'':String(v).trim();
function dateIsPast(v:unknown):boolean{const raw=text(v);if(!raw)return false;const d=new Date(raw.includes('T')?raw:`${raw}T12:00:00`);return!Number.isNaN(d.getTime())&&d.getTime()<Date.now();}
function searchable(r:any):string{return[r?.offerCode,r?.code,r?.offerName,r?.name,r?.shipName,r?.ship,r?.sailDate,r?.itinerary,r?.destination,r?.category,r?.cabinType,r?.roomType,r?.perks,r?.guestsInfo,r?.certificateCode].map(text).join(' ').toLowerCase();}
const terms=(q:string)=>q.toLowerCase().split(/[^a-z0-9]+/).filter(t=>t.length>=3);
const relevance=(r:any,t:string[])=>t.reduce((n,x)=>n+(searchable(r).includes(x)?1:0),0);
function money(v:unknown):string|null{const n=typeof v==='number'?v:Number(String(v??'').replace(/[$,]/g,''));return Number.isFinite(n)&&n!==0?`$${n.toLocaleString()}`:null;}
function offerDetail(r:any):string{return[text(r.shipName??r.ship),text(r.sailDate),text(r.itinerary??r.destination),text(r.cabinType??r.roomType??r.category),text(r.guestsInfo),money(r.tradeInValue??r.tradeValue??r.value)].filter(Boolean).join(' · ')||'Saved offer record';}
export function buildAllOffersScopeSnapshot(input:{ownerScope:AskAllOffersOwnerScope;offers:any[];bookedCruises:any[];certificates:any[];cruises:any[]}):ConversationScopeSnapshot{const ownerKey=buildAskAllOffersOwnerKey(input.ownerScope);const bookedOfferRecords=input.bookedCruises.filter(r=>Boolean(r?.offerCode||r?.offerName||r?.sourcePayload)).length;const staleRows=input.offers.filter(r=>dateIsPast(r?.offerExpiryDate??r?.expires??r?.expirationDate)).length;return{ownerKey,profileId:input.ownerScope.profileId,brand:input.ownerScope.brand,program:input.ownerScope.program,generatedAt:new Date().toISOString(),activeOfferRows:input.offers.length+bookedOfferRecords,standaloneOffers:input.offers.length,bookedOfferRecords,certificateRecords:input.certificates.length,cruiseRecords:input.cruises.length+input.bookedCruises.length,sourceFreshness:input.offers.length===0?'unknown':staleRows===0?'current':staleRows===input.offers.length?'stale':'mixed'};}
export function buildAllOffersSourceReferences(input:{question:string;offers:any[];bookedCruises:any[];certificates:any[];cruises:any[];maxSources?:number}):ConversationSourceReference[]{const q=terms(input.question);const c:Array<{score:number;ref:ConversationSourceReference}>=[];input.offers.forEach((r,i)=>{const code=text(r.offerCode??r.code)||`Offer ${i+1}`;const expired=dateIsPast(r.offerExpiryDate??r.expires??r.expirationDate);c.push({score:relevance(r,q)+4,ref:{id:`offer:${code}:${text(r.shipName??r.ship)}:${text(r.sailDate)}:${i}`,sourceType:'offer',label:`${code}${text(r.offerName??r.name)?` — ${text(r.offerName??r.name)}`:''}`,detail:offerDetail(r),evidenceKind:expired?'stale':'fact',route:r.id?`/offer-details?id=${encodeURIComponent(String(r.id))}`:'/(tabs)/(overview)'}});});input.bookedCruises.filter(r=>Boolean(r?.offerCode||r?.offerName||r?.sourcePayload)).forEach((r,i)=>c.push({score:relevance(r,q)+3,ref:{id:`booked:${text(r.id)}:${i}`,sourceType:'booked-offer',label:`${text(r.offerCode)||'Booked offer'} attached to ${text(r.shipName)||'booked cruise'}`,detail:offerDetail(r),evidenceKind:'fact',route:r.id?`/cruise-details?id=${encodeURIComponent(String(r.id))}`:'/(tabs)/booked'}}));input.certificates.forEach((r,i)=>{const code=text(r.certificateCode??r.code)||`Certificate ${i+1}`;c.push({score:relevance(r,q)+2,ref:{id:`certificate:${code}:${i}`,sourceType:'certificate',label:code,detail:[text(r.status),text(r.points?`${r.points} points`:''),text(r.sailingsFound?`${r.sailingsFound} sailings`:'')].filter(Boolean).join(' · ')||'Saved certificate record',evidenceKind:r.status==='parsed'?'fact':r.status==='parse_failed'?'missing':'estimated',route:'/certificate-codes'}});});if(c.length===0)return[{id:'system:no-offers',sourceType:'system',label:'No offer sources loaded',detail:'Sync Royal/Celebrity, Carnival, or certificates before relying on an all-offers comparison.',evidenceKind:'missing',route:'/(tabs)/settings'}];return c.sort((a,b)=>b.score-a.score||a.ref.label.localeCompare(b.ref.label)).slice(0,input.maxSources??8).map(x=>x.ref);}
export function buildAllOffersPrompt(question:string,snapshot:ConversationScopeSnapshot):string{return['Ask all offers:',question.trim(),' ',`Authoritative scope snapshot: ${snapshot.profileId} / ${snapshot.brand} / ${snapshot.program}.`,`Loaded sources: ${snapshot.standaloneOffers} standalone offer-sailing rows, ${snapshot.bookedOfferRecords} booked offer records, ${snapshot.certificateRecords} certificate records, and ${snapshot.cruiseRecords} cruise records.`,`Source freshness: ${snapshot.sourceFreshness}.`,'Answer from every active material offer variant in the selected profile scope. Keep cabin, guest, price, perk, received, expiration, trade-in, certificate, and booked-offer distinctions. Label facts, calculations, estimates, missing data, and stale data. Never invent a sailing or value, and do not replace standalone offer inventory with booked or completed cruises.'].join('\n');}
