import type { AskAllOffersOwnerScope, ConversationThread } from '@/lib/askAllOffers/types';
import { quotaSafeGetJsonItem, quotaSafeSetJsonItem } from '../storage/quotaSafeStorage';

async function coordinatedGetJson<T>(key: string, fallback: T): Promise<T> { return quotaSafeGetJsonItem<T>(key, fallback); }
async function coordinatedSetJson(key: string, value: unknown): Promise<void> { await quotaSafeSetJsonItem(key, value); }
export const ASK_ALL_OFFERS_STORAGE_VERSION = 'v1.0.0-local-profile-isolation';
const STORAGE_PREFIX='easyseas.ask-all-offers.threads.v1';
function hashOwner(value:string):string{let hash=2166136261;for(let i=0;i<value.length;i+=1){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(16).padStart(8,'0');}
export function buildAskAllOffersOwnerKey(scope:AskAllOffersOwnerScope):string{return hashOwner([String(scope.authenticatedEmail??'anonymous').trim().toLowerCase(),String(scope.profileId||'all').trim().toLowerCase(),String(scope.brand||'all').trim().toLowerCase(),String(scope.program||'all').trim().toLowerCase()].join('|'));}
const storageKey=(ownerKey:string)=>`${STORAGE_PREFIX}.${ownerKey}`;
function normalizeThread(value:any):ConversationThread|null{if(!value||typeof value!=='object'||typeof value.id!=='string')return null;return{id:value.id,title:typeof value.title==='string'&&value.title.trim()?value.title.trim():'Offer conversation',createdAt:typeof value.createdAt==='string'?value.createdAt:new Date().toISOString(),updatedAt:typeof value.updatedAt==='string'?value.updatedAt:new Date().toISOString(),archivedAt:typeof value.archivedAt==='string'?value.archivedAt:null,scope:value.scope,messages:Array.isArray(value.messages)?value.messages:[],lastQuestion:typeof value.lastQuestion==='string'?value.lastQuestion:null};}
export async function loadConversationThreads(ownerKey:string):Promise<ConversationThread[]>{const parsed=await coordinatedGetJson<unknown[]>(storageKey(ownerKey),[]);return parsed.map(normalizeThread).filter((item):item is ConversationThread=>Boolean(item)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}
export async function saveConversationThreads(ownerKey:string,threads:ConversationThread[]):Promise<void>{await coordinatedSetJson(storageKey(ownerKey),threads.filter(t=>t.scope?.ownerKey===ownerKey));}
export async function upsertConversationThread(ownerKey:string,thread:ConversationThread):Promise<ConversationThread[]>{if(thread.scope.ownerKey!==ownerKey)throw new Error('Conversation owner mismatch');const threads=await loadConversationThreads(ownerKey);const next=[thread,...threads.filter(t=>t.id!==thread.id)].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));await saveConversationThreads(ownerKey,next);return next;}
export async function renameConversationThread(ownerKey:string,threadId:string,title:string):Promise<ConversationThread[]>{const threads=await loadConversationThreads(ownerKey);const next=threads.map(t=>t.id===threadId?{...t,title:title.trim()||t.title,updatedAt:new Date().toISOString()}:t);await saveConversationThreads(ownerKey,next);return next;}
export async function archiveConversationThread(ownerKey:string,threadId:string,archived:boolean):Promise<ConversationThread[]>{const threads=await loadConversationThreads(ownerKey);const next=threads.map(t=>t.id===threadId?{...t,archivedAt:archived?new Date().toISOString():null,updatedAt:new Date().toISOString()}:t);await saveConversationThreads(ownerKey,next);return next;}
export async function deleteConversationThread(ownerKey:string,threadId:string):Promise<ConversationThread[]>{const next=(await loadConversationThreads(ownerKey)).filter(t=>t.id!==threadId);await saveConversationThreads(ownerKey,next);return next;}
