import { buildStructuredOptimizationContext } from './buildOptimizationContext';import type{OptimizationQuestionAnswer,OptimizationQuestionIntent,OptimizationSnapshotBundle}from'./types';
function intent(q:string):OptimizationQuestionIntent{const s=q.toLowerCase();if(/ignore|override|bypass/.test(s)&&/bankroll|limit|stop|safety/.test(s))return'safety-override';if(/why|explain|reason/.test(s))return'why';if(/probability|chance|likely|success/.test(s))return'success-probability';if(/cost|loss|coin.?in|how much/.test(s))return'expected-cost';if(/history|past|historical/.test(s))return'history';if(/profile|average|favorite|best|worst/.test(s))return'profile';if(/target|certificate|stop|continue|chase/.test(s))return'current-target';return'general'}
export function answerPersonalOptimizationQuestion(query:string,bundle:OptimizationSnapshotBundle):OptimizationQuestionAnswer{const c=buildStructuredOptimizationContext(bundle),i=intent(query),r=bundle.currentRecommendation;let headline='Personal certificate optimization';let answer='EasySeas does not have enough saved optimization data to answer this yet.';let denied=false;
if(i==='safety-override'){headline='Safety limits cannot be overridden by chat';answer='Chat can explain or correct source data, but it cannot bypass bankroll, hard-loss, profit-floor, fatigue, or data-quality gates. Update the underlying verified settings instead.';denied=true;}
else if(r&&i==='current-target'){headline=r.actionLabel;answer=r.recommendedTargetPoints===null?`Your current certificate is the recommended stopping point at ${r.currentPoints.toLocaleString()} points.`:`The saved recommendation is ${r.actionLabel.toLowerCase()} at ${r.recommendedTargetPoints.toLocaleString()} points.`;}
else if(r&&i==='expected-cost'){headline='Expected additional cost';answer=`The personal model estimates $${r.expectedAdditionalLoss.toFixed(0)} of additional gambling loss and $${r.expectedAdditionalCoinIn.toFixed(0)} of additional coin-in for the selected target. Coin-in is wagering volume, not expected loss.`;}
else if(r&&i==='success-probability'){headline='Personal success probability';answer=r.probabilityOfSuccess===null?'Success probability is unavailable because comparable personal history is incomplete.':`The saved personal estimate is ${(r.probabilityOfSuccess*100).toFixed(1)}%, with ${r.confidence} confidence.`;}
else if(r&&i==='why'){headline=`Why EasySeas says “${r.actionLabel}”`;answer=[...r.topReasons,...r.drillDown.safetyOverrides].filter(Boolean).slice(0,5).join(' ');}
else if(i==='history'&&bundle.dashboard){headline='Historical evidence';answer=`The model maturity is ${bundle.dashboard.modelMaturity}. Your average certificate is ${bundle.dashboard.averageCertificatePoints?.toLocaleString()??'not yet known'} points, and the saved highest-EV certificate is ${bundle.dashboard.highestExpectedValueCertificateCode??'not yet known'}.`;}
else if(i==='profile'&&bundle.dashboard){headline='Personal gambling profile';answer=`Average bankroll: ${bundle.dashboard.averageBankroll===null?'unknown':`$${bundle.dashboard.averageBankroll.toFixed(0)}`}. Average win: ${bundle.dashboard.averageGamblingWin===null?'unknown':`$${bundle.dashboard.averageGamblingWin.toFixed(0)}`}. Average loss: ${bundle.dashboard.averageGamblingLoss===null?'unknown':`$${bundle.dashboard.averageGamblingLoss.toFixed(0)}`}.`;}
else if(r){headline=r.actionLabel;answer=`The current saved recommendation is ${r.actionLabel}. Ask about target, expected cost, success probability, historical evidence, or why the engine stopped or continued.`;}
return{intent:i,headline,answer,facts:c.facts,estimates:c.estimates,assumptions:c.assumptions,missingData:c.missingData,warnings:c.warnings,safetyGateOverrideDenied:denied,recommendationId:c.recommendationId};}
