import type { OptimizationContextItem, OptimizationSnapshotBundle, StructuredOptimizationContext } from './types';
function item(label:string,value:string,source:string,confidence:OptimizationContextItem['confidence']):OptimizationContextItem{return{label,value,source,confidence}}
export function buildStructuredOptimizationContext(bundle: OptimizationSnapshotBundle): StructuredOptimizationContext {
  const rec=bundle.currentRecommendation;const d=bundle.dashboard;const live=bundle.liveState;const facts:OptimizationContextItem[]=[];const estimates:OptimizationContextItem[]=[];const missing:string[]=[];
  if(live){facts.push(item('Current points',live.currentPoints.toLocaleString(),'Live casino state','high'));facts.push(item('Current casino result',`${live.currentResult>=0?'+':''}$${live.currentResult.toFixed(0)}`,'Live casino state','high'));if(live.remainingBankroll!==null)facts.push(item('Remaining bankroll',`$${live.remainingBankroll.toFixed(0)}`,'Live casino state','high'));else missing.push('Remaining bankroll');}
  else missing.push('Live casino state');
  if(rec){facts.push(item('Recommendation',rec.actionLabel,'Saved recommendation snapshot',rec.confidence));if(rec.currentLockedThresholdPoints!==null)facts.push(item('Locked certificate',rec.currentLockedThresholdPoints.toLocaleString(),'Saved recommendation snapshot',rec.confidence));if(rec.recommendedTargetPoints!==null)estimates.push(item('Recommended target',rec.recommendedTargetPoints.toLocaleString(),'Personal optimization engine',rec.confidence));estimates.push(item('Expected additional loss',`$${rec.expectedAdditionalLoss.toFixed(0)}`,'Personal loss model',rec.confidence));if(rec.probabilityOfSuccess!==null)estimates.push(item('Success probability',`${(rec.probabilityOfSuccess*100).toFixed(1)}%`,'Personal success model',rec.confidence));estimates.push(item('Risk-adjusted incremental EV',`$${rec.riskAdjustedIncrementalExpectedValue.toFixed(0)}`,'Personal optimization engine',rec.confidence));}
  else missing.push('Current recommendation snapshot');
  if(d){if(d.averageBankroll!==null)facts.push(item('Historical average bankroll',`$${d.averageBankroll.toFixed(0)}`,'Canonical casino history',d.modelMaturity==='established'?'high':'medium'));if(d.favoriteCertificateCode)facts.push(item('Favorite certificate',d.favoriteCertificateCode,'Canonical casino history','medium'));}
  else missing.push('Personal gambling dashboard');
  return{ownerProfileId:bundle.ownerProfileId,generatedAt:bundle.generatedAt,recommendationId:rec?.id??null,facts,estimates,assumptions:rec?.assumptions??[],missingData:missing,warnings:[...new Set([...bundle.warnings,...(rec?.warnings??[])])],sourceFreshness:bundle.sourceFreshness};
}
