export type RecordKind='cruise'|'booking'|'offer'|'certificate'|'sailing'|'host'|'crew'|'machine'|'receipt'|'invoice'|'port'|'agent_history';
export interface OperatingRecord{id:string;kind:RecordKind;ownerId?:string;brand?:string;date?:string;ship?:string;port?:string;cabin?:string;guests?:number;status?:string;source?:string;title:string;text:string;route:string;updatedAt?:string}
const norm=(v:unknown)=>String(v??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const aliases:Record<string,string[]>= {rcl:['royal caribbean','royal'],rccl:['royal caribbean','royal'],x:['celebrity'],cococay:['perfect day'],ots:['of the seas']};
export function buildSearchIndex(records:OperatingRecord[]){return records.map(record=>{let text=norm(`${record.title} ${record.text} ${record.ship} ${record.port} ${record.cabin} ${record.brand} ${record.id}`);Object.entries(aliases).forEach(([alias,values])=>{if(values.some(value=>text.includes(norm(value))))text+=` ${alias}`});return{record,text}})}
export function searchOperatingIndex(index:ReturnType<typeof buildSearchIndex>,query:string,filters:Partial<Pick<OperatingRecord,'kind'|'ownerId'|'brand'|'ship'|'port'|'cabin'|'guests'|'status'|'source'>>&{dateFrom?:string;dateTo?:string}={}){const terms=norm(query).split(' ').filter(Boolean);const rows=index.filter(({record,text})=>terms.every(term=>text.includes(term))&&Object.entries(filters).every(([key,value])=>value==null||key==='dateFrom'||key==='dateTo'||norm((record as any)[key])===norm(value))&&(!filters.dateFrom||String(record.date??'')>=filters.dateFrom)&&(!filters.dateTo||String(record.date??'')<=filters.dateTo)).map(({record,text})=>({...record,highlights:terms.filter(term=>text.includes(term))}));return{rows,counts:rows.reduce((out,row)=>(out[row.kind]=(out[row.kind]??0)+1,out),{}as Record<string,number>)} }

export interface ActionCandidate{id:string;type:string;title:string;route:string;urgency:number;value:number;confidence:number;ownerId:string;deadline?:string;evidenceFingerprint:string}
export interface ActionDecision{id:string;status:'dismissed'|'snoozed'|'completed';evidenceFingerprint:string;snoozedUntil?:string}
export function prioritizeActions(candidates:ActionCandidate[],decisions:ActionDecision[],now=new Date().toISOString()){const decision=new Map(decisions.map(row=>[row.id,row]));const visible=candidates.filter(row=>{const prior=decision.get(row.id);if(!prior)return true;if(prior.evidenceFingerprint!==row.evidenceFingerprint)return true;if(prior.status==='snoozed'&&prior.snoozedUntil&&prior.snoozedUntil<=now)return true;return false}).sort((a,b)=>(b.urgency*4+b.value*2+b.confidence)-(a.urgency*4+a.value*2+a.confidence));return{primary:visible.slice(0,5),remainder:visible.slice(5)}}

export type RelationshipConfidence='exact'|'inferred'|'estimated'|'unresolved';export interface RelationshipEdge{id:string;from:string;to:string;kind:string;confidence:RelationshipConfidence;evidenceIds:string[];ambiguousSharedCode?:boolean}
export function buildRelationshipGraph(records:OperatingRecord[],edges:RelationshipEdge[]){const ids=new Set(records.map(r=>r.id));const safe=edges.map(edge=>edge.ambiguousSharedCode?{...edge,confidence:'unresolved' as const}:edge).filter(edge=>ids.has(edge.from)&&ids.has(edge.to));return{nodes:records,edges:safe,traceFrom:(id:string)=>safe.filter(e=>e.from===id||e.to===id),correct:(id:string,confidence:RelationshipConfidence)=>safe.map(e=>e.id===id?{...e,confidence}:e)}}

export interface InboxIssue{id:string;dedupeKey:string;type:string;priority:number;deadline?:string;ownerId:string;source:string;status:'open'|'snoozed'|'resolved';route:string;sourceRecordId?:string;observedAt?:string;confidence?:'high'|'medium'|'low';formula?:string|null;details?:string}
export function reconcileInbox(issues:InboxIssue[]){const map=new Map<string,InboxIssue>();issues.forEach(issue=>{const current=map.get(issue.dedupeKey);if(!current||issue.priority>current.priority)map.set(issue.dedupeKey,issue)});const rows=[...map.values()].sort((a,b)=>b.priority-a.priority);return{rows,openCount:rows.filter(r=>r.status==='open').length,bulk:(ids:string[],status:InboxIssue['status'],ownerId?:string)=>rows.map(row=>ids.includes(row.id)?{...row,status,ownerId:ownerId??row.ownerId}:row)}}

export type WidgetSize='small'|'medium'|'large';export interface WidgetLayout{id:string;hidden:boolean;size:WidgetSize;order:number}
export const HOME_PRESETS:Record<string,string[]>={Cruiser:['next-cruise','weather','documents','calendar'],CasinoPlayer:['casino-pace','certificates','bankroll','next-cruise'],CasinoHost:['action-inbox','host-followups','player-value','trips'],TravelPlanner:['timeline','payments','weather','documents'],Minimal:['next-cruise','action-inbox']};
export function applyHomePreset(name:keyof typeof HOME_PRESETS,available:string[]){const selected=HOME_PRESETS[name];return available.map((id,index)=>({id,hidden:!selected.includes(id),size:'medium' as const,order:selected.indexOf(id)>=0?selected.indexOf(id):selected.length+index}))}

export interface SavedWatchlist{id:string;ownerId:string;description:string;query:string;filters:Record<string,unknown>;paused:boolean;lastMatchIds:string[]}
export function reevaluateWatchlist(list:SavedWatchlist,matches:OperatingRecord[]){const next=matches.map(r=>r.id),old=new Set(list.lastMatchIds),current=new Set(next);return{updated:{...list,lastMatchIds:next},added:next.filter(id=>!old.has(id)),removed:list.lastMatchIds.filter(id=>!current.has(id)),notify:!list.paused&&(next.some(id=>!old.has(id))||list.lastMatchIds.some(id=>!current.has(id)))}}

export interface CompareCandidate{id:string;label:string;dates?:string;cabin?:string;guests?:number;taxes?:number;travelCost?:number;freePlay?:number;obc?:number;retailValue?:number;itinerary?:string}
export function compareCandidates(rows:CompareCandidate[]){if(rows.length<2||rows.length>5)throw new Error('COMPARE_REQUIRES_2_TO_5');const fields=(['taxes','travelCost','freePlay','obc','retailValue','guests']as const).map(field=>{const values=rows.map(r=>r[field]);const numeric=values.filter((v):v is number=>typeof v==='number');return{field,values,best:numeric.length?Math.max(...numeric):null,missing:values.map((v,i)=>v==null?rows[i].id:null).filter(Boolean)}});return{rows,fields,scheduleConflicts:rows.flatMap((a,i)=>rows.slice(i+1).filter(b=>a.dates&&a.dates===b.dates).map(b=>[a.id,b.id]))}}

export interface TimelineItem{id:string;tripId:string;kind:string;title:string;start:string;end?:string;localTimeZone?:string;shipTimeZone?:string;source:string}
export function buildUnifiedTimeline(items:TimelineItem[]){const unique=[...new Map(items.map(item=>[`${item.tripId}|${item.kind}|${item.start}|${norm(item.title)}`,item])).values()].sort((a,b)=>a.start.localeCompare(b.start));const conflicts=unique.flatMap((a,i)=>unique.slice(i+1).filter(b=>a.end&&b.start<a.end&&b.tripId===a.tripId).map(b=>[a.id,b.id]));return{items:unique,conflicts,offlinePayload:JSON.stringify(unique)}}

export interface QuickAction{id:string;label:string;recordKinds:RecordKind[];destructive?:boolean;reversible?:boolean;route:string;diagnosticCode:string;voiceOverLabel:string}
export function availableQuickActions(kind:RecordKind,actions:QuickAction[]){return actions.filter(action=>action.recordKinds.includes(kind)).map(action=>({...action,requiresConfirmation:Boolean(action.destructive),offersUndo:Boolean(action.reversible)}))}

export interface ScreenHelp{id:string;screen:string;concise:string;details:string;formulas?:string[];limitations?:string[];recordRoutes?:string[]}
export function explainScreen(screen:string,registry:ScreenHelp[],mode:'concise'|'detailed'='concise'){const help=registry.find(row=>row.screen===screen);if(!help)return{available:false,text:'Help metadata has not been registered for this screen.'};return{available:true,text:mode==='concise'?help.concise:[help.details,...(help.formulas??[]),...(help.limitations??[])].join('\n'),recordRoutes:help.recordRoutes??[]}}
