import type { ProvenanceLink, ProvenanceSourceType } from '@/types/provenance';
import { createProvenanceLink } from './provenance';
import { storeProvenanceLinks } from '@/lib/database/HealthTrustDatabase';

type Domain = ProvenanceLink['entityType'];
const FIELD_REGISTRY: Record<Domain, string[]> = {
  loyalty: ['tier', 'points', 'currentPoints', 'captainsClubPoints', 'blueChipPoints', 'memberNumber'],
  casino: ['points', 'pointsEarned', 'casinoPoints', 'coinIn', 'winLoss', 'winnings', 'theoreticalLoss', 'estimatedHours', 'adt'],
  financial: ['retailValue', 'retailPrice', 'stateroomValue', 'paid', 'amountPaid', 'taxes', 'fees', 'discountValue', 'compValue', 'obc', 'freePlay', 'winnings', 'netCash'],
  certificate: ['certificateCode', 'points', 'issueDate', 'expirationDate', 'tradeInValue', 'awardType'],
  weather: ['temperature', 'windSpeed', 'windDirection', 'waveHeight', 'wavePeriod', 'warning', 'forecast'],
  offer: ['offerCode', 'title', 'expirationDate', 'value', 'offerValue', 'points', 'pointsRequired', 'cabinType', 'cabinCategory', 'stateroomValue', 'guestCount', 'guests', 'guestsInfo', 'freePlay', 'obc'],
  cruise: ['shipName', 'sailDate', 'returnDate', 'nights', 'itineraryName', 'itinerary', 'cabinType', 'cabinCategory', 'guestCount', 'guests', 'guestsInfo', 'reservationNumber', 'seaDays', 'portDays', 'goldenHours', 'casinoScore', 'retailPrice', 'stateroomValue'],
  crew: ['fullName', 'department', 'roleTitle', 'ship', 'sailingDate', 'recognitionStatus'],
  profile: ['name', 'email', 'loyaltyNumber', 'preferredBrand'], preference: ['value'],
};
function text(value: unknown): string { return String(value ?? '').trim(); }
function inferSource(record: Record<string, unknown>, domain: Domain): ProvenanceSourceType { const source = text(record.source ?? record.parserSource ?? record.importSource ?? record.provider).toLowerCase(); if (source.includes('manual')) return 'manual_entry'; if (source.includes('csv') || source.includes('import')) return 'imported_csv'; if (source.includes('receipt') || source.includes('invoice')) return 'receipt'; if (domain === 'certificate' || source.includes('pdf')) return 'parsed_certificate'; if (domain === 'weather' || source.includes('noaa') || source.includes('weather')) return 'official_weather'; if (source.includes('estimate') || record.estimated === true) return 'estimate'; if (source.includes('derived') || record.isDerived === true || record.formula || record.calculationFormula) return 'derived_calculation'; if (source.includes('backup')) return 'backup_restore'; if (source.includes('local') || source.includes('saved profile') || source.includes('database')) return 'local_database'; return 'provider_sync'; }
function idOf(record: Record<string, unknown>, domain: Domain, index: number): string { return text(record.id ?? record.recordId ?? record.cruiseId ?? record.certificateCode ?? record.offerCode ?? record.memberNumber) || `${domain}-${index}`; }

export function buildDomainProvenanceLinks(domain: Domain, records: Array<Record<string, unknown>>, ownerId: string | null): ProvenanceLink[] {
  return records.flatMap((record, index) => { const entityId = idOf(record, domain, index); const sourceType = inferSource(record, domain); const observedAt = text(record.updatedAt ?? record.syncedAt ?? record.parsedAt ?? record.retrievedAt ?? record.createdAt) || new Date().toISOString(); const sourceRecord = text(record.sourceRecord ?? record.sourceFile ?? record.sourceUrl ?? record.provider) || `${sourceType}:${entityId}`; const formula = text(record.formula ?? record.calculationFormula) || null; const suppliedConfidence = text(record.confidence).toLowerCase(); const confidence = suppliedConfidence === 'exact' || suppliedConfidence === 'high' || suppliedConfidence === 'medium' || suppliedConfidence === 'low' || suppliedConfidence === 'estimated' ? suppliedConfidence : sourceType === 'estimate' ? 'estimated' : sourceType === 'derived_calculation' ? 'medium' : sourceType === 'provider_sync' || sourceType === 'receipt' ? 'high' : 'medium'; return FIELD_REGISTRY[domain].filter((field) => record[field] !== undefined && record[field] !== null && record[field] !== '').map((field) => createProvenanceLink({ entityType: domain, entityId, field, sourceType, observedAt, ownerId, confidence, sourceRecord, formula: sourceType === 'derived_calculation' || sourceType === 'estimate' ? formula ?? 'Derived by Easy Seas from linked source records.' : null, sourceHash: text(record.sourceHash) || null, parentProvenanceIds: Array.isArray(record.parentProvenanceIds) ? record.parentProvenanceIds.map(String) : [], provider: text(record.provider) || null, notes: text(record.provenanceNotes) || null })); });
}

export async function persistProvenanceSnapshot(input: Partial<Record<Domain, Array<Record<string, unknown>>>>, ownerId: string): Promise<number> { const links = (Object.entries(input) as Array<[Domain, Array<Record<string, unknown>>]>).flatMap(([domain, records]) => buildDomainProvenanceLinks(domain, records ?? [], domain === 'offer' || domain === 'weather' || domain === 'certificate' ? null : ownerId)); await storeProvenanceLinks(links); return links.length; }
