import type { BookedCruise, CalendarEvent, ItineraryDay } from '@/types/models';
import { createDateFromString, formatDateMDY } from '@/lib/date';

const DERIVED_CRUISE_PORT_EVENT_PREFIX = 'derived-cruise-port-';
const LEGACY_CRUISE_EVENT_PREFIX = 'cruise-';

function buildDerivedCruiseEventDescription(cruise: BookedCruise, itineraryDay: ItineraryDay): string {
  const lines: string[] = [];

  if (cruise.shipName) {
    lines.push(cruise.shipName);
  }
  if (cruise.itineraryName) {
    lines.push(cruise.itineraryName);
  }
  if (itineraryDay.arrival) {
    lines.push(`Arrival: ${itineraryDay.arrival}`);
  }
  if (itineraryDay.departure) {
    lines.push(`Departure: ${itineraryDay.departure}`);
  }
  if (itineraryDay.notes) {
    lines.push(itineraryDay.notes);
  }
  if (cruise.reservationNumber) {
    lines.push(`Reservation: ${cruise.reservationNumber}`);
  }

  return lines.join('\n');
}

function buildDerivedCruisePortEvent(cruise: BookedCruise, itineraryDay: ItineraryDay): CalendarEvent | null {
  if (!cruise.id || !cruise.sailDate || itineraryDay.isSeaDay || !itineraryDay.port) {
    return null;
  }

  const baseDate = createDateFromString(cruise.sailDate);
  if (Number.isNaN(baseDate.getTime())) {
    console.log('[DerivedCruiseEvents] Skipping invalid sail date for cruise:', cruise.id, cruise.sailDate);
    return null;
  }

  const eventDate = new Date(baseDate);
  const dayOffset = Math.max(0, (itineraryDay.day || 1) - 1);
  eventDate.setDate(eventDate.getDate() + dayOffset);
  const formattedDate = formatDateMDY(eventDate, '-');

  return {
    id: `${DERIVED_CRUISE_PORT_EVENT_PREFIX}${cruise.id}-${itineraryDay.day}`,
    title: `Port Day: ${itineraryDay.port}`,
    startDate: formattedDate,
    endDate: formattedDate,
    start: formattedDate,
    end: formattedDate,
    type: 'cruise',
    sourceType: 'cruise',
    location: itineraryDay.port,
    description: buildDerivedCruiseEventDescription(cruise, itineraryDay),
    cruiseId: cruise.id,
    color: '#22C55E',
    allDay: true,
    notes: itineraryDay.notes,
  };
}

export function buildDerivedCruisePortEvents(cruises: BookedCruise[]): CalendarEvent[] {
  const derivedEvents: CalendarEvent[] = [];

  cruises.forEach((cruise) => {
    if (!cruise.itinerary || cruise.itinerary.length === 0) {
      return;
    }

    cruise.itinerary.forEach((itineraryDay) => {
      const derivedEvent = buildDerivedCruisePortEvent(cruise, itineraryDay);
      if (derivedEvent) {
        derivedEvents.push(derivedEvent);
      }
    });
  });

  return derivedEvents.sort((left, right) => {
    const leftDate = left.startDate || left.start || '';
    const rightDate = right.startDate || right.start || '';
    return leftDate.localeCompare(rightDate) || left.title.localeCompare(right.title);
  });
}

export function isAutoGeneratedCruiseCalendarEvent(event: CalendarEvent): boolean {
  const eventId = event.id || '';

  if (eventId.startsWith(DERIVED_CRUISE_PORT_EVENT_PREFIX)) {
    return true;
  }

  if (
    eventId.startsWith(LEGACY_CRUISE_EVENT_PREFIX)
    && event.type === 'cruise'
    && (event.sourceType === 'cruise' || !event.source)
  ) {
    return true;
  }

  return false;
}

export function mergeCalendarEventsWithDerivedCruiseEvents(
  calendarEvents: CalendarEvent[],
  bookedCruises: BookedCruise[],
): CalendarEvent[] {
  const preservedEvents = calendarEvents.filter((event) => !isAutoGeneratedCruiseCalendarEvent(event));
  const derivedCruiseEvents = buildDerivedCruisePortEvents(bookedCruises);
  const mergedEvents = [...preservedEvents, ...derivedCruiseEvents];

  console.log('[DerivedCruiseEvents] Merging calendar events with derived cruise events:', {
    preservedEvents: preservedEvents.length,
    derivedCruiseEvents: derivedCruiseEvents.length,
    totalEvents: mergedEvents.length,
    cruises: bookedCruises.length,
  });

  return mergedEvents;
}

export function countEffectiveCalendarEvents(
  calendarEvents: CalendarEvent[],
  bookedCruises: BookedCruise[],
): number {
  return mergeCalendarEventsWithDerivedCruiseEvents(calendarEvents, bookedCruises).length;
}
