export const EASYSEAS_APP_VERSION = '13.0.74';
export const EASYSEAS_IOS_BUILD_NUMBER = '445';
export const EASYSEAS_ANDROID_VERSION_CODE = 130107;
export const EASYSEAS_RELEASE_LABEL = `EasySeas ${EASYSEAS_APP_VERSION} (${EASYSEAS_IOS_BUILD_NUMBER})`;
export const EASYSEAS_DIAGNOSTIC_VERSION = `${EASYSEAS_APP_VERSION}-build${EASYSEAS_IOS_BUILD_NUMBER}`;
