export type AnnualCasinoReportConfidence = 'actual' | 'estimated' | 'mixed';

export interface AnnualCasinoHistoricalFact {
  ship: string;
  sailDate: string;
  returnDate: string;
  nights: number;
  retailValue: number;
  amountPaid: number;
  winningsBroughtHome: number;
  pointsEarned: number;
  originalCasinoPoints?: number;
  allocatedCasinoPoints?: number;
  annualReconciliationPoints?: number;
  calculationConfidence: AnnualCasinoReportConfidence;
  notes?: string;
}

/** User-confirmed Royal Caribbean annual report: 2025-04-01 through 2026-04-01. */
export const ANNUAL_CASINO_REPORT_FACTS: AnnualCasinoHistoricalFact[] = [
  { ship: 'Harmony of the Seas', sailDate: '2025-04-20', returnDate: '2025-04-27', nights: 7, retailValue: 4650, amountPaid: 175.25, winningsBroughtHome: 8000, pointsEarned: 2030, originalCasinoPoints: 2030, annualReconciliationPoints: 1150, calculationConfidence: 'actual', notes: 'Raw pasted per-cruise points. Annual account reconciliation points are tracked separately and are not displayed on this cruise row.' },
  { ship: 'Ovation of the Seas', sailDate: '2025-07-29', returnDate: '2025-08-01', nights: 3, retailValue: 1588, amountPaid: 149.10, winningsBroughtHome: 0, pointsEarned: 317, originalCasinoPoints: 317, annualReconciliationPoints: 1150, calculationConfidence: 'actual', notes: 'Raw pasted per-cruise points. Annual account reconciliation points are tracked separately and are not displayed on this cruise row.' },
  { ship: 'Navigator of the Seas', sailDate: '2025-08-01', returnDate: '2025-08-04', nights: 3, retailValue: 1326, amountPaid: 133, winningsBroughtHome: 300, pointsEarned: 650, originalCasinoPoints: 650, annualReconciliationPoints: 1150, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Navigator of the Seas', sailDate: '2025-08-22', returnDate: '2025-08-25', nights: 3, retailValue: 1326, amountPaid: 133, winningsBroughtHome: 300, pointsEarned: 650, originalCasinoPoints: 650, annualReconciliationPoints: 1150, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Star of the Seas', sailDate: '2025-08-27', returnDate: '2025-08-31', nights: 4, retailValue: 6500, amountPaid: 162.37, winningsBroughtHome: 700, pointsEarned: 4581, originalCasinoPoints: 4581, annualReconciliationPoints: 1150, calculationConfidence: 'actual', notes: 'Raw pasted per-cruise points. Annual account reconciliation points are tracked separately and are not displayed on this cruise row.' },
  { ship: 'Navigator of the Seas', sailDate: '2025-09-08', returnDate: '2025-09-12', nights: 4, retailValue: 999, amountPaid: 136.58, winningsBroughtHome: 189, pointsEarned: 976, originalCasinoPoints: 976, annualReconciliationPoints: 1150, calculationConfidence: 'actual', notes: 'Raw pasted per-cruise points. Annual account reconciliation points are tracked separately and are not displayed on this cruise row.' },
  { ship: 'Navigator of the Seas', sailDate: '2025-09-15', returnDate: '2025-09-19', nights: 4, retailValue: 1050, amountPaid: 132.50, winningsBroughtHome: 100, pointsEarned: 817, originalCasinoPoints: 817, annualReconciliationPoints: 1150, calculationConfidence: 'actual', notes: 'Raw pasted per-cruise points. Annual account reconciliation points are tracked separately and are not displayed on this cruise row.' },
  { ship: 'Radiance of the Seas', sailDate: '2025-09-26', returnDate: '2025-10-04', nights: 8, retailValue: 2400, amountPaid: 600, winningsBroughtHome: 780, pointsEarned: 1009, originalCasinoPoints: 1009, annualReconciliationPoints: 1150, calculationConfidence: 'actual', notes: 'Raw pasted per-cruise points. Annual account reconciliation points are tracked separately and are not displayed on this cruise row.' },
  { ship: 'Liberty of the Seas', sailDate: '2025-10-16', returnDate: '2025-10-25', nights: 9, retailValue: 3500, amountPaid: 800, winningsBroughtHome: 1488, pointsEarned: 7482, originalCasinoPoints: 7482, annualReconciliationPoints: 1150, calculationConfidence: 'actual', notes: 'Raw pasted per-cruise points. Annual account reconciliation points are tracked separately and are not displayed on this cruise row.' },
  { ship: 'Quantum of the Seas', sailDate: '2025-11-10', returnDate: '2025-11-14', nights: 4, retailValue: 1528, amountPaid: 137, winningsBroughtHome: 700, pointsEarned: 925, originalCasinoPoints: 925, annualReconciliationPoints: 1150, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Quantum of the Seas', sailDate: '2025-11-17', returnDate: '2025-11-21', nights: 4, retailValue: 1528, amountPaid: 137, winningsBroughtHome: 700, pointsEarned: 925, originalCasinoPoints: 925, annualReconciliationPoints: 1150, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Quantum of the Seas', sailDate: '2025-12-01', returnDate: '2025-12-05', nights: 4, retailValue: 1528, amountPaid: 137, winningsBroughtHome: 700, pointsEarned: 925, originalCasinoPoints: 925, annualReconciliationPoints: 1150, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Quantum of the Seas', sailDate: '2025-12-05', returnDate: '2025-12-10', nights: 5, retailValue: 1446, amountPaid: 221, winningsBroughtHome: 700, pointsEarned: 1250, originalCasinoPoints: 1250, annualReconciliationPoints: 1150, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Quantum of the Seas', sailDate: '2025-12-10', returnDate: '2025-12-15', nights: 5, retailValue: 1446, amountPaid: 221, winningsBroughtHome: 700, pointsEarned: 1250, originalCasinoPoints: 1250, annualReconciliationPoints: 1150, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Quantum of the Seas', sailDate: '2026-01-07', returnDate: '2026-01-13', nights: 6, retailValue: 1206, amountPaid: 25.97, winningsBroughtHome: 700, pointsEarned: 1500, originalCasinoPoints: 1500, annualReconciliationPoints: 1149, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Quantum of the Seas', sailDate: '2026-01-13', returnDate: '2026-01-16', nights: 3, retailValue: 740, amountPaid: 127, winningsBroughtHome: 300, pointsEarned: 700, originalCasinoPoints: 700, annualReconciliationPoints: 1149, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Quantum of the Seas', sailDate: '2026-01-16', returnDate: '2026-01-21', nights: 5, retailValue: 1446, amountPaid: 220.95, winningsBroughtHome: 700, pointsEarned: 1250, originalCasinoPoints: 1250, annualReconciliationPoints: 1149, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Harmony of the Seas', sailDate: '2026-02-22', returnDate: '2026-03-01', nights: 7, retailValue: 4650, amountPaid: 151, winningsBroughtHome: 700, pointsEarned: 1800, originalCasinoPoints: 1800, annualReconciliationPoints: 1149, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Harmony of the Seas', sailDate: '2026-03-01', returnDate: '2026-03-08', nights: 7, retailValue: 4650, amountPaid: 151, winningsBroughtHome: 700, pointsEarned: 1800, originalCasinoPoints: 1800, annualReconciliationPoints: 1149, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  { ship: 'Navigator of the Seas', sailDate: '2026-03-09', returnDate: '2026-03-16', nights: 7, retailValue: 3242, amountPaid: 154.69, winningsBroughtHome: 700, pointsEarned: 1700, originalCasinoPoints: 1700, annualReconciliationPoints: 1149, calculationConfidence: 'mixed', notes: 'Estimated winnings baseline. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
  // The supplied source line says $7,800 winnings but its stated +$167 cash result and the confirmed $19,457 annual winnings total both reconcile to the $300 fallback.
  { ship: 'Navigator of the Seas', sailDate: '2026-03-16', returnDate: '2026-03-20', nights: 4, retailValue: 1025, amountPaid: 133, winningsBroughtHome: 300, pointsEarned: 2000, originalCasinoPoints: 2000, annualReconciliationPoints: 1149, calculationConfidence: 'mixed', notes: 'Winnings use the annual-total-consistent $300 value. Raw pasted per-cruise points; annual account reconciliation points stay separate.' },
];
